### ISSUE TITLE
[Tracking]: code splitting

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#102]
The issue is to tracking todos about code splitting for milestone 1

## Correctness

- [x] ~Prevent exports of entry chunk/module being renamed~

This won't happens.

- [x] #122
- [x] #110

## Enhancements

- [x] #137

## Refactor

- [x] #103

## Misc

- [x] #111

**Comment by algora-pbc** [comment]
💎 **Boshen** is offering a **$10** bounty for this issue
👉 Got a pull request resolving this? Claim the bounty by adding `@algora-pbc /claim #102` in the PR body and joining algora.io

**Comment by Bhavyajain21** [comment]
Can I be assigned?

**Comment by hyf0** [comment]
@Bhavyajain21 Thanks for the enthusiasm. This issue doesn't leave many things to do.

@Boshen was just testing out how to use `algora.io`. We aren't really looking for help for this issue with bounty.
