### ISSUE TITLE
Fix tests__esbuild__packagejson__test_package_json_browser_index_no_ext__config_json case 

### ISSUE THREAD

**Issue by zhusjfaker** [rolldown/rolldown#1089]
After investigating the documentation for oxc-resolver and the esbuild implementation

"rolldown/crates/rolldown/tests/esbuild/packagejson/test_package_json_browser_index_no_ext"

An additional configuration option, resolve, is required for the package to succeed

```json
{
  "config": {
    "input": [
      {
        "name": "entry",
        "import": "./src/entry.js"
      }
    ],
    "resolve":{
      "aliasFields": ["browser"]
    }
  }
}
```

But this configuration item is default in esbuild, I found that rolldown does not add the default alias_fields setting to resolve_option during initialisation, and this configuration item in oxc_resolver also uses the default method by default, do I need to add it in e.g.: " alias_fields: Some(vec![vec!["browser".into()]]),"

You can refer to the test case

https://github.com/zhusjfaker/rolldown/blob/fix/tests__esbuild__packagejson__test_package_json_browser_index_no_ext__config_json/crates/rolldown/tests/fix/mod.rs#L36

@hyf0 @IWANABETHATGUY

**Comment by zhusjfaker** [comment]
@underfin

**Comment by zhusjfaker** [comment]
And I found that the reverse serialisation for "aliasFields" seems to be a bit problematic, maybe because it shows Some(vec<string>) in the json, but it's actually Some(Vec<Vec<string>>). json. Instead, I assign the value in rust

```rust
{
  "config": {
    "input": [
      {
        "name": "entry",
        "import": "./src/entry.js"
      }
    ],
    "resolve":{
      "aliasFields": ["browser"]
    }
  }
}
```

**Comment by zhusjfaker** [comment]
https://github.com/rolldown/rolldown/pull/1075  it has been fixed in #1075

**Comment by hyf0** [comment]
Adding " alias_fields: Some(vec![vec!["browser".into()]])," doesn't make the test passed.

> maybe because it shows Some(vec) in the json, but it's actually Some(Vec<Vec>)

Yes. It's indeed `Vec<Vec<..>>` and expected. I'm looking into the test case.

**Comment by hyf0** [comment]
It's not fixed. It it not bundled correctly.

**Comment by zhusjfaker** [comment]
i will fix the  issue of resolve option ,please don't worry about it @hyf0

**Comment by hyf0** [comment]
The problem here is that how esbuild resolve `./demo-pkg` in `import {browser as a} from './demo-pkg/no-ext'` to `node_modules/demo-pkg`.

There aren't aliases. I thought only bare specifier like `import 'demo-pkg'` could resolve to `node_modules/demo-pkg` instead of `import './demo-pkg'`

**Comment by hyf0** [comment]
I just looked again. Esbuild didn't put `demo-pkg` in `node_modules` while we did. @zhusjfaker Something wrong with the migrating.

**Comment by zhusjfaker** [comment]
> I just looked again. Esbuild didn't put `demo-pkg` in `node_modules` while we did. @zhusjfaker Something wrong with the migrating.

yeah i have found it ,sorry i  have mistake in migrate case
