### ISSUE TITLE
NAPI-RS throwing `Nul` Error while dealing with virtual modules

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#1115]
refs:
- https://github.com/napi-rs/napi-rs/issues/2110

https://github.com/rolldown/rolldown/blob/49d4b5c03ab699d71125782c746d15b9b276821c/crates/rolldown/src/utils/chunk/render_chunk.rs#L76-L78

**Comment by hyf0** [comment]
This is due to the limitation of node-api. `napi_set_named_property` and ``napi_set_named_property` consider `\0` as terminator rather values.

To solve the problem, we first use the workaround:
- Convert the `String` to a custom string type that implements `ToNapiValue` trait and convert the `String` to `JsString` under the hood.

This way would cause a extra napi call for creating `JsString`.

The best practice is to make node-api  `napi_set_named_property` and `napi_set_named_property` support passing string with length to treat `\0` as values instead of terminator.

**Comment by IWANABETHATGUY** [comment]
It seems we can close this issue now.

**Comment by hyf0** [comment]
> It seems we can close this issue now.

https://github.com/rolldown/rolldown/blob/5dd140ed553242d9328f483942d1f4f01daed1c1/crates/rolldown/src/ecmascript/ecma_generator.rs#L51-L56

I had a quick try on removing this code, it will produces some errors.

**Comment by hyf0** [comment]
https://github.com/rolldown/rolldown/pull/2991 fix the issue by using workaround. But the true fix should be done by napi's side.

It could done by enable napi's `experimental` and  `node_version_detect` feature. `node18` is the minimal node version we promise to supported, so no need to consider the compatibility problems for old versions.

https://github.com/napi-rs/napi-rs/blob/f116eaf5e54090db4dca8a00ccdb684543a39e86/crates/napi/src/bindgen_runtime/js_values/map.rs#L31-L38C11

@Brooooooklyn  Any downside about enabling `experimental` feature?
