### ISSUE TITLE
Pass esbuild test `test_package_json_exports_default_over_import_and_require`

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#1128]
- https://github.com/rolldown/rolldown/tree/a3717ad7407a4aec48ad9c9226a23a236f5fa086/crates/rolldown/tests/esbuild/packagejson/.test_package_json_exports_default_over_import_and_require

Blocked by https://github.com/oxc-project/oxc-resolver/issues/160.

**Comment by zhusjfaker** [comment]
https://github.com/rolldown/rolldown/compare/main...zhusjfaker:fix/test_package_json_exports_default_over_import_and_require?expand=1

**Comment by zhusjfaker** [comment]
https://github.com/rolldown/rolldown/pull/1263

**Comment by zhusjfaker** [comment]
oxc-resolver have fixed in version: "1.18.0" ,master please close this issue

**Comment by zhusjfaker** [comment]
@hyf0
