### ISSUE TITLE
test(esbuild/packgaejson): track the progress of packagejson test cases under esbuild.

### ISSUE THREAD

**Issue by zhusjfaker** [rolldown/rolldown#1201]
Current progress  

All of the package_json case number is  **89**

The number of migrated cases is **88**

The number of tests already completed under Rolldown is **59**

The number of tests already under Rolldown that have not been completed are **29**

finish percent is **67%**

<google-sheets-html-origin>
index | case_name | status
-- | -- | --
1 | test_common_js_variable_in_esm_type_module | done
2 | test_package_json_bad_main | done
3 | test_package_json_browser_index_no_ext | done
4 | test_package_json_browser_issue2002_a | done
5 | test_package_json_browser_issue2002_c | done
6 | test_package_json_browser_map_avoid_missing | done
7 | test_package_json_browser_map_module_disabled | done
8 | test_package_json_browser_map_module_to_module | done
9 | test_package_json_browser_map_module_to_relative | done
10 | test_package_json_browser_map_native_module_disabled | done
11 | test_package_json_browser_map_relative_disabled | done
12 | test_package_json_browser_map_relative_to_module | done
13 | test_package_json_browser_map_relative_to_relative | done
14 | test_package_json_browser_no_ext | done
15 | test_package_json_browser_node_modules_index_no_ext | done
16 | test_package_json_browser_node_modules_no_ext | done
17 | test_package_json_browser_over_main_node | done
18 | test_package_json_browser_over_module_browser | done
19 | test_package_json_browser_string | done
20 | test_package_json_browser_with_main_node | done
21 | test_package_json_browser_with_module_browser | done
22 | test_package_json_disabled_type_module_issue3367 | done
23 | test_package_json_dual_package_hazard_import_and_require_browser | done
24 | test_package_json_dual_package_hazard_import_and_require_force_module_before_main | done
25 | test_package_json_dual_package_hazard_import_and_require_implicit_main | done
26 | test_package_json_dual_package_hazard_import_and_require_implicit_main_force_module_before_main | done
27 | test_package_json_dual_package_hazard_import_and_require_same_file | done
28 | test_package_json_dual_package_hazard_import_and_require_separate_files | done
29 | test_package_json_dual_package_hazard_import_only | done
30 | test_package_json_dual_package_hazard_require_only | done
31 | test_package_json_exports_alternatives | done
32 | test_package_json_exports_browser | done
33 | test_package_json_exports_custom_conditions | done
34 | test_package_json_exports_entry_point_import_over_require | done
35 | test_package_json_exports_entry_point_main_only | done
36 | test_package_json_exports_entry_point_module_over_main | done
37 | test_package_json_exports_entry_point_require_only | done
38 | test_package_json_exports_import_over_require | done
39 | test_package_json_exports_neutral | done
40 | test_package_json_exports_node | done
41 | test_package_json_exports_not_exact_missing_extension | done
42 | test_package_json_exports_order_independent | done
43 | test_package_json_exports_pattern_trailers | done
44 | test_package_json_exports_require_over_import | done
45 | test_package_json_exports_wildcard | done
46 | test_package_json_import_self_using_import | done
47 | test_package_json_import_self_using_import_scoped | done
48 | test_package_json_import_self_using_require | done
49 | test_package_json_import_self_using_require_scoped | done
50 | test_package_json_imports | done
51 | test_package_json_imports_error_unsupported_directory_import | done
52 | test_package_json_imports_remap_to_other_package | done
53 | test_package_json_main | done
54 | test_package_json_main_fields_a | done
55 | test_package_json_main_fields_b | done
56 | test_package_json_module | done
57 | test_package_json_neutral_explicit_main_fields | done
58 | test_package_json_subpath_import_node_builtin_issue3485 | done
59 | test_package_json_type_should_be_types | done

**Comment by zhusjfaker** [comment]
<google-sheets-html-origin>
index | case_name | issue | mr | status
-- | -- | -- | -- | --
1 | .test_package_json_browser_issue2002_b | https://github.com/oxc-project/oxc-resolver/issues/159 |  https://github.com/rolldown/rolldown/pull/1262 |  done
2 | .test_package_json_exports_alternatives | https://github.com/rolldown/rolldown/issues/1174 |   |  
3 | .test_package_json_exports_default_over_import_and_require | https://github.com/oxc-project/oxc-resolver/issues/160 |  https://github.com/rolldown/rolldown/pull/1263 |  done
4 | .test_package_json_exports_error_invalid_module_specifier | https://github.com/rolldown/rolldown/issues/1174 |   |  
5 | .test_package_json_exports_error_invalid_package_configuration | https://github.com/rolldown/rolldown/issues/1174 |   |  
6 | .test_package_json_exports_error_invalid_package_target | https://github.com/rolldown/rolldown/issues/1174 |   |  
7 | .test_package_json_exports_error_missing_trailing_slash | https://github.com/rolldown/rolldown/issues/1174 |   |  
8 | .test_package_json_exports_error_module_not_found | https://github.com/rolldown/rolldown/issues/1174 |   |  
9 | .test_package_json_exports_error_package_path_not_exported | https://github.com/rolldown/rolldown/issues/1174 |   |  
10 | .test_package_json_exports_error_unsupported_directory_import | https://github.com/rolldown/rolldown/issues/1174 |   |  
11 | .test_package_json_exports_exact_missing_extension | https://github.com/rolldown/rolldown/issues/1174 |   |  
12 | .test_package_json_exports_must_use_import | https://github.com/rolldown/rolldown/issues/1174 |   |  
13 | .test_package_json_exports_must_use_require | https://github.com/rolldown/rolldown/issues/1174 |   |  
14 | .test_package_json_exports_no_conditions_match | https://github.com/rolldown/rolldown/issues/1174 |   |  
15 | .test_package_json_exports_not_exact_missing_extension_pattern | https://github.com/rolldown/rolldown/issues/1174 |   |  
16 | .test_package_json_exports_reverse_lookup | https://github.com/rolldown/rolldown/issues/1174 |   |  
17 | .test_package_json_import_self_using_import_failure |   |   |  
18 | .test_package_json_import_self_using_require_failure |   |   |  
19 | .test_package_json_imports_error_equals_hash |   |   |  
20 | .test_package_json_imports_error_missing_remapped_package |   |   |  
21 | .test_package_json_imports_error_starts_with_hash_slash |   |   |  
22 | .test_package_json_imports_invalid_package_configuration |   |   |  
23 | .test_package_json_main_fields_error_message_default |   |   |  
24 | .test_package_json_main_fields_error_message_empty |   |   |  
25 | .test_package_json_main_fields_error_message_not_included |   |   |  
26 | .test_package_json_neutral_no_default_main_fields |   |   |  
27 | .test_package_json_reverse_package_exports_issue3377 |   |   |  
28 | .test_package_json_syntax_error_comment |   |  https://github.com/rolldown/rolldown/pull/1251 |  
29 | .test_package_json_syntax_error_trailing_comma |   |  #1251  |

**Comment by zhusjfaker** [comment]
https://github.com/rolldown/rolldown/issues/1185

**Comment by zhusjfaker** [comment]
Not yet migrated as the global package environment cannot be simulated

**TestPackageJsonNodePathsIssue2752**

**Comment by IWANABETHATGUY** [comment]
This is tracked by `esbuild-diff` tools, so closed.
