### ISSUE TITLE
Types of the Rollup plugins are not compatible with rolldown's `Plugin` type.

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#1273]

**Comment by hyf0** [comment]
The current intension of `Plugin` type of rolldown is users could know what can and can't do with rolldown's `Plugin` type. But this does cause consistency compared to rollup's `Plugin` type.

**Comment by zhusjfaker** [comment]
mark

**Comment by hyf0** [comment]
We try to be best compatible with rollup even in types. Unsupported API would be marked with `@deprected` and using them would cause runtime error. See #1289 for example.
