### ISSUE TITLE
Emit `"use strict"` properly

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#1277]
Context:
- https://github.com/rolldown/rolldown/issues/1264#issuecomment-2137010111

This issue contains following steps:

1. Research on how esbuild and rollup deal with `"use strict"`
2. Find out the best practice for rolldown
3. Implement it in rolldown

**Comment by yyx990803** [comment]
ESM is strict by default so it should just be removed when output is ES?

Also if source is all ESM it means the output should be all ESM, i.e. use strict at the top of each chunk. But definitely need to do a bit research for non-ESM output.

**Comment by hyf0** [comment]
Add a document on how rolldown gonna handle  `"use strict"`. https://github.com/rolldown/rolldown/pull/1279

If there aren't other arguments, I will follow what the doc said.

**Comment by yyx990803** [comment]
#1279 looks good to me.
