### ISSUE TITLE
Support `base64` loader

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#1297]
## Related

- https://esbuild.github.io/content-types/#base64
- https://github.com/rolldown/rolldown/blob/e88c85d7cf6b60ee04a9a901c8a7c033c4d7ad5d/crates/rolldown/src/utils/parse_to_ast.rs#L26-L56
- https://github.com/rolldown/rolldown/blob/e88c85d7cf6b60ee04a9a901c8a7c033c4d7ad5d/crates/rolldown/src/utils/normalize_options.rs#L15-L40

**Comment by ikkz** [comment]
Hi, I want to implement this loader.

**Comment by hyf0** [comment]
> Hi, I want to implement this loader.

Nice. Thank you in advance.
