### ISSUE TITLE
Support empty loader

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#1298]
## Related

- https://esbuild.github.io/content-types/#empty-file
- https://github.com/rolldown/rolldown/blob/e88c85d7cf6b60ee04a9a901c8a7c033c4d7ad5d/crates/rolldown/src/utils/parse_to_ast.rs#L26-L56
- https://github.com/rolldown/rolldown/blob/e88c85d7cf6b60ee04a9a901c8a7c033c4d7ad5d/crates/rolldown/src/utils/normalize_options.rs#L15-L40

**Comment by RayZhao1998** [comment]
I'm willing to work on this.

**Comment by hyf0** [comment]
> I'm willing to work on this.

Cool. Thank you in advanced.
