### ISSUE TITLE
Support dataurl loader

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#1299]
## Related

- https://esbuild.github.io/content-types/#data-url
- https://github.com/rolldown/rolldown/blob/e88c85d7cf6b60ee04a9a901c8a7c033c4d7ad5d/crates/rolldown/src/utils/parse_to_ast.rs#L26-L56
- https://github.com/rolldown/rolldown/blob/e88c85d7cf6b60ee04a9a901c8a7c033c4d7ad5d/crates/rolldown/src/utils/normalize_options.rs#L15-L40

**Comment by hyf0** [comment]
WARNING⚠️

Be aware this is a difficult task. We would very much welcome contributions, but please be aware that Rolldown's maintainers have limited time to provide support or feedback. Please assess your understanding of the problem, and ability to tackle it on your own without a great deal of outside help before diving in.


We are of course very happy to discuss and answer questions. But if you're fairly new to Rust, or unfamiliar with the subject of this issue, this one is probably not for you. please take a look at other [good first issues](https://github.com/rolldown/rolldown/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) and take the one you are familiar with if you're keen to get involved in Rolldown.

**Comment by 7086cmd** [comment]
I made a small impl for pngs, svgs, converting them into DataUrl with the help of crates `base64` and `urlencoding`: [https://github.com/7086cmd/image-to-dataurl](https://github.com/7086cmd/image-to-dataurl). I am trying to bench its performance now.

**Comment by 7086cmd** [comment]
The bench result on my M2 Pro is:

```
test a_black_hole                ... bench:  52,146,033.30 ns/iter (+/- 1,790,249.19)
test bench_encode_a_little_large ... bench:     173,840.62 ns/iter (+/- 4,157.34)
test bench_encode_bits           ... bench:      21,507.68 ns/iter (+/- 553.21)
test bench_encode_svgs           ... bench:       9,513.51 ns/iter (+/- 287.87)
```

The [image](https://en.wikipedia.org/wiki/File:J._M._Flagg,_I_Want_You_for_U.S._Army_poster_(1917).jpg) for `a_black_hole` is about `83.5 MB`, and others can be seen in the repository, including a `Honkai: Star Rail` svg icon made by `articons`, and a snapshot in `400 KB`.

**Comment by 7086cmd** [comment]
It seems that #1352 has solved this issue...?

**Comment by 7086cmd** [comment]
#1367 may be a solution for the Data Url loader.
