### ISSUE TITLE
Support text loader

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#1300]
## Related

- https://esbuild.github.io/content-types/#text
- https://github.com/rolldown/rolldown/blob/e88c85d7cf6b60ee04a9a901c8a7c033c4d7ad5d/crates/rolldown/src/utils/parse_to_ast.rs#L26-L56
- https://github.com/rolldown/rolldown/blob/e88c85d7cf6b60ee04a9a901c8a7c033c4d7ad5d/crates/rolldown/src/utils/normalize_options.rs#L15-L40

**Comment by Cecil0o0** [comment]
Could I have a try for this task?

**Comment by hyf0** [comment]
> Could I have a try for this task?

Of course. Thanks in advanced.
