### ISSUE TITLE
A repo for recording bundler comparisons

### ISSUE THREAD

**Issue by Boshen** [rolldown/rolldown#1404]
The repo needs to use the latest versions of modern bundlers that are production ready, and keep a record of

* bundle size with default condition and its runtime speed
* bundle size with best compression settings and its runtime speed

The bundlers to compare against:

* rollup
* webpack
* vite
* parcel
* esbuild

Nightly versions should be used if they exist.

The benchmark files:

* threejs 10x
* vue
* something bigger, such as https://github.com/calcom/cal.com

References:

* https://github.com/sapphi-red/performance-compare
* https://github.com/privatenumber/minification-benchmarks

**Comment by robpalme** [comment]
Typo:  rolldown->rollup

**Comment by Boshen** [comment]
> Typo: rolldown->rollup

Thank you for the view! Edited.

**Comment by IWANABETHATGUY** [comment]
Closed in favor of https://github.com/rolldown/metric
