### ISSUE TITLE
Support banner  footer Hooks 

### ISSUE THREAD

**Issue by underfin** [rolldown/rolldown#1417]
The hooks supported need to some step.
- add rust plugin function and called it at bundle, you could follow `renderChunk` at [here](https://github.com/rolldown/rolldown/blob/main/crates/rolldown_plugin/src/plugin.rs#L84)
- add rust side binding, you can follow `renderChunk` at [rust side](https://github.com/rolldown/rolldown/blob/main/crates/rolldown_binding/src/options/plugin/js_plugin.rs#L165) and [js side](https://github.com/rolldown/rolldown/blob/main/packages/rolldown/src/plugin/bindingify-output-hooks.ts#L30)
-  implement `ChunkInfo` and using it at hooks(it could be a single pr)
- add test for it at [here](https://github.com/rolldown/rolldown/tree/main/packages/rolldown/tests/fixtures/plugin)

The rollup document at [here](https://rollupjs.org/plugin-development/#banner)

**Comment by komyg** [comment]
Hi @underfin, I'd like to work on this issue.
