### ISSUE TITLE
Question: should we add a conflict heavy benchmark case to avoid regressing `Renamer` ? 

### ISSUE THREAD

**Issue by IWANABETHATGUY** [rolldown/rolldown#1466]
related to : https://github.com/rolldown/rolldown/pull/1461

**Comment by Boshen** [comment]
yes

**Comment by hyf0** [comment]
I guess we just add the benchmark input of turbopack benchmark suite. Just add to rust benchmark of rolldown would be enough, since we are just comparing ourselves.
