### ISSUE TITLE
Using builtin `assert.expect` instead of `console.log` in snapshot testing

### ISSUE THREAD

**Issue by IWANABETHATGUY** [rolldown/rolldown#1471]
use `assert.expect` as possible as we could

- [ ] │   ├── bundler_ts
- [ ]  │   ├── dce 
- [ ]  │   ├── default
- [ ]  │   ├── glob
- [ ] │   ├── import_star
- [ ] │   ├── import_star_ts
- [ ] │   ├── loader
- [ ] │   ├── lower
- [ ] │   ├── packagejson
- [ ] │   └── splitting
├── fixtures
- [ ] │   ├── cjs_compat
- [ ] │   ├── code_splitting
- [ ] │   ├── deconflict
- [ ] │   ├── errors
- [ ] │   ├── function
- [ ] │   ├── issues
- [ ] │   ├── loaders
- [ ] │   ├── misc
- [ ] │   ├── rollup
- [ ] │   ├── tree_shaking
- [ ] │   └── warnings

**Comment by Boshen** [comment]
Can you link the code so you can add a "good first issue" label?

**Comment by hyf0** [comment]
Might wanna consider #1378. We will run our tests using node18 and node20.

**Comment by IWANABETHATGUY** [comment]
> Might wanna consider #1378. We will run our tests using node18 and node20.

Not sure what exactly node18 version do you mean, but there is no compatible issue when I try `node v18.19.0`

![image](https://github.com/rolldown/rolldown/assets/17974631/5a8fd0c9-2eaa-45d2-ae9d-e00f3c7b53d6)

**Comment by hyf0** [comment]
> > Might wanna consider #1378. We will run our tests using node18 and node20.
> 
> Not sure what exactly node18 version do you mean, but there is no compatible issue when I try `node v18.19.0`
> 
> ![image](https://private-user-images.githubusercontent.com/17974631/344392484-5a8fd0c9-2eaa-45d2-ae9d-e00f3c7b53d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2NjY0MjIsIm5iZiI6MTcxOTY2NjEyMiwicGF0aCI6Ii8xNzk3NDYzMS8zNDQzOTI0ODQtNWE4ZmQwYzktMmVhYS00NWQyLWFlOWQtZTAwZjNjN2I1M2Q2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDEzMDIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1NDI2NjA3OGM2MzVmMDc2ZjVmYTI3M2VlOGMxMTI1Mjc3ZTY4M2JhMjYyMWEyYzMyMmUyMjg3ZTZhY2JkNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5x4gEfrwUDHHqlCMJmAJLCjcIusdPGEeR__9OIh4bD0)

---

The latest ndoe18 and node20 version.

Cool. Just make sure we aren't use API that only node22 supported. Some node tests uses `import.meta.dirname`, which make them not runnable under node18.
