### ISSUE TITLE
Failed tests of esbuild/bundler_ts

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#1475]
## crates/rolldown/tests/esbuild/bundler_ts/enum_rules_from_type_script_5_0

```
called `Result::unwrap()` on an `Err` value: Parse failed, got [
    OxcDiagnostic {
        inner: OxcDiagnosticInner {
            message: "Expected `,` but found `Identifier`",
            labels: Some(
                [
                    LabeledSpan {
                        label: Some(
                            "`,` expected",
                        ),
                        span: SourceSpan {
                            offset: SourceOffset(
                                877,
                            ),
                            length: 2,
                        },
                        primary: false,
                    },
                ],
            ),
            help: None,
            severity: Error,
        },
    },
]
```

## crates/rolldown/tests/esbuild/bundler_ts/export_type_issue379

Wrong transpile result

oxc: https://oxc-project.github.io/oxc/playground/?code=3YCAAIC2gICAgICAgIC6nsrEgtfuY2JfqQYcWmkF%2FKbw5SpTY%2B4FdrYsMbJ6Olvmq%2FozNk6vr7gC4j4CTt9f2Miff72IQIA%3D

expected: https://www.typescriptlang.org/play/?#code/C4TwDgpgBAKhDOwoF4oFEA2EC2EB2wAUFkgGYD25KUAjAEwDMhEAHmOQE5IDesCwAGigUqAXyA

**Comment by Dunqing** [comment]
Related to https://github.com/oxc-project/oxc/issues/3827
