### ISSUE TITLE
Enable esbuild's tests which are related to typescript

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#1476]
- https://github.com/rolldown/rolldown/tree/main/crates/rolldown/tests/esbuild/bundler_ts
- https://github.com/rolldown/rolldown/tree/main/crates/rolldown/tests/esbuild/import_star_ts

refs:

- #1475

**Comment by shulaoda** [comment]
Does this issue seem to have been done? Should we close all related issues?

**Comment by IWANABETHATGUY** [comment]
Not really, some of them are still failing, so not enabled yet.

**Comment by IWANABETHATGUY** [comment]
not needed
