### ISSUE TITLE
chore(deps): The conflict versions of latest `cargo-binstall` and rust toolchain.

### ISSUE THREAD

**Issue by 7086cmd** [rolldown/rolldown#1482]
Hello!

In the latest `cargo-bininstall` package, it only supports Rust `1.79.0`, so that current user can't successfully run `just setup` successfully.

I am unsure whether to define the `bininstall` version or update our Rust version to `1.79.0`, which doesn't conflict to current code because I ran `just test` successfully with `1.79.0`.

**Comment by Boshen** [comment]
Probably better to use the prebuilt binary `curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash` as instructed in its README https://github.com/cargo-bins/cargo-binstall?tab=readme-ov-file#installation

**Comment by IWANABETHATGUY** [comment]
Our rust version is already https://github.com/rolldown/rolldown/blob/main/rust-toolchain.toml, `1.79.0`

**Comment by 7086cmd** [comment]
Ok, thanks. It seems that we can specify a version in `justfile` so that conflicts won't happen then.
