### ISSUE TITLE
Allow output info of module and chunk info

### ISSUE THREAD

**Issue by IWANABETHATGUY** [rolldown/rolldown#1493]
Collecting and output stats is not trivial (we could reimplement it in the future), but for now, only output used exports of each module and chunk graph info is enough. it is especially useful when writing a tool to compare output with another bundler.

**Comment by hyf0** [comment]
Do you need it from rust side or js side? I thought we already emit status info as rollup did.

**Comment by IWANABETHATGUY** [comment]
let me have a look

**Comment by IWANABETHATGUY** [comment]
Closed as it is stale.
