### ISSUE TITLE
Emit semantic error from oxc

### ISSUE THREAD

**Issue by Boshen** [rolldown/rolldown#1494]
The semantic builder also returns JavaScript syntax errors.

https://github.com/rolldown/rolldown/blob/87ec563e8bc1a2241d80a40452c8dc7c6c59ad06/crates/rolldown_oxc_utils/src/oxc_ast/helpers.rs#L14-L21

https://github.com/oxc-project/oxc/blob/54c653ebd44e0d5968dfac0a983c7f152dede732/crates/oxc_semantic/src/builder.rs#L87

You may abort the program if any error occours.

**Comment by IWANABETHATGUY** [comment]
bundler is different from the traditional compiler, it follows code in code out, so we should emit the diagnostic and continue bundling the project unless we meet a unrecover error.

**Comment by hyf0** [comment]
Yeah. We need to distinguish the type of errors to see if we emit warning or error for it.

**Comment by komyg** [comment]
Hey @underfin, I'd like to help out on this issue.

**Comment by Boshen** [comment]
Need to emit from this as well https://github.com/rolldown/rolldown/blob/a2bb2cae97e0f79f712c8ff68d116366ee4ecf35/crates/rolldown/src/utils/pre_process_ecma_ast.rs#L35-L38
