### ISSUE TITLE
Refactor oxc related code

### ISSUE THREAD

**Issue by Boshen** [rolldown/rolldown#1495]
`OxcCompiler` or `OxcAst` in `rolldown_oxc_utils` should contain all oxc related code, it's currently all over the place:

* crates/rolldown/src/utils/pre_process_ast.rs
* crates/rolldown/src/utils/tweak_ast_for_scanning.rs
* crates/rolldown/src/utils/fold_const_value.rs
* rates/rolldown/src/utils/call_expression_ext.rs
* etc etc .. 

I assume the core `rolldown` crate should only provide bundling methods, and expose internals via traits (kind of like oop template pattern). I also assume Rolldown will eventually add css and other file support.

Should I do the refactoring?

**Comment by IWANABETHATGUY** [comment]
I agree with you, cc @hyf0

**Comment by hyf0** [comment]
My first intension of `rolldown_oxc_utils` is to provide dx friendly API not all code of rolldown that are related to oxc.

There will be a refactor for moving javascript-related logic to `rolldown_plugin_javascript` but haven't think through the full picture.

As for now, we create the codebase from porting esbuild. These oxc's hardcode of `rolldown` crate fits the architecture.

**Comment by Boshen** [comment]
Let's defer the refactoring when we have finished thinking about how to structure code around plugins.
