### ISSUE TITLE
Failed `tests/esbuild/packagejson/test_package_json_dual_package_hazard_import_and_require_browser`

### ISSUE THREAD

**Issue by IWANABETHATGUY** [rolldown/rolldown#1507]
##  crates/rolldown/tests/esbuild/packagejson/test_package_json_dual_package_hazard_import_and_require_browser
**our** 

```js


//#region node_modules/demo-pkg/module.browser.js
var module_browser_ns, module_browser_default;
var init_module_browser = __esmMin(() => {
	module_browser_ns = {};
	__export(module_browser_ns, {default: () => module_browser_default});
	module_browser_default = 'browser module';
});

//#endregion
//#region src/test-main.js
console.log((init_module_browser(), __toCommonJS(module_browser_ns)));

//#endregion
//#region src/test-module.js
init_module_browser();
console.log(module_browser_default);

//#endregion
```
**esbuild**
```
---------- /Users/user/project/out.js ----------
// Users/user/project/node_modules/demo-pkg/main.browser.js
var require_main_browser = __commonJS({
  "Users/user/project/node_modules/demo-pkg/main.browser.js"(exports, module) {
    module.exports = "browser main";
  }
});

// Users/user/project/src/test-main.js
console.log(require_main_browser());

// Users/user/project/src/test-module.js
var import_demo_pkg = __toESM(require_main_browser());
console.log(import_demo_pkg.default);

```

##

**Comment by hyf0** [comment]
### [crates/rolldown/tests/esbuild/packagejson/test_package_json_dual_package_hazard_import_and_require_browser](https://github.com/rolldown/rolldown/blob/fa347b3a44d7fee7f3edeb1f7b6b26e1fdef2ee2/crates/rolldown/tests/esbuild/packagejson/test_package_json_dual_package_hazard_import_and_require_browser/node_modules/demo-pkg/package.json)

It seems that we resolve to wrong module.

---

```json
{
  "name": "demo-pkg",
  "main": "./main.js",
  "module": "./module.js",
  "browser": {
    "./main.js": "./main.browser.js",
    "./module.js": "./module.browser.js"
  }
}
```

For `import('demo-pkg')` and `require('demo-pkg')`, rolldown resolve to `"./module.js": "./module.browser.js"` for both of them while esbuild resolve to `"./main.browser.js"`.

Not sure if it's a bug `oxc_resolver`. Need @Boshen's view. Rolldown default to `Browser` platform.

https://github.com/rolldown/rolldown/blob/4bb7dc0cd34ebc9f7cc7562b16226546835eedbd/crates/rolldown_resolver/src/resolver.rs#L30-L125

Related issues:

https://github.com/webpack/webpack/issues/4674#issuecomment-355853969

**Comment by Boshen** [comment]
For [crates/rolldown/tests/esbuild/packagejson/test_package_json_dual_package_hazard_import_and_require_browser](https://github.com/rolldown/rolldown/blob/fa347b3a44d7fee7f3edeb1f7b6b26e1fdef2ee2/crates/rolldown/tests/esbuild/packagejson/test_package_json_dual_package_hazard_import_and_require_browser/node_modules/demo-pkg/package.json)

Do you know why `esbuild` returns `./main.browser.js` when esm prioritizes `module`?

**Comment by IWANABETHATGUY** [comment]
let me see how other bundler behave.

**Comment by IWANABETHATGUY** [comment]
Here is webpack output: 
```js
/******/ (() => { // webpackBootstrap
/******/ 	var __webpack_modules__ = ({

/***/ "./a/node_modules/demo-pkg/module.browser.js":
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "default": () => (__WEBPACK_DEFAULT_EXPORT__)
/* harmony export */ });
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = ("browser module");


/***/ }),

/***/ "./a/test-main.js":
/***/ ((__unused_webpack_module, __unused_webpack_exports, __webpack_require__) => {

console.log(__webpack_require__("./a/node_modules/demo-pkg/module.browser.js"));


/***/ })

/******/ 	});

var __webpack_exports__ = {};
// This entry need to be wrapped in an IIFE because it need to be in strict mode.
(() => {
"use strict";

// EXTERNAL MODULE: ./a/test-main.js
var test_main = __webpack_require__("./a/test-main.js");
// EXTERNAL MODULE: ./a/node_modules/demo-pkg/module.browser.js
var module_browser = __webpack_require__("./a/node_modules/demo-pkg/module.browser.js");
;// CONCATENATED MODULE: ./a/test.module.js

console.log(module_browser["default"]);

;// CONCATENATED MODULE: ./a/entry.js



})();

/******/ })()
;

```

**Comment by IWANABETHATGUY** [comment]
webpack just behaves same as us, so it looks like a bug of esbuild.

**Comment by hyf0** [comment]
> // Now that all files have been scanned, look for packages that are imported
> // both with "import" and "require". Rewrite any imports that reference the
> // "module" package.json field to the "main" package.json field instead.

It's a special behavior of esbuild:

https://github.com/evanw/esbuild/blob/9d506806bdd963b02b3d6edf45e717e03dcba785/internal/bundler/bundler.go#L2313-L2330

**Comment by hyf0** [comment]
I personally would prefer the webpack's implementation, which is prefering esm first.

> // This attempts to automatically avoid the "dual package hazard" where a
> // package has both a CommonJS module version and an ECMAScript module
> // version and exports a non-object in CommonJS (often a function). If we
> // pick the "module" field and the package is imported with "require" then
> // code expecting a function will crash.

Esbuild does make a point. But still I would prefer the garbage in, garbage out principle. It's better for users to provide valid input in the first place, rather than expecting the bundler to make them right.

**Comment by IWANABETHATGUY** [comment]
here is parcel output: 
```js
// ... snip

var parcelRegister = parcelRequire.register;
parcelRegister("2CInk", function(module, exports) {

$parcel$defineInteropFlag(module.exports);

$parcel$export(module.exports, "default", () => $1e918d68c5346f77$export$2e2bcd8739ae039);
var $1e918d68c5346f77$export$2e2bcd8739ae039 = "browser module";

});



(0, ($parcel$interopDefault($ipVX5$nodeassert))).deepEqual((parcelRequire("2CInk")), {
    default: "browser main"
});




var $2CInk = parcelRequire("2CInk");
(0, ($parcel$interopDefault($ipVX5$nodeassert))).equal((0, $2CInk.default), "browser module");



```
it is same as us and webpack, I think we should follow main stream bundler's behavior, so closed.

Feel free to reopen
