### ISSUE TITLE
[Tracking]: error/warning mechanism

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#151]
The issue is to tracking todos about error/warning mechanism

- [x] #331
- [x] #154
- [x] Print errors/warnings in node binding

## Enhancements

- [x] #152

**Comment by kinggoesgaming** [comment]
I am currently going through the repo, trying to understand how it is structured and all. After that I do want to work on this.

**Comment by hyf0** [comment]
> I am currently going through the repo, trying to understand how it is structured and all. After that I do want to work on this.

Hi, thanks for the enthusiasm. Currently, the codebase changes fast. At some point in time, I will create issue for contributors. please wait for it.
