### ISSUE TITLE
npm package e2e test infra

### ISSUE THREAD

**Issue by Boshen** [rolldown/rolldown#1519]
We want a e2e test infra:

* add a npm package
* add an entry index.js
* import the package
* add asserts on the exported values from the package

**Comment by IWANABETHATGUY** [comment]
just found this repo, https://github.com/LeoDog896/npm-rank, 
maybe it is also useful for oxc.

**Comment by Boshen** [comment]
All setup is ready here https://github.com/oxc-project/monitor-oxc

**Comment by Boshen** [comment]
Runtime test is in https://github.com/oxc-project/monitor-oxc/blob/main/src/main.test.mjs
