### ISSUE TITLE
[Discussion] test correctness of sourcemap mapping

### ISSUE THREAD

**Issue by IWANABETHATGUY** [rolldown/rolldown#1535]
### What problem does this feature solve?

Currently, we only snapshot the source map, but there is no way to verify if the snapshot is correct or not.
We should investigate a way to verify the correctness of the generated sourcemap automatically

### What does the proposed API look like?

Don't need an API

**Comment by hyf0** [comment]
Rolldown uses `oxc-sourcemap`.

A: If we generated wrong sourcemap due to we passed wrong `Span`. That's our fault.

B: If `oxc-sourcemap` generates wrong sourcemap with correct input, it's oxc's scope.

What part of correctness do you want to test? A? B? or all of them?

**Comment by Boshen** [comment]
Many tests for A, a few for B to guard against accidental regression from upstream.

**Comment by IWANABETHATGUY** [comment]
> Rolldown uses `oxc-sourcemap`.
> 
> A: If we generated wrong sourcemap due to we passed wrong `Span`. That's our fault.
> 
> B: If `oxc-sourcemap` generates wrong sourcemap with correct input, it's oxc's scope.
> 
> What part of correctness do you want to test? A? B? or all of them?

e.g.
https://github.com/rolldown/rolldown/pull/1461/commits/feef991fcc3e6d2de4e54efccc00cbd7bb12a122#diff-898b973c43b5f17f61661fec1f875f719c2843baaf049dd33cecbf6202dcbb62. 
If someone changes the code which affects the soucemap generation, how could we determine if the new source map is correct other than pasting the code to https://evanw.github.io/source-map-visualization .

**Comment by IWANABETHATGUY** [comment]
I just want to find a way to automatically verify the newly generated sourcemap is still right.  I think this is also important for `oxc`, especially when `oxc` started `minifier`

**Comment by underfin** [comment]
The `Sourcemap Visualizer` section is do it, you can see at
https://github.com/rolldown/rolldown/blob/main/crates/rolldown/tests/fixtures/misc/wrapped_esm/artifacts.snap#L39.

The feature is same with https://evanw.github.io/source-map-visualization, example to `(1:7-1:16) " function" --> (27:0-27:9) "\nfunction"`. The `(1:7-1:16)` is a token rangle, The `" function"` is source code for the token range. The left section is original code, the right section is generated code.

> automatically verify the newly generated sourcemap is still right

Actually the sourcemap snapshot is changed, the diff could display something, we should take care of the changed section.

**Comment by IWANABETHATGUY** [comment]
> The `Sourcemap Visualizer` section is do it, you can see at https://github.com/rolldown/rolldown/blob/main/crates/rolldown/tests/fixtures/misc/wrapped_esm/artifacts.snap#L39.
> 
> The feature is same with https://evanw.github.io/source-map-visualization, example to `(1:7-1:16) " function" --> (27:0-27:9) "\nfunction"`. The `(1:7-1:16)` is a token rangle, The `" function"` is source code for the token range. The left section is original code, the right section is generated code.
> 
> > automatically verify the newly generated sourcemap is still right
> 
> Actually the sourcemap snapshot is changed, the diff could display something, we should take care of the changed section.

`Sourcemap` is complicated, and doesn't have any specific pattern, it is hard to verify via code, Closed.
