### ISSUE TITLE
[Infra]: Tracking crate build time.

### ISSUE THREAD

**Issue by IWANABETHATGUY** [rolldown/rolldown#1539]
### What problem does this feature solve?

Avoid introducing `rolldown` crate build time regression unintentionally.

### What does the proposed API look like?

no

**Comment by hyf0** [comment]
Sounds like a benchmark suite. Just record the time and use https://github.com/benchmark-action/github-action-benchmark/tree/master would be enough I guess?

**Comment by IWANABETHATGUY** [comment]
I mean recording the `cargo build --release` time every day or every commit. I am unsure if we can use `github-action-benchmark` to do it, but maybe `time cargo build --release` is enough?

**Comment by Boshen** [comment]
Here's how I do this: https://github.com/oxc-project/monitor-oxc/blob/a0f34edc0c745d0a68ee4991e15046d398468548/.github/workflows/ci.yml#L114
