### ISSUE TITLE
Diagnostics for errors/warnings

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#154]
I had a prototype for this.

For unresolved entry error, we would have a `Dianostic` to show

![image](https://github.com/rolldown-rs/rolldown/assets/49502170/a995e734-c529-4bc4-baeb-ee3779a66852)

rather than the current

https://github.com/rolldown-rs/rolldown/blob/0c9ab02bd89da358a0d9fb9719e85cd63d0f4aad/crates/rolldown/tests/fixtures/errors/unresolved_entry/artifacts.snap#L8-L12

**Comment by hyf0** [comment]
Wonderful reference: https://twitter.com/101babich/status/1720015048926433386

**Comment by milesj** [comment]
miette works wonderfully here: https://crates.io/crates/miette

Also a dropin replacement for `anyhow`

**Comment by hyf0** [comment]
> miette works wonderfully here: https://crates.io/crates/miette
> 
> Also a dropin replacement for `anyhow`

Thank you. That's why I use `ariadne` in https://github.com/rolldown-rs/rolldown/pull/163. `miette` also uses it under the hood. The current error design is still not finished, I will try to see if I could use `miette` directly.

**Comment by Boshen** [comment]
FYI all oxc diagnostics are `miette` wrapped.

**Comment by milesj** [comment]
Gonna take a look at this this week
