### ISSUE TITLE
Same named export imported by different files result in unnecessary as aliases

### ISSUE THREAD

**Issue by yyx990803** [rolldown/rolldown#1548]
### Reproduction link or steps

To reproduce, run `pnpm build vue -r` in https://github.com/vuejs/core/tree/rolldown (make sure to checkout `rolldown` branch)

Then check `packages/vue/dist/vue.esm-browser.js` line 2

### What is expected?

```js
import { parse, parseExpression } from "@babel/parser";
```

### What is actually happening?

The same `parseExpression` import from `@babel/parser` is aliased two times:

```js
import { parse, parseExpression, parseExpression as parseExpression$1, parseExpression as parseExpression$2 } from "@babel/parser";
```

### System Info

```Shell
NA
```

**Comment by hyf0** [comment]
Yeah. That's current esbuild's behavior for dealing with external modules: https://hyrious.me/esbuild-repl/?version=0.23.0&b=e%00entry.js%00import+%7B+parse+%7D+from+%27ext%27%0Aimport+%27.%2Ffoo%27%0Aconsole.log%28parse%29&b=%00foo.js%00import+%7B+parse+%7D+from+%27ext%27%0Aconsole.log%28parse%29&o=--bundle+--splitting+--format%3Desm+--external%3Aext+--outdir%3Ddist

However, I will see how to improve this pattern.
