### ISSUE TITLE
rolldown-cli could not print correct version.

### ISSUE THREAD

**Issue by IWANABETHATGUY** [rolldown/rolldown#1579]
### Reproduction link or steps

install the nightly version of **rolldown**, and run `rolldown --version` it would print `0.11.0`

### What is expected?

it should print the correct nightly version [0.11.1-snapshot-3db8546-20240711002946](https://www.npmjs.com/package/rolldown/v/0.11.1-snapshot-3db8546-20240711002946)

### What is actually happening?

print `0.11.0`

### System Info

```Shell
NA
```

**Comment by hyf0** [comment]
Let me fix it with #1402 too.

**Comment by IWANABETHATGUY** [comment]
Can I take this, I see this has been delayed for a while.

**Comment by 7086cmd** [comment]
```
+ rolldown 0.12.2-snapshot-a82ccc6-20240816002925 (0.12.2 is available)

Done in 7.3s
(base) . rolldown % npx rolldown -v
rolldown v0.12.2
```

The issue has been resolved. (This applies only to the `nightly` build, not to the `canary` build.)

**Comment by IWANABETHATGUY** [comment]
> ```
> + rolldown 0.12.2-snapshot-a82ccc6-20240816002925 (0.12.2 is available)
> 
> Done in 7.3s
> (base) . rolldown % npx rolldown -v
> rolldown v0.12.2
> ```
> 
> Solved.

No, the correct stdout should be: 
rolldown v0.12.2-snapshot-a82ccc6-20240816002925

**Comment by 7086cmd** [comment]
Oh, get it.

> > ```
> > + rolldown 0.12.2-snapshot-a82ccc6-20240816002925 (0.12.2 is available)
> > 
> > Done in 7.3s
> > (base) . rolldown % npx rolldown -v
> > rolldown v0.12.2
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Solved.
> 
> No, the correct stdout should be: rolldown v0.12.2-snapshot-a82ccc6-20240816002925

Is it possible to mark `package.json` as an external dependency to solve this issue?

**Comment by IWANABETHATGUY** [comment]
No, this is an issue related to CI publish workflow
