### ISSUE TITLE
Cannot install app via cargo install --git

### ISSUE THREAD

**Issue by qarmin** [rolldown/rolldown#1585]
### Reproduction link or steps

```
cargo install --git https://github.com/rolldown/rolldown.git
```

### What is expected?

Compiling app

### What is actually happening?

```
error: environment variable `WORKSPACE_DIR` not defined at compile time
 --> crates/rolldown_testing/src/workspace.rs:6:17
  |
6 |   PathBuf::from(env!("WORKSPACE_DIR"))
  |                 ^^^^^^^^^^^^^^^^^^^^^
  |
  = help: use `std::env::var("WORKSPACE_DIR")` to read the variable at run time
  = note: this error originates in the macro `env` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `rolldown_testing` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `rolldown_testing v0.0.1 (https://github.com/rolldown/rolldown.git#593e87e6)`, intermediate artifacts can be found at `/tmp/cargo-installHxha5i`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

```

### System Info

```Shell
System:
    OS: Linux 6.8 Ubuntu 24.04 LTS 24.04 LTS (Noble Numbat)
    CPU: (8) x64 Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
    Memory: 16.12 GB / 23.39 GB
    Container: Yes
    Shell: 5.2.21 - /bin/bash
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    npm: 10.5.2 - ~/.nvm/versions/node/v20.11.1/bin/npm
    pnpm: 9.1.0 - ~/.nvm/versions/node/v20.11.1/bin/pnpm
  Browsers:
    Brave Browser: 126.1.67.123
```

**Comment by Boshen** [comment]
@qarmin is our fuzzer guy who is trying to understand Rolldown so he can build a fuzzer with it.

**Comment by IWANABETHATGUY** [comment]
introduced by https://github.com/rolldown/rolldown/pull/1541.

**Comment by IWANABETHATGUY** [comment]
I don't find other elegant method to get `workspace_dir`

**Comment by Boshen** [comment]
Use https://doc.rust-lang.org/nightly/std/macro.option_env.html and bail testing if the env is not found?

Because `cargo install --git https://github.com/rolldown/rolldown.git` don't have a workspace yet.

**Comment by Boshen** [comment]
Oh wait ... @qarmin, Rolldown is not mean to be installed from `cargo`.

You need to clone the repo and `just build native release`. Can someone help out and show us how to get a local build and run commands on the build?

**Comment by hyf0** [comment]
You can only use rolldown via npm: https://www.npmjs.com/package/rolldown. We don't have the plan to expose rolldown as an binary that could installed with `cargo isntall`.
