### ISSUE TITLE
Throw friendly warning message for ambiguous export

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#1621]
### What problem does this feature solve?

.

### What does the proposed API look like?

- Reference https://github.com/rolldown/rolldown/pull/397 for what the error message looks like
- https://github.com/rolldown/rolldown/blob/24078fb0d2e060d5c51f6c5d82b569139d886320/crates/rolldown_error/src/build_error/error_constructors.rs
- Where you need to report the warning
https://github.com/rolldown/rolldown/blob/24078fb0d2e060d5c51f6c5d82b569139d886320/crates/rolldown/src/stages/link_stage/bind_imports_and_exports.rs#L270

**Comment by shulaoda** [comment]
Can i try it?

**Comment by hyf0** [comment]
> Can i try it?

Of course. Assigned.
