### ISSUE TITLE
Rolldown internal error: GenericFailure

### ISSUE THREAD

**Issue by Sunny-117** [rolldown/rolldown#1625]
### Reproduction link or steps

https://github.com/Sunny-117/tiny-vue/tree/feat/rolldown
```bash
git clone https://github.com/Sunny-117/tiny-vue
git checkout feat/rolldown
pnpm i
pnpm run build
```

### What is expected?

build success

### What is actually happening?

![image](https://github.com/user-attachments/assets/1a8f3982-85dd-4e38-9e25-9bf2ba3dab7c)

### System Info

```Shell
macOS
node20.11.0
pnpm 8.3.1
```

**Comment by IWANABETHATGUY** [comment]
rolldown has builtin `typescript` support, so you don't need to use `typescript` plugin, it worked after tweaking your `rolldown.config.js`: 

```diff
diff --git a/rolldown.config.js b/rolldown.config.js
index ebd03b7..11b4c66 100644
--- a/rolldown.config.js
+++ b/rolldown.config.js
@@ -1,4 +1,4 @@
-import typescript from "@rollup/plugin-typescript";
+// import typescript from "@rollup/plugin-typescript";
 export default {
   input: "./packages/vue/src/index.ts",
   output: [
@@ -12,5 +12,5 @@ export default {
     },
   ],
 
-  plugins: [typescript()],
+  // plugins: [typescript()],
 };
```

**Comment by IWANABETHATGUY** [comment]
BTW, Rolldown is currently in active development and not usable for production yet.
so you may suffer a lot of unexpected error, and for library bundling, you may also get a bigger output, because rollup has the most powerful tree-shaking feature which we don't fully support yet.

**Comment by Sunny-117** [comment]
> BTW, Rolldown is currently in active development and not usable for production yet. so you may suffer a lot of unexpected error, and for library bundling, you may also get a bigger output, because rollup has the most powerful tree-shaking feature which we don't fully support yet.

Thanks a lot. I have one more question regarding the build. Is the product output currently not aligned with rollup? The same configuration but no output file as expected.


by rolldown:
![image](https://github.com/user-attachments/assets/29f00665-97bc-472c-ae32-1dd031a2b244)

by rollup:  main branch

![image](https://github.com/user-attachments/assets/c0a0178c-5f77-4e4e-b32b-b74580f9ce15)

**Comment by IWANABETHATGUY** [comment]
I think it is related to https://github.com/rolldown/rolldown/issues/1270, we don't support `output.file` now.

**Comment by IWANABETHATGUY** [comment]
> > BTW, Rolldown is currently in active development and not usable for production yet. so you may suffer a lot of unexpected error, and for library bundling, you may also get a bigger output, because rollup has the most powerful tree-shaking feature which we don't fully support yet.
> 
> Thanks a lot. I have one more question regarding the build. Is the product output currently not aligned with rollup? The same configuration but no output file as expected.
> 
> by rolldown: ![image](https://private-user-images.githubusercontent.com/73089592/348686105-29f00665-97bc-472c-ae32-1dd031a2b244.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNDQxOTAsIm5iZiI6MTcyMTA0Mzg5MCwicGF0aCI6Ii83MzA4OTU5Mi8zNDg2ODYxMDUtMjlmMDA2NjUtOTdiYy00NzJjLWFlMzItMWRkMDMxYTJiMjQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDExNDQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0OWI2ODMxZTAyYTY5ZDUwZTc2NDRjMTJhZTRjZmFiZTVmOTQ4ZjZjMzcwODYxNjFmODJmNDY5OTI3NTQ2MDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9QEn3d_KXEhIHrfV6r1mipV3Lx3ciIMj1E798I_fgNk)
> 
> by rollup: main branch
> 
> ![image](https://private-user-images.githubusercontent.com/73089592/348686292-c0a0178c-5f77-4e4e-b32b-b74580f9ce15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNDQxOTAsIm5iZiI6MTcyMTA0Mzg5MCwicGF0aCI6Ii83MzA4OTU5Mi8zNDg2ODYyOTItYzBhMDE3OGMtNWY3Ny00ZTRlLWIzMmItYjc0NTgwZjljZTE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDExNDQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhZGI3NDNhZTliMmFhZWVkOWQ5N2JmNDI5ODUyMWE3MmVhODc0YzdjNDRhY2Y5NjNmODgwNTQyYzE4YzcyNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s37F38LingmDHMBylaStaL9y05cTMWB89OT-THP7Dts)

as for output cc @hyf0

**Comment by hyf0** [comment]
`output.file` is supported now. If you still meet this problem with newest rolldown, feel free to reopen this issue.
