### ISSUE TITLE
Convert parsing errors of oxc to rolldown's errors with friendly messages

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#1630]
### What problem does this feature solve?

.

### What does the proposed API look like?

Related code:
- https://github.com/rolldown/rolldown/blob/4d89536f5d034f6819376f8bcb1f7353ad1a0681/crates/rolldown_ecmascript/src/ecma_compiler.rs#L18gm

Should return `Result<EcmaAst, rolldown_error::BuildError>` 

- https://github.com/rolldown/rolldown/blob/4d89536f5d034f6819376f8bcb1f7353ad1a0681/crates/rolldown_ecmascript/src/ecma_compiler.rs#L26

Oxc's errors

- https://github.com/rolldown/rolldown/blob/4d89536f5d034f6819376f8bcb1f7353ad1a0681/crates/rolldown_error/src/events/eval.rs#L24-L35
- https://github.com/rolldown/rolldown/blob/4d89536f5d034f6819376f8bcb1f7353ad1a0681/crates/rolldown/tests/fixtures/warnings/eval/artifacts.snap#L10-L19

Rolldown's error

**Comment by shulaoda** [comment]
Try it. 🙌

**Comment by shulaoda** [comment]
I need some help, this error cannot output a snapshot as it will cause the program to picnic. @hyf0 

- Should I convert the error message that causes the program to picnic?
- In addition, it seems that the type it returns should be `Result<EcmaAst, Vec<BuildDiagnostic>>` ？

**Comment by hyf0** [comment]
@shulaoda Depend on the case, use `anyhow::Result<Result<EcmaAst, Vec<BuildDiagnostic>>>` or `Result<EcmaAst, Vec<BuildDiagnostic>>`.

- `anyhow::Result` is for program errors.
- `Result<EcmaAst, Vec<BuildDiagnostic>>` is for business errors.

We used to treat parsing errors as program errors. And this issue intend to treat them as business errors to provide better error report.
