### ISSUE TITLE
Better error report for ambiguous export

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#1643]
https://hyrious.me/esbuild-repl/?version=0.23.0&b=e%00entry.js%00import+%7B+foo+%7D+from+%27.%2Fproxy%27%0Aconsole.log%28foo%29&b=%00a.js%00export+const+foo+%3D+1&b=%00b.js%00export+const+foo+%3D+2&b=%00proxy.js%00export+*+from+%27.%2Fa%27%0Aexport+*+from+%27.%2Fb%27&o=--bundle+--splitting+--format%3Desm+--external%3Aext+--outdir%3Ddist

Esbuild treats this as an error and has better report. Let's merge this PR for now. I'll open an new issue to port esbuild's behavior.

_Originally posted by @hyf0 in https://github.com/rolldown/rolldown/pull/1634#discussion_r1679021003_

A follow up of #1621.

**Comment by hyf0** [comment]
https://hyrious.me/esbuild-repl/?version=0.23.0&b=e%00entry.js%00import+%7B+foo+%7D+from+%27.%2Fproxy%27%0Aconsole.log%28foo%29&b=%00a.js%00export+const+foo+%3D+1&b=%00b.js%00export+const+foo+%3D+2&b=%00proxy.js%00export+*+from+%27.%2Fa%27%0Aexport+*+from+%27.%2Fb%27&o=--bundle+--splitting+--format%3Desm+--external%3Aext+--outdir%3Ddist

**Comment by shulaoda** [comment]
I will continue to do it.
