### ISSUE TITLE
The `resolveId` need ImportKind info.

### ISSUE THREAD

**Issue by underfin** [rolldown/rolldown#166]
Because the esbuild supported esm and cjs, the resolve provider a `ImportKind: 'import/require-call'` for reference module, but the rollup hasn't it. The vite using it to convert the `require` call module to esm at pre-bundling, see https://github.com/vitejs/vite/blob/main/packages/vite/src/node/optimizer/esbuildDepPlugin.ts#L157.

The rollup `resolveId` has below signature, here has two ways to add kind.
- add a new  filed `kind` at `options` 
- add a new  filed `kind` at `options.custom` 
``` .ts
type ResolveIdHook = (
	source: string,
	importer: string | undefined,
	options: {
		assertions: Record<string, string>;
		custom?: { [plugin: string]: any };
		isEntry: boolean;
	}
) => ResolveIdResult;
```
Hope get some advice for this.

**Comment by hyf0** [comment]
> add a new filed kind at options

I prefer this way. It's

- more intuitive
- still compatible with rollup plugin
