### ISSUE TITLE
Regression on `rollup@function@sequence-expressions-template-tag`

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#1660]
This is a classic one. Esbuild has the issue before. https://github.com/evanw/esbuild/issues/2610

_Originally posted by @hyf0 in https://github.com/rolldown/rolldown/issues/1656#issuecomment-2235574523_

**Comment by hyf0** [comment]
Contexts:
- https://github.com/rolldown/rolldown/pull/1656#issuecomment-2235544211
- https://github.com/evanw/esbuild/issues/2610

**Comment by hyf0** [comment]
https://github.com/oxc-project/oxc/issues/4341

**Comment by IWANABETHATGUY** [comment]
It seems this isssue is fixed

**Comment by hyf0** [comment]
Fixed.
