### ISSUE TITLE
The crate rolldown_ecmascript's test can't pass 

### ISSUE THREAD

**Issue by shulaoda** [rolldown/rolldown#1671]
### Reproduction link or steps

cargo test -p rolldown_ecmascript

### What is expected?

![image](https://github.com/user-attachments/assets/d4d1bc6e-6e4e-4251-88f7-1411c4289c08)

### What is actually happening?

![image](https://github.com/user-attachments/assets/b1ac075f-df83-4602-aa48-522aaf147b79)

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i5-13600KF
    Memory: 17.46 GB / 31.81 GB
  Binaries:
    Node: 18.20.4 - D:\Github\nvm\nodejs\node.EXE
    npm: 10.7.0 - D:\Github\nvm\nodejs\npm.CMD
    pnpm: 9.5.0 - D:\Github\nvm\nodejs\pnpm.CMD
    bun: 1.1.20 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (126.0.2592.81)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    rolldown: workspace:* => 0.12.1
```

### Any additional comments?

Related to #1670 

https://github.com/shulaoda/rolldown/blob/ea3837322a05386bf34526a3a12ec0a42c9acdad/crates/rolldown_ecmascript/Cargo.toml#L15-L23

**Comment by IWANABETHATGUY** [comment]
I can not reproduce, BTW I use linux.

**Comment by IWANABETHATGUY** [comment]
Also, if `rolldown_resolver` could not find `OsFileSystem`, maybe the right fix would be to add the `os` feature in `Cargo.toml` under directory `rolldown_resolver`,  maybe the linked pr is not a correct fix. Can you `cargo clean` and try again?

**Comment by shulaoda** [comment]
> Also, if `rolldown_resolver` could not find `OsFileSystem`, maybe the right fix would be to add the `os` feature in `Cargo.toml` under directory `rolldown_resolver`, maybe the linked pr is not a correct fix. Can you `cargo clean` and try again?

My negligence, please wait for a moment

**Comment by IWANABETHATGUY** [comment]
I tried `cargo clean` and reproduced the issue, and I added `os` in `Cargo.toml` under `rolldown_resolver` directory it  is fixed.
