### ISSUE TITLE
banner should be placed before the generated `use strict` for cjs

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#1706]
cc @hyf0 The rollup `banner` should be prepend at `use strict` for cjs, you could see [amd example]( https://rollupjs.org/repl/?version=4.19.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQSUyMjAxJTIyJTJDJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMmNvZGUlMjIlM0ElMjIlMkYlMkYlMjBOQU1FRCUyMEVYUE9SVFMlNUNuJTJGJTJGJTIwVGhlcmUlMjBhcmUlMjBtYW55JTIwd2F5cyUyMHRvJTIwZXhwb3J0JTIwYmluZGluZ3MlNUNuJTJGJTJGJTIwZnJvbSUyMGFuJTIwRVMyMDE1JTIwbW9kdWxlJTVDbmV4cG9ydCUyMHZhciUyMGZvbyUyMCUzRCUyMDElM0IlNUNuJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwYmFyKCklMjAlN0IlNUNuJTVDdCUyRiUyRiUyMHRyeSUyMGNoYW5naW5nJTIwdGhpcyUyMHRvJTIwJTYwZm9vJTJCJTJCJTYwJTVDbiU1Q3QlMkYlMkYlMjB3aGVuJTIwZ2VuZXJhdGluZyUyMENvbW1vbkpTJTVDbiU1Q3RyZXR1cm4lMjBmb28lM0IlNUNuJTdEJTVDbiU1Q25mdW5jdGlvbiUyMGJheigpJTIwJTdCJTVDbiU1Q3RyZXR1cm4lMjBiYXIoKSUzQiU1Q24lN0QlNUNuJTVDbmV4cG9ydCUyMCU3QiUyMGJheiUyMCU3RCUzQiU1Q25leHBvcnQlMjAqJTIwZnJvbSUyMCcuJTJGcXV4JyUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTJDJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlN0QlMkMlN0IlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwY29uc3QlMjBxdXglMjAlM0QlMjAnUVVYJyUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSUyQyUyMm5hbWUlMjIlM0ElMjJxdXguanMlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyb3V0cHV0JTIyJTNBJTdCJTIyZXNNb2R1bGUlMjIlM0ElMjJpZi1kZWZhdWx0LXByb3AlMjIlMkMlMjJleHBvcnRzJTIyJTNBJTIyYXV0byUyMiUyQyUyMmZvcm1hdCUyMiUzQSUyMmFtZCUyMiU3RCU3RCU3RA==)

_Originally posted by @underfin in https://github.com/rolldown/rolldown/pull/1705#discussion_r1689206084_

**Comment by 7086cmd** [comment]
@hyf0 Handled it in `iife` in #1707. (`cjs` has been already fixed in #1705)

**Comment by 7086cmd** [comment]
Solved in #1707.
