### ISSUE TITLE
[Test] test infra about `composingJsPlugin` 

### ISSUE THREAD

**Issue by IWANABETHATGUY** [rolldown/rolldown#1709]
### What problem does this feature solve?

Make sure `rolldown` output has the same behavior after enabling **experimental?.enableComposingJsPlugins**

### What does the proposed API look like?

N/A

**Comment by hyf0** [comment]
We could run plugin test twice with enabling `composingJsPlugin` and not.

**Comment by IWANABETHATGUY** [comment]
This could be a solution, but we also need some `composingJsPlugin` specific tests.

**Comment by hyf0** [comment]
we could expose the `composingJsPlugin` function to outside and test it using `vitest`. But I wonder if we could test it without exposing it.
