### ISSUE TITLE
`panicked at crates/rolldown/src/utils/chunk/render_chunk_exports.rs:28:54 no entry found for key` when bundling aliased entries with shared cjs dep

### ISSUE THREAD

**Issue by hi-ogawa** [rolldown/rolldown#1722]
### Reproduction link or steps

I was investigating panic in Vite's `playground/alias` https://github.com/rolldown/vite/pull/28#issuecomment-2234949149 and it looks like the same error can be reproduced with this stripped down example:

<details><summary>(Initial repro using `vue` and `@vue/shared`)</summary>

```ts
import * as rolldown from "rolldown";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);

async function main() {
  const bundle = await rolldown.rolldown({
    cwd: import.meta.dirname,
    // works if single entry
    input: ["vue", "foo"],
    resolve: {
      alias: {
        "foo": "vue",
        // works if removed
        "@vue/shared": require.resolve("@vue/shared/dist/shared.cjs.prod.js"),
      },
    }
  });
  await bundle.write({
    format: "esm",
  });
  process.exit(0);
}

main();
```

Also this is the original vite config in the playground:
- https://github.com/vitejs/vite/blob/4126db8a2fc68bc346ed85b61810cc9cf9097c3e/playground/alias/vite.config.js#L20-L26

</details>

_New repro without vue_

https://github.com/hi-ogawa/rolldown/tree/b31fa276a6aa6ee370984652425356b2b1d9e7e8/examples/repro-alias

- `index.js`

```ts
import * as rolldown from "rolldown";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);

async function main() {
  const bundle = await rolldown.rolldown({
    cwd: import.meta.dirname,
    // works if single entry (each one works alone)
    input: [
      "test-dep-main",
      "foo",
    ],
    resolve: {
      alias: {
        "foo": "test-dep-main",
      },
    }
  });
  await bundle.write({
    format: "esm",
  });
  process.exit(0);
}

main();
```

- `test-dep-main/index.js`

```ts
export const main = "main";
export { sub } from "test-dep-sub";
```

- `test-dep-sub/index.cjs`

```ts
module.exports.sub = "sub";
```

- command

```
$ node examples/repro-alias/index.js 
thread 'tokio-runtime-worker' panicked at crates/rolldown/src/utils/chunk/render_chunk_exports.rs:28:54:
no entry found for key
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: Panic in async function] { code: 'GenericFailure' }
```

### What is expected?

Not panic and build should succeed.

### What is actually happening?

```
thread 'tokio-runtime-worker' panicked at crates/rolldown/src/utils/chunk/render_chunk_exports.rs:28:54:
no entry found for key
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### System Info

```Shell
System:
    OS: Linux 6.9 Arch Linux
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-12650H
    Memory: 22.02 GB / 31.06 GB
    Container: Yes
    Shell: 5.2.26 - /usr/bin/bash
  Binaries:
    Node: 20.14.0 - ~/.volta/tools/image/node/20.14.0/bin/node
    npm: 10.7.0 - ~/.volta/tools/image/node/20.14.0/bin/npm
    pnpm: 9.6.0 - ~/.volta/tools/image/node/20.14.0/bin/pnpm
  Browsers:
    Chromium: 126.0.6478.126
  npmPackages:
    rolldown: 0.12.2 => 0.12.2
```

**Comment by hi-ogawa** [comment]
I think I found a simpler repro only using fixture dependencies. https://github.com/hi-ogawa/rolldown/blob/chore-repro-1722/examples/repro-alias/index.js I'll update an issue title and description based on this repro.

I have no idea what's going on internally, but hopefully this might make it easier to debug.

**Comment by hi-ogawa** [comment]
Stripped down repro further without `node_modules` deps https://github.com/hi-ogawa/rolldown/tree/4ea730383ca57998f6c6e064c413e610c909127c/crates/rolldown/tests/fixtures/issues/1722

- `_config.json`

```js
{
  "config": {
    "input": [
      {
        "name": "main",
        "import": "./main.js"
      },
      {
        "name": "foo",
        "import": "foo"
      }
    ],
    "resolve": {
      "alias": [["foo", ["./main.js"]]]
    }
  }
}
```

- `main.js`

```js
export const main = "main";
export { sub } from "./sub.cjs";
```

- `sub.cjs`

```js
module.exports.sub = "sub";
```

**Comment by hyf0** [comment]
https://github.com/rolldown/rolldown/blob/247bc4b185a8cc95b7bc8727b0e81871f333824a/crates/rolldown/src/stages/generate_stage/compute_cross_chunk_links.rs#L222-L227

probably due to not following these changes in the above code

https://github.com/rolldown/rolldown/blob/3d3028452d77854a8cd596a5094d28b37d3ce2ba/crates/rolldown/src/stages/generate_stage/code_splitting.rs#L52-L68

**Comment by hyf0** [comment]
This is bug is about reexport commonjs in shared entries.
