### ISSUE TITLE
Support http-import by default

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#1768]
### What problem does this feature solve?

Allow bundling code like

```ts
// main.ts
import { bgBlue, bold, italic, red } from "https://deno.land/std@0.190.0/fmt/colors.ts";

console.log(bgBlue(italic(red(bold("Hello world!")))));
```

### What does the proposed API look like?

No configuration. It's enabled by default.

## Related

- #1762

**Comment by hyf0** [comment]
- It will only treat patterns like `https://deno.land/std@0.190.0/fmt/colors.ts` as a valid file to fetch. It should has explicit extension. Otherwise, it will follow the current behavior and mark it as external module.

**Comment by 7086cmd** [comment]
Maybe we can use `MIME`? But seems that it may be recognized as `audio/vnd.dlna.mpeg-tts` :joy:.

**Comment by 7086cmd** [comment]
I've implemented a small feature [here](https://github.com/7086cmd/rolldown/tree/feat/http-resolve/crates/rolldown_plugin_http_resolve) (as a native plugin), which uses `oxc` to transform remote file imports into URLs. While native support might be overkill, we could alternatively develop this as an opt-in plugin in Rust.

**Comment by ikkz** [comment]
If it is going to become a built-in feature of Rolldown, caching (and cleaning) of remote files may also need to be considered to speed up repeated builds during the development.

**Comment by 7086cmd** [comment]
> If it is going to become a built-in feature of Rolldown, caching (and cleaning) of remote files may also need to be considered to speed up repeated builds during the development.

Yes, it is required even if the plugin isn't included in this repository. I am also trying to support the cache in my spare time.

**Comment by hyf0** [comment]
A very nice article about http-import: https://deno.com/blog/http-imports. Also is a nice explanation on why we shouldn't enable http-import by default. It's not a recommended pattern.
