### ISSUE TITLE
[Tracking]: Port vite plugin to rolldown rust side

### ISSUE THREAD

**Issue by underfin** [rolldown/rolldown#1826]
Here has a list which we need to port vite plugin to rolldown rust side.

- [x] #1827
- [x] dynamicImportVarsPlugin
- [x] importGlobPlugin
- [x] dataURIPlugin
- [x] manifestPlugin
- [x] #1918
- [x] #1919

**Comment by hyf0** [comment]
Σヽ(ﾟД ﾟ; )ﾉ

**Comment by hi-ogawa** [comment]
Is it planned to have `rolldownCjsExternalPlugin` in https://github.com/rolldown/vite/pull/24 as builtin? or could this be a core bundler feature? (though esbuild chose not to do this as explained in https://github.com/evanw/esbuild/issues/566#issuecomment-735551834)

**Comment by hyf0** [comment]
I can't firmly say it's not gonna be core bundler feature now. But evenw does made a great explanation on this

>  it's impossible in the general case to preserve the semantics of the original code when you do this. It's a lossy transformation

So from this aspect, it's probably not gonna be core bundler feature.

However, you could always make it a builtin plugin if needed just like we did now.
