### ISSUE TITLE
modulePreloadPolyfillPlugin

### ISSUE THREAD

**Issue by underfin** [rolldown/rolldown#1827]
The modulePreloadPolyfillPlugin provides a virtual module for the preload polyfill, the source code see [here](https://github.com/vitejs/vite/blob/main/packages/vite/src/node/plugins/modulePreloadPolyfill.ts).

The rolldown always has a example plugin to do similar things, you could follow [it](https://github.com/rolldown/rolldown/blob/main/crates/rolldown_plugin_wasm/src/lib.rs#L19-L37). You also need to add plugin binding and export it, add test it at [rolldown js side test](https://github.com/rolldown/rolldown/tree/main/packages/rolldown/tests/fixtures/builtin-plugin).

**Comment by shulaoda** [comment]
Try it. 🙌
