### ISSUE TITLE
Use `block_on_spawn_all` instead of `join_all` to resolve entries

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#183]
I'm not sure. `block_on_spawn_all` would run tasks in parallel while `join_all` seems to run them concurrently.

_Originally posted by @hyf0 in https://github.com/rolldown-rs/rolldown/pull/178#discussion_r1383294824_

**Comment by houyunlu** [comment]
Some investigation: 

 ```rs
 async_scoped::Scope::scope_and_block(|scope: &mut TokioScope<'_, _>| {
      iter.into_iter().for_each(|fut| scope.spawn(fut));
    });
 ```

[scope_and_block](https://github.com/houyunlu/async-scoped/blob/2ae12b1baa862a7c8bcd1dec8c5f5ab39b64b173/src/usage.rs#L56-L65) required type to impl `Blocker`,  the    `Blocker` trait implementation of `tokio` runtime https://github.com/houyunlu/async-scoped/blob/2ae12b1baa862a7c8bcd1dec8c5f5ab39b64b173/src/spawner.rs#L79-L88 use `tokio::task::block_in_place` which required `rt-multi-thread` feature of `tokio` , so there is no way we can' make the crate compiled on `wasm` target.

So I decided to use the same function name but different implementations on different platforms, one used `futures::join_all` (for wasm target), one used `async_scoped::Scope::scope_and_block`(for none wasm target).

**Comment by hyf0** [comment]
I think `join_all` + `spawn` with some unsafe could do the same as `scope_and_block`.

>  use the same function name but different implementations on different platforms

IMO, You don't need to do this anymore. Let's keep the current implementation now.

**Comment by houyunlu** [comment]
> I think `join_all` + `spawn` with some unsafe could do the same as `scope_and_block`.
> 
> > use the same function name but different implementations on different platforms
> 
> IMO, You don't need to do this anymore. Let's keep the current implementation now.

I still used the `async_scoped` crate because it has a lot of tests, which should be more robust
