### ISSUE TITLE
[Feature Request]: Emit warnings for commonjs-variable-in-esm

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#1831]
### What problem does this feature solve?

https://hyrious.me/esbuild-repl/?version=0.23.0&b=e%00entry.js%00export+const+a+%3D+1%0Amodule.exports+%3D+%7B%7D&b=%00foo.cjs%00module.exports.foo+%3D+1&o=--bundle+--format%3Desm+--external%3Aext+--outdir%3Ddist

### What does the proposed API look like?

Related code:
- https://github.com/rolldown/rolldown/blob/726f6333ef6f765720bc7a827cb2b315f065c34a/crates/rolldown/src/ast_scanner/mod.rs#L42
- https://github.com/rolldown/rolldown/blob/726f6333ef6f765720bc7a827cb2b315f065c34a/crates/rolldown/src/ast_scanner/mod.rs#L549

**Comment by shulaoda** [comment]
My field, try it. 🙌

**Comment by IWANABETHATGUY** [comment]
sorry, I don't see your comment just now,  I have finished this.
