### ISSUE TITLE
[Bug]: Should not emit twice for the same diagnostic

### ISSUE THREAD

**Issue by IWANABETHATGUY** [rolldown/rolldown#1852]
### Reproduction link or steps

see https://github.com/rolldown/rolldown/issues/1851 as an example.

### What is expected?

Should only emit once.

### What is actually happening?

emit twice.

### System Info

```Shell
n/a
```

**Comment by hyf0** [comment]
Yeah. It's not reach to diagnostic level, which means these errors aren't come from `BuildDiagnostic` but `anyhow::Error`. I guess multiple print come from the parallelism of module tasks.

**Comment by IWANABETHATGUY** [comment]
It came from `runMain`
```js
async function runMain(cmd, opts = {}) {
	const rawArgs = opts.rawArgs || process.argv.slice(2);
	const showUsage$1 = opts.showUsage || showUsage;
	try {
		if (rawArgs.includes("--help") || rawArgs.includes("-h")) {
			await showUsage$1(...await resolveSubCommand(cmd, rawArgs));
			process.exit(0);
		} else if (rawArgs.length === 1 && rawArgs[0] === "--version") {
			const meta = typeof cmd.meta === "function" ? await cmd.meta() : await cmd.meta;
			if (!meta?.version) {
				throw new CLIError("No version specified", "E_NO_VERSION");
			}
			consola.log(meta.version);
		} else {
			await runCommand(cmd, {rawArgs});
		}
	} catch (error) {
		const isCLIError = error instanceof CLIError;
		if (!isCLIError) {
			consola.error(error, "\n");
		}
		if (isCLIError) {
			await showUsage$1(...await resolveSubCommand(cmd, rawArgs));
		}
		// consola.error(error.message);
		process.exit(1);
	}
}
```

**Comment by shulaoda** [comment]
This problem seems to be caused by CLI.
<img width="926" alt="image" src="https://github.com/user-attachments/assets/65dcffc2-cf45-4e33-91c8-92b1b6f1b003">

**Comment by IWANABETHATGUY** [comment]
I will try to file an issue upstream, if they are not willing to fix this issue, maybe we need to fork our own cli
