### ISSUE TITLE
[Bug]: Wrong import behavior in dynamic imports in CJS.

### ISSUE THREAD

**Issue by 7086cmd** [rolldown/rolldown#1856]
It should be a bug in handling the dynamic import already appearing in the main branch, which infers the common chunk as an entry point and removed all of exports.

_Originally posted by @7086cmd in https://github.com/rolldown/rolldown/pull/1812#discussion_r1702769903_

It is strange that the former bug was solved.

But we should use `Promise.resolve().then...` instead of `require` in CJS format.

**Comment by 7086cmd** [comment]
More details:

### Actual Behavior

```js
import("./shared-zbREASMc.js").then((x) => {
	console.log(x.shared);
});
```

### Expected Behavior in [Rollup REPL](https://rollupjs.org/repl/?version=4.20.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmltcG9ydCgnLiUyRmZpbGUnKS50aGVuKChpbXBvcnRlZCklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwYXNzZXJ0LnN0cmljdEVxdWFsKGltcG9ydGVkLnNoYXJlZCUyQyUyMCdzaGFyZWQnKSU1Q24lN0QpJTVDbiU1Q25leHBvcnQlMjBjb25zdCUyMG1haW4lMjAlM0QlMjAnbWFpbiclMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSUyQyUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTdEJTJDJTdCJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNvbnN0JTIwc2hhcmVkJTIwJTNEJTIwJ3NoYXJlZCclNUNuJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTJDJTIybmFtZSUyMiUzQSUyMmZpbGUuanMlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyb3V0cHV0JTIyJTNBJTdCJTIyZXNNb2R1bGUlMjIlM0F0cnVlJTJDJTIyZXhwb3J0cyUyMiUzQSUyMm5hbWVkJTIyJTJDJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTdEJTJDJTIydHJlZXNoYWtlJTIyJTNBdHJ1ZSU3RCU3RA==)

```js
Promise.resolve().then(function () { return require('./file-Ck7dPsV5.js'); }).then((imported) => {
  assert.strictEqual(imported.shared, 'shared');
});
```

**Comment by hyf0** [comment]
Already tracked in https://github.com/rolldown/rolldown/issues/1842. It's not just cjs format.
