### ISSUE TITLE
How to support `define` options.

### ISSUE THREAD

**Issue by underfin** [rolldown/rolldown#186]
Because the vite use esbuild `define` option at optimizer, the rollup has `[@rollup/plugin-replace](https://github.com/rollup/plugins/tree/master/packages/replace#rollupplugin-replace)` to do it,  it using string match to replace, it is performance friendly but other ecosystem using last to do it, eg `swc/webpack`. 

I think we can use `@rollup/plugin-replace` to do it at milestone 1. It means we need to support some plugin API for the plugin, it is easy to implement.
But we need re-think it how to support it at rolldown for better performance and correct replace result.

**Comment by kazupon** [comment]
I am interested in this issue and making the plugin work.

we consider performance, I think the plugin should be implemented on the Rust side.
However, we would ideally like to keep it compatible with the existing rollup plugin.
Do you have in your team about a plugin plan, how to implemetation idea?

**Comment by shulaoda** [comment]
It seems that this feature has already been supported in PR #1882?

**Comment by hyf0** [comment]
Yeah. But we haven't exposed the options from nodejs. Will closed this issue once it's done.
