### ISSUE TITLE
[Bug]: Align `OutputOptions#esModule` with rollup

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#1888]
### Reproduction link or steps

Not needed.

### What is expected?

https://github.com/rollup/rollup/blob/df12edfea6e9c1a71bda1a01bed1ab787b7514d5/src/rollup/types.d.ts#L716

### What is actually happening?

https://github.com/rolldown/rolldown/blob/d19beb4e463e5ed502cc56ffcb196a5333a4c843/packages/rolldown/src/options/output-options.ts#L44-L49

### System Info

```Shell
Not needed.
```

**Comment by shulaoda** [comment]
Try it. 🙌

**Comment by 7086cmd** [comment]
Actually, in Rust, I used `Always` and `Never` for handling it, as NAPI-RS raises an error when transforming the JavaScript type to Rust when the type is `boolean | 'if-default-prop'`.

> During the conversion from JavaScript to Rust, the program encountered a panic when the source value was a boolean. Overriding true or false with a string was considered inelegant (IMO), so this approach was not used.

Passing the `true` or `false` is valid here, and tests are also included. If it's necessary to these 2 words from the JavaScript configuration side (actually we support passing `true` or `false`), remember the mapping **from `true` to `'always'`**, and **from `false` to `'never'`** in Rust :)

**Comment by hyf0** [comment]
Yeah. `rolldown` crate should keep using the current definition, which I think it is more proper. But js and binding crate should just pass values.

**Comment by 7086cmd** [comment]
That's great. @shulaoda you just need to edit the `bindingifyEsModule` function and some definitions and modify some tests on the JavaScript side.

**Comment by 7086cmd** [comment]
> Yeah. `rolldown` crate should keep using the current definition, which I think it is more proper. But js and *binding crate* should just pass values.

Implementing this idea may present challenges. My proposed approach involves only passing the `boolean` value from the configuration to the JavaScript side, where it will be transformed into the appropriate `never` and `always` from `true` or `false` value during the normalization step. While using a union type in Rust may be acceptable, I personally prefer to avoid it.

cc @hyf0.
