### ISSUE TITLE
Fix failed tests cases in #188

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#190]
https://github.com/rolldown-rs/rolldown/actions/runs/6783066064/job/18436561827?pr=188

- [x] Fix rollup@function@assignment-patterns: allows reassigments to default parameters that shadow imports
- [x] #197
- [x] Fix rollup@function@consistently-renames-destructured-parameters: destructured parameters are properly renamed
- [x] Fix rollup@function@switch-scope: uses correct scopes for switch statements

**Comment by joinmouse** [comment]
https://github.com/rolldown/rolldown/pull/621 Now, I test rollup@function@switch-scope is ok

**Comment by hyf0** [comment]
> #621 Now, I test rollup@function@switch-scope is ok

Thanks. Updated.
