### ISSUE TITLE
wasmHelperPlugin

### ISSUE THREAD

**Issue by IWANABETHATGUY** [rolldown/rolldown#1918]
https://github.com/rolldown/vite/blob/ededbc26533fc3ff7069e00ab8990ead9fd3cf64/packages/vite/src/node/plugins/wasm.ts#L50-L77

**Comment by ikkz** [comment]
I want to try it

**Comment by ikkz** [comment]
This plugin seems to have been implemented in #1368.

**Comment by ikkz** [comment]
Perhaps I can optimize it a bit, for example, by directly inlining it as a data URL when the wasm file is small enough.

**Comment by IWANABETHATGUY** [comment]
> Perhaps I can optimize it a bit, for example, by directly inlining it as a data URL when the wasm file is small enough.

We don't need to optimize for now, just try to port it as same as vite, which is easy to migrate.

**Comment by IWANABETHATGUY** [comment]
Sorry for my careless, you could continue `wasm-fallback` pulgin.
