### ISSUE TITLE
wasmFallbackPlugin

### ISSUE THREAD

**Issue by IWANABETHATGUY** [rolldown/rolldown#1919]
https://github.com/rolldown/vite/blob/ededbc26533fc3ff7069e00ab8990ead9fd3cf64/packages/vite/src/node/plugins/wasm.ts#L79-L96

**Comment by ikkz** [comment]
Maybe I can implement it in the same PR as #1918?

**Comment by IWANABETHATGUY** [comment]
Thanks in advance, but prefer splitting them into two pr.
