### ISSUE TITLE
[Feature Request]: Align `output.globals` with Rollup.

### ISSUE THREAD

**Issue by 7086cmd** [rolldown/rolldown#1925]
### What problem does this feature solve?

In Rollup, the `output.globals` option supports not only the HashMap (`{ [id: string]: string }` in TypeScript, `HashMap` in Rust) but also requires the function (`(id: string) => string`). While implementing this may be challenging, you can refer to the `external` option in the `input` option.

Perhaps we should consider adding a `contrib: hard` tag if this functionality is required.

### What does the proposed API look like?

For instance, if only external modules like `node:path` are present, transform all of these external modules into `path` within an IIFE.
```ts
export default defineConfig({
    external: (id: string) => "path",
})
```

**Comment by hyf0** [comment]
Closed by #2818.
