### ISSUE TITLE
[Bug]: same filenames are cause bundle error

### ISSUE THREAD

**Issue by Gehbt** [rolldown/rolldown#1944]
### Reproduction link or steps

with file directory and input: ["./index.js", "a/index.js"]

- index.js
- a
  └─index.js

[mini repro](https://github.com/Gehbt/rolldown-bug-repro1)

### What is expected?

use rollup:
![image](https://github.com/user-attachments/assets/d02ecd33-804f-4c07-97ed-5e93e468fccc)

### What is actually happening?

![image](https://github.com/user-attachments/assets/e1f0c881-227d-4af4-90e3-5bd42e7bc19f)

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 35.19 GB / 63.67 GB
  Binaries:
    Node: 20.12.2 - ~\AppData\Local\fnm_multishells\56692_1723391137579\node.EXE
    npm: 10.5.0 - ~\AppData\Local\fnm_multishells\56692_1723391137579\npm.CMD
    pnpm: 9.1.0 - ~\AppData\Local\fnm_multishells\56692_1723391137579\pnpm.CMD
    bun: 1.1.21 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (127.0.2651.74), ChromiumDev (128.0.2677.1)
    Internet Explorer: 11.0.22621.3527
```

**Comment by 7086cmd** [comment]
Related code:
https://github.com/rolldown/rolldown/blob/bc5cc201d86db863bd6acbd16c2327f0d4864830/crates/rolldown/src/stages/generate_stage/mod.rs#L315-L319

**Comment by IWANABETHATGUY** [comment]
simple patch: 
```diff
diff --git a/crates/rolldown/src/stages/generate_stage/mod.rs b/crates/rolldown/src/stages/generate_stage/mod.rs
index bab41c93..a734865e 100644
--- a/crates/rolldown/src/stages/generate_stage/mod.rs
+++ b/crates/rolldown/src/stages/generate_stage/mod.rs
@@ -190,21 +190,7 @@ impl<'a> GenerateStage<'a> {
 
       let chunk_name_info = &mut index_pre_generated_names[chunk_id];
 
-      let chunk_name = if chunk_name_info.explicit {
-        if used_names.contains(&chunk_name_info.name) {
-          return Err(anyhow::anyhow!("Chunk name `{}` is already used", chunk_name_info.name));
-        }
-        chunk_name_info.name.clone()
-      } else {
-        let mut chunk_name = chunk_name_info.name.clone();
-        let mut next_count = 1;
-        // TODO: use `FxHashMap<ArcStr, u32>` to find conflict-less name in one go.
-        while used_names.contains(&chunk_name) {
-          chunk_name = ArcStr::from(format!("{chunk_name}~{next_count}"));
-          next_count += 1;
-        }
-        chunk_name
-      };
+      let chunk_name = { chunk_name_info.name.clone() };
 
       used_names.insert(chunk_name.clone());
 
```

**Comment by hyf0** [comment]
The unexpected thing here is that ` chunk_name_info.explicit` should be false since users didn't provide names explicitly. This might cause by js side, where we shouldn't do normalization for unset name.

In the meantime, as a workaround, you could provide name explicitly.

**Comment by IWANABETHATGUY** [comment]
> The unexpected thing here is that ` chunk_name_info.explicit` should be false since users didn't provide names explicitly. This might cause by js side, where we shouldn't do normalization for unset name.
> 
> In the meantime, as a workaround, you could provide name explicitly.

Even set `explicit` to false, our chunk name is still different from `rollup`

**Comment by IWANABETHATGUY** [comment]
Looks like `rollup` did not do chunk name deconflict.

**Comment by nilptr** [comment]
I guess the explicit chunk name is caused by this.

https://github.com/rolldown/rolldown/blob/eb78b810304852baf5bcaf816c81414fc5542661/packages/rolldown/src/options/bindingify-input-options.ts#L147-L153

**Comment by shulaoda** [comment]
Try it. 🙌
