### ISSUE TITLE
replace `citty` with builtin `node:parseArgs` to parse command line args.

### ISSUE THREAD

**Issue by IWANABETHATGUY** [rolldown/rolldown#1954]
### What problem does this feature solve?

`citty` is not actively maintained, and since our lowerest node js requirement is `>= 18.20.3` we could use `node:parseArgs` to parse command line args.

related to https://github.com/rolldown/rolldown/issues/1852
### What does the proposed API look like?

same as before.

**Comment by ikkz** [comment]
I want to try it

**Comment by IWANABETHATGUY** [comment]
Thanks in advance, but It would great to finish https://github.com/rolldown/rolldown/issues/1919 this ASAP, since #1919 have higher priority, if you don't have enough time, then I could take #1919, and you continue this issue.

**Comment by ikkz** [comment]
> Thanks in advance, but It would great to finish #1919 this ASAP, since #1919 have higher priority, if you don't have enough time, then I could take #1919, and you continue this issue.

I have written a draft for #1919 and plan to open a PR today.

**Comment by IWANABETHATGUY** [comment]
> > Thanks in advance, but It would great to finish #1919 this ASAP, since #1919 have higher priority, if you don't have enough time, then I could take #1919, and you continue this issue.
> 
> I have written a draft for #1919 and plan to open a PR today.

that's great

**Comment by 7086cmd** [comment]
Hello @ikkz. To complete the task, you just need to remove the `citty` parameter and modify the rolldown on the track using parseArgs. I will take care of the -c and -h parameters more efficiently with other arguments :)

**Comment by ikkz** [comment]
> Hello @ikkz. To complete the task, you just need to remove the `citty` parameter and modify the rolldown on the track using parseArgs. I will take care of the -c and -h parameters more efficiently with other arguments :)

@7086cmd Thank you for your guidance. I'll open a draft PR tomorrow
