### ISSUE TITLE
[rolldown/cli] Auto-Generate CLI Args from Options Schema

### ISSUE THREAD

**Issue by IWANABETHATGUY** [rolldown/rolldown#1955]
### What problem does this feature solve?

Looking to enhance the CLI by auto-generating command line arguments based on the options schema.
## Desc 
- Automatically generate CLI args from schema options (booleans, strings, arrays of strings).This would make the CLI more flexible, reducing the need for a config file and aligning args directly with schema types.

### What does the proposed API look like?

n/a

**Comment by 7086cmd** [comment]
I intend to implement the schema generation process using TypeScript instead of Rust, as the CLI is currently written in TypeScript.

**Comment by IWANABETHATGUY** [comment]
> I am going to try this. Planning to generate the schema according to the zod instead of Rust side, as the CLI is implemented in TypeScript.

that sounds cool

**Comment by IWANABETHATGUY** [comment]
better do it after #1954

**Comment by 7086cmd** [comment]
I am implementing it in accordance with the API standard specified in the documentation for [`node:parseArgs`](https://nodejs.org/api/util.html#utilparseargsconfig).
