### ISSUE TITLE
Whether to update node version

### ISSUE THREAD

**Issue by 7086cmd** [rolldown/rolldown#1982]
The issue appears to be related to the usage of the `nodejs 22.6.0`-featured API, specifically the `allowNegative` option. This option is crucial, and I am contemplating whether we should modify the `node-version`.

_Originally posted by @7086cmd in https://github.com/rolldown/rolldown/issues/1977#issuecomment-2288509208_

**Comment by ikkz** [comment]
There was a related issue(#1378) previously, directly upgrading to version 22 seems not to be a good solution to solve it.
For the "allowNegative" option, always setting it to false and then implementing this feature through `tokens` might be a viable solution?
