### ISSUE TITLE
[Feature Request]: Support `banner`, `footer`, `intro` and `outro` for composejs plugin

### ISSUE THREAD

**Issue by IWANABETHATGUY** [rolldown/rolldown#1999]
### What problem does this feature solve?

Making `banner`, `footer`, `intro` and `outro` composable for compose js plugin
for now, these hook will bailout https://github.com/rolldown/rolldown/blob/1b49ed1102469e42283b38fa115cfb215bf25629/packages/rolldown/src/utils/compose-js-plugins.ts#L10-L28
### What does the proposed API look like?

n/a

**Comment by ikkz** [comment]
I want to try it ❤️

**Comment by IWANABETHATGUY** [comment]
Thanks in advance.

**Comment by IWANABETHATGUY** [comment]
There is a stale branch you could refer https://github.com/rolldown/rolldown/tree/feat/compose-js-impl, but you could start on your own.

**Comment by ikkz** [comment]
> There is a stale branch you could refer https://github.com/rolldown/rolldown/tree/feat/compose-js-impl, but you could start on your own.

Thanks, this is very helpful to me
