### ISSUE TITLE
Use `autofix.ci` to fix code issues.

### ISSUE THREAD

**Issue by 7086cmd** [rolldown/rolldown#2003]
### What problem does this feature solve?

I observed the usage of the `autofix.ci` command in `slidev`, which enables automatic resolution of certain easily fixable issues, such as formatting problems. By utilizing the `just fix` command, open-source projects can freely access the `autofix.ci` command to promptly address these issues without the need to repeatedly employ the `just fmt` command in pull requests.

### What does the proposed API look like?

Only requires configuration of a CI pipeline.

**Comment by shulaoda** [comment]
I can try to complete this, but it requires installing Github App [autofix.ci](https://github.com/apps/autofix-ci/installations/select_target) first. @IWANABETHATGUY

**Comment by IWANABETHATGUY** [comment]
> I can try to complete this, but it requires installing Github App [autofix.ci](https://github.com/apps/autofix-ci/installations/select_target) first. @IWANABETHATGUY

Thanks in advance.

**Comment by IWANABETHATGUY** [comment]
autofix.ci is installed.
