### ISSUE TITLE
[Feature Request]: watch mode

### ISSUE THREAD

**Issue by benmccann** [rolldown/rolldown#2028]
### What problem does this feature solve?

Rebuild the bundle when its source files change on disk, so that the build doesn't need to be manually re-executed

### What does the proposed API look like?

https://rollupjs.org/command-line-interface/#w-watch

A `-w`/`--watch` CLI flag can be used

[`this.meta.watchMode`](https://rollupjs.org/plugin-development/#this-meta) can be passed to plugins to let them know we're in watch mode

**Comment by 7086cmd** [comment]
cc @hyf0, I am also curious about the optimal placement of the watcher, Rust side or JavaScript side.

**Comment by hyf0** [comment]
rebuild is not supported yet. So no plan on `watch` support. It will add unnecessary complexity for nothing. We will consider adding this feature when we supporting incremental rebuild.

**Comment by benmccann** [comment]
Thanks for the update!

For what it's worth, I'd be happy with doing a complete rebuild on watch especially since rolldown is so fast! Our build has gone from ~8 seconds with rollup to ~1s with rolldown. And I think most of that is just the startup time of parsing the build config, etc. because once it starts printing to the screen it completes very quickly and says "Finished in 44.59 ms", so presumably that's the time that it would take to do a complete rebuild in watch mode

**Comment by hyf0** [comment]
Thanks for the feedback. We gonna have a watch mode that does full rebuild soon.

**Comment by IWANABETHATGUY** [comment]
@underfin could https://github.com/rolldown/rolldown/pull/2396 closed this issue?

**Comment by underfin** [comment]
Yeah. It already implement it.
