### ISSUE TITLE
[Feature Request]: Why not use `husky` for `pre-commit` interception?

### ISSUE THREAD

**Issue by shulaoda** [rolldown/rolldown#2104]
### What problem does this feature solve?

IMO, we can actually format or lint during the `git commit` stage, rather than heavily relying on the `CI/CD` pipeline. This way, we can avoid some unnecessary errors before the code is even committed.

**Comment by shulaoda** [comment]
Related to #2103

**Comment by IWANABETHATGUY** [comment]
Because husky could be bypassed, https://git-scm.com/book/fa/v2/Customizing-Git-Git-Hooks#:~:text=although%20you%20can%20bypass%20it%20with%20git%20commit%20%2D%2Dno%2Dverify

**Comment by shulaoda** [comment]
> https://git-scm.com/book/fa/v2/Customizing-Git-Git-Hooks#:~:text=although%20you%20can%20bypass%20it%20with%20git%20commit%20%2D%2Dno%2Dverify

Yes, it can indeed be bypassed. However, in most cases, can we use `husky` to avoid some unnecessary mistakes? For example, forgetting to `format` or `lint` before committing.

**Comment by IWANABETHATGUY** [comment]
some rules of cargo clippy needs cross module information so you can't fine-grained control how many files needs to verify like `prettier`, but I am open to using `husky` and lint-stage for node validation
