### ISSUE TITLE
Convert `stale` labeled PR to draft

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#2130]
There is a attempt on https://github.com/rolldown/rolldown/pull/2127 but it seems not work 
 while test in https://github.com/rolldown/rolldown/pull/2128.

<img width="1025" alt="image" src="https://github.com/user-attachments/assets/2be962a5-e360-4b68-bccd-4122bf2ab619">

**Comment by hikomoon** [comment]
can I try this ?
