### ISSUE TITLE
[Feature Request]: Use `autofix.ci` to update snapshots.

### ISSUE THREAD

**Issue by 7086cmd** [rolldown/rolldown#2190]
### What problem does this feature solve?

Whenever we add more options, we may occasionally express our dissatisfaction with the CLI helper test.

### What does the proposed API look like?

The CLI helper message snapshot should be automatically accepted.

**Comment by hyf0** [comment]
I personally feel it's not big deal and expected to let you know that adding options will affects the cli.

But if we want to go further, we could have a label `autofix.update-snapshot-node` to trigger `just test-node --update` using `autofix.ci`.

**Comment by 7086cmd** [comment]
I agree with using `autofix.ci`, it conbines the prompt of affecting CLI, but also needless for extra manual commit.
