### ISSUE TITLE
[Bug]: `[hash:6]` in `entryFileNames` does not get replaced with hash

### ISSUE THREAD

**Issue by sapphi-red** [rolldown/rolldown#2206]
### Reproduction link or steps

1. Open https://stackblitz.com/edit/github-6jajke-nva34g?file=rolldown.config.mjs
2. `npm run build` runs automatically
3. see `dist/entry-[hash:6].js` is generated
4. run `npm run build:up` to run rollup
5. see `dist/entry-q8VKMz.js` is generated

### What is expected?

`dist/entry-hash.js` (`hash` part can be any 6-character long hash) is generated

### What is actually happening?

`dist/entry-[hash:6].js` is generated (`[hash:6]` is not replaced with the real hash)

### System Info

```Shell
Stackblitz

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    rolldown: https://pkg.pr.new/rolldown@d6233d8 => 0.13.2
```

### Any additional comments?

This is not something urgent.

**Comment by underfin** [comment]
The related code is [here](https://github.com/rolldown/rolldown/blob/main/crates/rolldown_common/src/inner_bundler_options/types/filename_template.rs#L35)
