### ISSUE TITLE
[Bug]: `output.sourcemap: hidden` does output sourcemap

### ISSUE THREAD

**Issue by sapphi-red** [rolldown/rolldown#2208]
### Reproduction link or steps

1. Open https://stackblitz.com/edit/github-6jajke-zdkn4v?file=rolldown.config.mjs
2. `npm run build` runs automatically
3. see no sourcemap is output in `dist`
4. delete dist directory
5. run `npm run build:up` to run rollup
6. see `dist/entry.js.map` is output and `dist/entry.js` does not contain any source map comment

### What is expected?

source map to be output

### What is actually happening?

source map is not output

### System Info

```Shell
Stackblitz

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    rolldown: https://pkg.pr.new/rolldown@d6233d8 => 0.13.2
```

**Comment by 7086cmd** [comment]
> If true, a separate sourcemap file will be created. If "inline", the sourcemap will be appended to the resulting output file as a data URI. "hidden" works like true except that the corresponding sourcemap comments in the bundled files are suppressed.

From https://rollupjs.org/configuration-options/#output-sourcemap.
