### ISSUE TITLE
[Feature Request]: Output File Name Flag

### ISSUE THREAD

**Issue by trymeouteh** [rolldown/rolldown#2224]
### What problem does this feature solve?

Unable to choose the name of the build file. You are able to choose the output directory, but not the file name itself.

```
rolldown make.js -d dist -f iife -n mathPackage
```

The above command will then generate a build file in `/dist/make.js`

### What does the proposed API look like?

Another flag to output the file name 

```
rolldown make.js -d dist -o math-package.js -f iife -n mathPackage
```

The above command will then generate a build file in `/dist/math-package.js`

**Comment by 7086cmd** [comment]
We haven't support `output.file` option, so this is not supported at the time being.

And the `-n` is only used for the name of iife wrapper, not the output file name.

**Comment by trymeouteh** [comment]
I would like to suggest changing the `-d` directory flag to `-o` output flag to have only one flag to choose where the file output directory and name. `-o dist/math.js`

**Comment by 7086cmd** [comment]
Yes, we will use `-o` flag aligning with Rollup once `output.file` is supported.
