### ISSUE TITLE
[Bug]: Sourcemap flag -s "Invalid value for option: sourcemap"

### ISSUE THREAD

**Issue by trymeouteh** [rolldown/rolldown#2225]
### Reproduction link or steps

```
rolldown make.js -d dist -f iife -n mathPackage -s
```

### What is expected?

A new build file `/dist/make.js` and sourcemap file `/dist/make.js.map`

### What is actually happening?

The following error in the terminal and no files are generated.

```
> rolldown make.js -d dist -f iife -n mathPackage -s

ERROR  Invalid value for option: sourcemap. Invalid input. You can use rolldown -h to see the help. 
```

### System Info

```Shell
Linux Mint
Node 20.17.0
```

### Any additional comments?

When using `-s inline` it does produce a build with no errors and the sourcemaps are inside the build file.

**Comment by 7086cmd** [comment]
The `-n` is not supported yet, please try again after removing `-n mathPackage`.
