### ISSUE TITLE
[Bug]: build fails if `!~{000}` exists

### ISSUE THREAD

**Issue by sapphi-red** [rolldown/rolldown#2257]
### Reproduction link or steps

1. Open https://stackblitz.com/edit/github-6jajke-vryfxq?file=src%2Fentry.js,rolldown.config.mjs
2. `npm run build` runs automatically
3. panics at this line https://github.com/rolldown/rolldown/blob/d2fc33a07f8733eecca484df98f3bc0c1cdb2461/crates/rolldown/src/utils/hash_placeholder.rs#L72

### What is expected?

A warning is output

### What is actually happening?

A panic happens

### System Info

```Shell
Stackblitz

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    rolldown: https://pkg.pr.new/rolldown@dab103f => 0.13.2
```

### Any additional comments?

This is not something urgent.

**Comment by shulaoda** [comment]
This issue is likely due to the `hash` replacement occurring within the `content`.
