### ISSUE TITLE
[Bug]: importMetaGlobPlugin does not support `./**.js`

### ISSUE THREAD

**Issue by sapphi-red** [rolldown/rolldown#2298]
### Reproduction link or steps

1. Open https://stackblitz.com/edit/github-6jajke-ntifpy?file=package.json,rolldown.config.mjs,src%2Fentry.js
1. `npm run build` runs automatically.
1. An error happens

### What is expected?

No error happens and works like `./dir/**/*.js`.

### What is actually happening?

The following error happens:

> called `Result::unwrap()` on an `Err` value: PatternError { pos: 44, msg: "recursive wildcards must form a single path component" }

### System Info

```Shell
Stackblitz

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    rolldown: https://pkg.pr.new/rolldown@351d2c7 => 0.13.2
```

### Any additional comments?

Faced this while trying rolldown with Vite.

**Comment by IWANABETHATGUY** [comment]
IIRC this is not a valid glob syntax? maybe we should add some hack

**Comment by sapphi-red** [comment]
I guess there's no spec about glob syntax, so nothing is valid or invalid unless the implementation is specified. It is supported by the two popular glob library in JS (`minimatch` and `picomatch`).
https://stackblitz.com/edit/node-hsydk6?file=index.js

Although, it works like `./dir/*.js` instead of `./dir/**/*.js` which I was expecting. Probably better to output a warning even if we support it...
I'm going to fix Vite's code not to rely on this behavior as it feels it's relying on a implementation detail.

**Comment by IWANABETHATGUY** [comment]
support this is fine, I could do it in rolldown plugin side
