### ISSUE TITLE
[Bug]: importMetaGlobPlugin does not work in simple cases

### ISSUE THREAD

**Issue by sapphi-red** [rolldown/rolldown#2299]
### Reproduction link or steps

1. Open https://stackblitz.com/edit/github-6jajke-mebhpz?file=rolldown.config.mjs,src%2Fentry.js
1. `npm run build` runs automatically.
1. The output does not contain code from `src/dir/a.js`.

### What is expected?

The output contain code from `src/dir/a.js`.

### What is actually happening?

The output does not contain code from `src/dir/a.js` and `import.meta.glob` is replaced with an empty object.

### System Info

```Shell
Stackblitz

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    rolldown: https://pkg.pr.new/rolldown@351d2c7 => 0.13.2
```

### Any additional comments?

Faced this while trying rolldown with Vite.

**Comment by shulaoda** [comment]
It seems necessary to start with `./src`.

https://github.com/rolldown/rolldown/blob/50fa28433a4cf72d5f112499246ea4d0e37cbe83/crates/rolldown_plugin_import_glob/src/lib.rs#L225-L236
