### ISSUE TITLE
[Bug]: does not support importing TS files with `.js` extension even if `"module": "NodeNext"` is set in tsconfig.json

### ISSUE THREAD

**Issue by sapphi-red** [rolldown/rolldown#2304]
### Reproduction link or steps

1. Open https://stackblitz.com/edit/github-6jajke-59ne76?file=src%2Fentry.ts
1. `npm run build` runs automatically.
1. `./foo.js` gets externalized automatically.

### What is expected?

No error happens and `./foo.js` resolve to `./foo.ts`.

### What is actually happening?

`./foo.js` gets externalized automatically and a warning is output.

### System Info

```Shell
Stackblitz

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    rolldown: https://pkg.pr.new/rolldown@351d2c7 => 0.13.2
```

### Any additional comments?

This happens with other related extensions (`.mjs` -> `.mts`, `.cjs` -> `.cts`, `.jsx` -> `.tsx`).

Faced this while trying rolldown with Vite.

**Comment by underfin** [comment]
@Boshen It is the I-meet problem, it is a ts compiler behavior, Could you think it should be supported at oxc-resolver? The `enhanced-resolve` does not support it.

**Comment by Boshen** [comment]
You need to setup `extensionAlias` in order for this to work. I'm not sure whether this should be user land configuration or provided as a default in Rolldown.

**Comment by hyf0** [comment]
Some notes:
- Currently, users used `target: "node-next"` should manually config extensionAlias on its own.

For the future:

- However, `oxc-resolver` now takes `tsconfig` as input. Wether oxc-resolve should config `extensionAlias` automatically based on `target` field should be considered by @Boshen.
- Rolldown might also need to consider whether to accept/support `tsconfig` as the first-class citizen. If so, rolldown need to change it's behavior based on the `tsconfig` input. Such config `extensionAlias` if `target: node-next` is set.

**Comment by Boshen** [comment]
>  Wether oxc-resolve should config extensionAlias automatically based on target field should be considered b

The resolver is unopinionated on how to deal with extensions, the tool makes the decision.

This is also why there is many module resolution options in tsc  https://www.typescriptlang.org/tsconfig/#moduleResolution

**Comment by sapphi-red** [comment]
> * Currently, users used `target: "node-next"` should manually config `extensionAlias` on its own.

Currently `extensionAlias` is not exposed, so we need that to be exposed.

**Comment by hyf0** [comment]
With above context, I think configuring `extensionAlias` manually should be the practice for now. I have created https://github.com/rolldown/rolldown/issues/2327 to expose the option.

As for the future, we need more investigation on this.

Some related questions:

- How vite now handle this?
- How esbuild handle this?

**Comment by sapphi-red** [comment]
> - How vite now handle this?

Vite only resolves `.js` -> `.ts` if the import statement is written in TS files (and TS section of Vue). (related PR: https://github.com/vitejs/vite/pull/5510)
https://github.com/vitejs/vite/blob/d7763a5615a238cb1b5dceb7bdfc4aac7678fb0a/packages/vite/src/node/plugins/resolve.ts#L645-L697
This differs from the TS's behavior as mentioned in https://github.com/vitejs/vite/issues/8993.

> - How esbuild handle this?

esbuild unconditionally applies this behavior. It applies even if `tsconfig.json` does not exist or `tsconfig.json` has `"module": "node"`.
https://github.com/evanw/esbuild/blob/d34e79e2a998c21bb71d57b92b0017ca11756912/internal/resolver/resolver.go#L1795-L1807
[reproduction with `"module": "node"`](https://esbuild.github.io/try/#YgAwLjI0LjAALS1idW5kbGUAZQBlbnRyeS5qcwBpbXBvcnQgJy4vZmlsZS5qcycKCmNvbnNvbGUubG9nKCdlbnRyeScpAABmaWxlLnRzAGNvbnNvbGUubG9nKCdmaWxlJykAAHRzY29uZmlnLmpzb24AewogICJjb21waWxlck9wdGlvbnMiOiB7CiAgICAibW9kdWxlIjogIk5vZGUiCiAgfQp9), [reproduction without tsconfig.json](https://esbuild.github.io/try/#YgAwLjI0LjAALS1idW5kbGUAZQBlbnRyeS5qcwBpbXBvcnQgJy4vZmlsZS5qcycKCmNvbnNvbGUubG9nKCdlbnRyeScpAABmaWxlLnRzAGNvbnNvbGUubG9nKCdmaWxlJyk)

**Comment by sapphi-red** [comment]
Although I don't think this behavior is that important anymore since the [`allowImportingTsExtensions` option](https://www.typescriptlang.org/ja/tsconfig/#allowImportingTsExtensions) has landed.

**Comment by hyf0** [comment]
#3078 ports esbuild's behavior.
