### ISSUE TITLE
[Bug]: `css` can not be specified for `moduleTypes`

### ISSUE THREAD

**Issue by sapphi-red** [rolldown/rolldown#2329]
### Reproduction link or steps

https://stackblitz.com/edit/github-6jajke-scawe9?file=rolldown.config.mjs

```js
import { defineConfig } from 'rolldown';

export default defineConfig({
  input: ['./src/entry.js'],
  output: {
    dir: 'dist',
  },
  moduleTypes: {
    '.sass': 'css',
  },
});
```

### What is expected?

`css` can be specified for `moduleTypes`.

### What is actually happening?

`Unknown module type: css` error happens.

### System Info

```Shell
Stackblitz

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    rolldown: https://pkg.pr.new/rolldown@3899128 => 0.13.2
```

### Any additional comments?

Maybe it's because css support is kind a experimental.

**Comment by burhanuday** [comment]
Hi @hyf0 
I see that you raised a PR https://github.com/rolldown/rolldown/pull/2247 to support this
But i think the input schema isn't updated here - https://github.com/rolldown/rolldown/blob/main/packages/rolldown/src/options/input-options.ts#L29
Is it enough to add it to the zod schema to close this issue?
I can pick it up if that is the case

**Comment by hyf0** [comment]
> Hi @hyf0 I see that you raised a PR #2247 to support this But i think the input schema isn't updated here - https://github.com/rolldown/rolldown/blob/main/packages/rolldown/src/options/input-options.ts#L29 Is it enough to add it to the zod schema to close this issue? I can pick it up if that is the case

Sure. Thank you in advanced.

**Comment by hyf0** [comment]
Closed by https://github.com/rolldown/rolldown/pull/2464.
