### ISSUE TITLE
[Bug]: `advancedChunks.groups[*].test` expects a string instead of a RegExp

### ISSUE THREAD

**Issue by sapphi-red** [rolldown/rolldown#2391]
### Reproduction link or steps

https://github.com/rolldown/rolldown/blob/7bc51f099a916dbe31bc0582995c58cf0d0f8924/packages/rolldown/src/options/output-options.ts#L93
https://github.com/rolldown/rolldown/blob/7bc51f099a916dbe31bc0582995c58cf0d0f8924/crates/rolldown_binding/src/utils/normalize_binding_options.rs#L193-L195

### What is expected?

Allow passing a RegExp and disallow passing a string.
```ts
advancedChunks: {
  groups: [
    {
      name: 'chunk',
      test: /chunk.css/,
    },
  ],
},
```
This is more intuitive.
I think it can allow strings if it works like `id.includes(group.test)` instead of `new RegExp(group.test).test(id)`.

### What is actually happening?

This is disallowed
```ts
advancedChunks: {
  groups: [
    {
      name: 'chunk',
      test: /chunk.css/,
    },
  ],
},
```
and this is allowed.
```ts
advancedChunks: {
  groups: [
    {
      name: 'chunk',
      test: 'chunk.css',
    },
  ],
},
```

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 17.20 GB / 31.92 GB
  Binaries:
    Node: 20.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.12.0 - C:\Program Files\nodejs\pnpm.CMD
    bun: 1.1.29 - ~\AppData\Local\Microsoft\WinGet\Links\bun.EXE
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    rolldown: https://pkg.pr.new/rolldown@9a0db67 => 0.13.2
```

**Comment by shulaoda** [comment]
This might be a workaround since `zod` doesn't support `z.regex()`. 🤔
