### ISSUE TITLE
[Bug]: `this.getModuleInfo(id)` returns `null` in `load` hook

### ISSUE THREAD

**Issue by sapphi-red** [rolldown/rolldown#2392]
### Reproduction link or steps

1. https://stackblitz.com/edit/github-6jajke-xxwzrl?file=rolldown.config.mjs
2. `npm run build` runs automatically
3. see `/home/projects/github-6jajke-xxwzrl/src/entry.js false undefined` output in the terminal
4. run `npm run build:up` to run rollup
5. see `/home/projects/github-6jajke-xxwzrl/src/entry.js true true` output in the terminal

### What is expected?

`this.getModuleInfo(id)` returns the module info

### What is actually happening?

 `this.getModuleInfo(id)` returns `null`

### System Info

```Shell
Stackblitz

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    rolldown: https://pkg.pr.new/rolldown@2e3e2ed => 0.13.2
```

**Comment by underfin** [comment]
It is diffcult at now, because the module created after `resolveid/load/transform` hook, so it is null at the hooks.
