### ISSUE TITLE
[Bug]: Rolldown treats modules as CJS when the module is empty/unknown-format and `resolveId` did not set the ModuleFormat

### ISSUE THREAD

**Issue by sapphi-red** [rolldown/rolldown#2394]
### Reproduction link or steps

1. Open https://stackblitz.com/edit/github-6jajke-8u4btw?file=rolldown.config.mjs,src%2Fentry.js
2. `npm run build` runs automatically
3. see the output containing `rolldown:runtime`
4. run `npm run build:up` to run rollup
5. see the output not containing any CJS conversion code

### What is expected?

`node dist/entry.js` outputs `undefined`.

### What is actually happening?

`node dist/entry.js` outputs `{}`.

### System Info

```Shell
Stackblitz

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    rolldown: https://pkg.pr.new/rolldown@7bc51f0 => 0.13.2
```

### Any additional comments?

Faced this while trying rolldown with Vite.

This behavior does make sense in terms of compat with other tools. But if we want to make it more compatible with rollup, the default ModuleFormat to be ESM. I think there's a tradeoff in both ways. This can be worked around on Vite side by adding `export {}`.

**Comment by underfin** [comment]
The esbuild also treats modules as CJS when the module is empty, the rolldown following it.

**Comment by hyf0** [comment]
Yeah. We just follow esbuild's behavior.

> This can be worked around on Vite side by adding export {}.

We could discuss about how we could make this behavior work well with vite in this issue instead of doing workaround.

**Comment by hyf0** [comment]
Let's try make empty module esm first and see what happens.

**Comment by hyf0** [comment]
Affected case: 

<img width="635" alt="image" src="https://github.com/user-attachments/assets/8dcb0955-79e1-4fe5-a38e-c0bfa6de3262">

Some users use this kind of pattern to delay error to runtime.

If we treat unknown-format module to esm by default, it would break this usage and needs to change it to the below code

<img width="671" alt="image" src="https://github.com/user-attachments/assets/8c49cc36-25de-46db-9158-776fc8aeeffd">

**Comment by underfin** [comment]
The rollup has a interesting test at https://github.com/rollup/rollup/blob/master/test/function/samples/namespace-member-side-effects/assignment/main.js#L9. The namespace behavior is different at here.
