### ISSUE TITLE
[Feature Request]: Support `.ts` extension for configuration file.

### ISSUE THREAD

**Issue by izaakschroeder** [rolldown/rolldown#2400]
### What problem does this feature solve?

For runtimes that support loading `.ts` files directly (e.g. `bun` and [in the future node](https://github.com/nodejs/loaders/issues/208)) it allows the pleasant addition of type-safe configuration files. 

### What does the proposed API look like?

```patch
diff --git a/dist/cjs/cli.cjs b/dist/cjs/cli.cjs
index eb3926fb44d29f034d157e63463d8dd0e5c7e7b6..068ae5717724ff4ab6fb489ae54bc798be3c7fa7 100644
--- a/dist/cjs/cli.cjs
+++ b/dist/cjs/cli.cjs
@@ -31,7 +31,7 @@ async function ensureConfig(configPath) {
 	const configExports = await import(fileUrl);
 	return configExports.default;
 }
-const SUPPORTED_CONFIG_FORMATS = [".js", ".mjs", ".cjs"];
+const SUPPORTED_CONFIG_FORMATS = [".js", ".mjs", ".cjs", ".ts"];
 function isSupportedFormat(configPath) {
 	const ext = nodePath.extname(configPath);
 	return SUPPORTED_CONFIG_FORMATS.includes(ext);
diff --git a/dist/esm/cli.mjs b/dist/esm/cli.mjs
index ceeaa986eb3bb5452b78a206099d9005c43bc3f0..b84b25694cf49c2eb2ff9b7d167fc0ae367051be 100644
--- a/dist/esm/cli.mjs
+++ b/dist/esm/cli.mjs
@@ -30,7 +30,7 @@ async function ensureConfig(configPath) {
 	const configExports = await import(fileUrl);
 	return configExports.default;
 }
-const SUPPORTED_CONFIG_FORMATS = [".js", ".mjs", ".cjs"];
+const SUPPORTED_CONFIG_FORMATS = [".js", ".mjs", ".cjs", ".ts"];
 function isSupportedFormat(configPath) {
 	const ext = nodePath.extname(configPath);
 	return SUPPORTED_CONFIG_FORMATS.includes(ext);

```

**Comment by birkskyum** [comment]
@izaakschroeder , with node this is actually also possible today with rollup, using the --configPlugin @rollup/plugin-typescript :

`"build-dev": "rollup --configPlugin @rollup/plugin-typescript -c --environment BUILD:dev"`

**Comment by hi-ogawa** [comment]
I think it makes sense to lift this restriction if config loading is left to runtime's `import`.

For example, it's already possible to workaround this by using `tsx` since it can resolve `rolldown.config.js` to `rolldown.config.ts` https://stackblitz.com/edit/github-u1dtrk?file=package.json

```sh
NODE_OPTIONS='--import tsx/esm' rolldown -c
```

With `--experimental-strip-types`, it doesn't allow `js -> ts` resolution, but re-exporting from ts file works:

```ts
// command: NODE_OPTIONS='--experimental-strip-types' rolldown -c

// rolldown.config.js
export { default } from "./rolldown.config.ts";

// rolldown.config.ts
export default ....
```

**Comment by underfin** [comment]
close https://github.com/rolldown/rolldown/pull/3134
