### ISSUE TITLE
[Bug]: Cannot call write twice in parallel

### ISSUE THREAD

**Issue by sxzz** [rolldown/rolldown#2518]
### Reproduction link or steps

https://github.com/sxzz/rolldown-rebuild-issue

```js
import { rolldown } from 'rolldown'

const bundle = await rolldown({
  input: ['./input.js'],
})
await write()
// Execute twice
await write()

async function write() {
  await Promise.all([
    bundle.write({ format: 'esm', dir: './dist' }),
    bundle.write({ format: 'cjs', dir: './dist', entryFileNames: 'input.cjs' }),
  ])
}
```

### What is expected?

No errors.

### What is actually happening?

```
node:internal/modules/run_main:129
    triggerUncaughtException(
    ^

[Error: Failed to lock the bundler. Is another operation in progress?] {
  code: 'GenericFailure'
}
```

### System Info

```Shell
N/A
```

### Any additional comments?

prev https://github.com/rolldown/rolldown/issues/2213, but call `write` API in parallel

**Comment by IWANABETHATGUY** [comment]
https://github.com/rolldown/rolldown/blob/5fc923df94ca54c1fff35c5bc26d179813a9305d/crates/rolldown_binding/src/bundler.rs#L131-L131 from here,

**Comment by IWANABETHATGUY** [comment]
@underfin any reason use try lock rather than `lock`  ?
