### ISSUE TITLE
`esbuild` will auto convert `format` to `cjs` if you don't specify `format` when `platform` is `node`

### ISSUE THREAD

**Issue by IWANABETHATGUY** [rolldown/rolldown#2526]
`esbuild` will auto convert `format` to `cjs` if you don't specify `format` when `platform` is `node`

_Originally posted by @IWANABETHATGUY in https://github.com/rolldown/rolldown/pull/2525#discussion_r1822589001_

**Comment by hyf0** [comment]
Interesting behavior. I prefer not to follow this one with esbuild. However, let's bring this up in the weekly meeting.

**Comment by IWANABETHATGUY** [comment]
the related code: https://github.com/evanw/esbuild/blob/d34e79e2a998c21bb71d57b92b0017ca11756912/pkg/api/api_impl.go#L1376-L1386

**Comment by hyf0** [comment]
After the discussion, the conclusion would be default tot `esm` always, which is the current behavior.
