### ISSUE TITLE
[Feature Request]: Refactor `InputOptions` and `OutputOptions` with `satisfies` keyword

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#2568]
### What problem does this feature solve?

This is a preparation for improving dx of writing options using jsdoc.

### What does the proposed API look like?

See details at https://github.com/web-infra-dev/rspack/issues/4241#issuecomment-2376478969.

**Comment by shulaoda** [comment]
I‘m free to try it. 👀
