### ISSUE TITLE
[Bug]: crashes when the input code assigns to a namespace object

### ISSUE THREAD

**Issue by sapphi-red** [rolldown/rolldown#2607]
### Reproduction link or steps

1. Open https://stackblitz.com/edit/github-xv4yss-53rtbd?file=src%2Fentry.js,src%2Fdep.js
2. `npm i` runs automatically
3. `npm run build` runs automatically and crashes with `canonical name not found for SymbolRef { owner: 2, symbol: SymbolId(2) }, original_name: "dep_exports"`

### What is expected?

No crash happens and the build completes successfully.

### What is actually happening?

A crash happens: `canonical name not found for SymbolRef { owner: 2, symbol: SymbolId(2) }, original_name: "dep_exports"`.

### System Info

```Shell
Stackblitz

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    rolldown: https://pkg.pr.new/rolldown@829d80a => 0.13.2
```

### Any additional comments?

This is not something urgent. I just found this while checking whether rolldown freezes the namespace object or not as [`output.freeze`](https://rollupjs.org/configuration-options/#output-freeze) was not supported.

**Comment by IWANABETHATGUY** [comment]
https://hyrious.me/esbuild-repl/?version=0.23.0&b=e%00entry.js%00import+*+as+dep+from+%27.%2Fdep.js%27%3B%0A%0Adep.bar+%3D+%27bar%27%3B&b=%00dep.js%00const+a%3D+10%3B&o=%7B%0A++treeShaking%3A+true%2C%0A++external%3A+%5B%22c%22%2C+%22a%22%2C+%22b%22%5D%2C%0A%22bundle%22%3A+true%2C%0Aformat%3A+%22esm%22%2C%0Aplatform%3A+%22node%22%2C%0Aminify%3A+false%0A%7D

**Comment by IWANABETHATGUY** [comment]
We should generate a diagnostic
