### ISSUE TITLE
feature: expect rolldown to polyfill `import.meta.url` when the output format is CJS

### ISSUE THREAD

**Issue by sapphi-red** [rolldown/rolldown#2609]
### Reproduction link or steps

1. Open https://stackblitz.com/edit/github-xv4yss-h6rnrw?file=src%2Fentry.js,rolldown.config.mjs
2. `npm i` runs automatically
3. `npm run build` runs automatically
4. See the output containing `import.meta.url` as-is
5. Run `npm run build:up` to see how rollup behaves

### What is expected?

The output to work similarly to the input without any modification.
For example, rollup outputs the following code
```js
'use strict';

var _documentCurrentScript = typeof document !== 'undefined' ? document.currentScript : null;
console.log('foo', (typeof document === 'undefined' ? require('u' + 'rl').pathToFileURL(__filename).href : (_documentCurrentScript && _documentCurrentScript.tagName.toUpperCase() === 'SCRIPT' && _documentCurrentScript.src || new URL('entry.cjs', document.baseURI).href)));
```

### What is actually happening?

The output contains `import.meta.url` as-is causing the script to error when run.

### System Info

```Shell
Stackblitz

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    rolldown: https://pkg.pr.new/rolldown@829d80a => 0.13.2
```

### Any additional comments?

related code in rollup: https://github.com/rollup/rollup/blob/cdf34ab5411aac6ac3f6cd21b10d2e58427e88ec/src/ast/nodes/MetaProperty.ts#L205-L225

Found while trying to bundle Vite with Rolldown.

**Comment by hyf0** [comment]
Related: https://github.com/evanw/esbuild/issues/1492

**Comment by hyf0** [comment]
Thanks for the https://github.com/evanw/esbuild/issues/1492.

Does this workaround works as your expect:

```js
import { defineConfig } from 'rolldown';

export default defineConfig({
  input: ['./src/entry.js'],
  define: {
    'import.meta.url': `require("url").pathToFileURL(__filename)`,
  },
  output: {
    dir: './dist',
    entryFileNames: 'entry.cjs',
    format: 'cjs',
  },
});

```

**Comment by sapphi-red** [comment]
Yes, I used `'import.meta.url': "require('u' + 'rl').pathToFileURL(__filename).href",` to workaround it.

**Comment by hyf0** [comment]
I guess this is actually a do less or do more question. Let's wait more feedbacks. @yyx990803 cc

**Comment by hyf0** [comment]
I now prefer do more. This behavior would probably only be done if `format: 'cjs'` and `platform: 'node'`.

Does replaceing `import.meta.url` to `require("url").pathToFileURL(__filename)` is enough?

**Comment by sapphi-red** [comment]
The workaround of setting `'import.meta.url': "require('u' + 'rl').pathToFileURL(__filename).href",` only works if you are outputting for a single format. If you are outputting for multiple formats (e.g. IIFE, CJS, ESM), then the workaround does not work. Because define's replacement cannot be different for each formats.

> Does replaceing `import.meta.url` to `require("url").pathToFileURL(__filename)` is enough?

I think it should have `.href` at the end to align the types (`import.meta.url` returns a string, not a URL type). Replacing it should be enough.

**Comment by hyf0** [comment]
I'm thinking to use https://github.com/evanw/esbuild/issues/1633#issuecomment-944765929 as the polyfill when the platform is `node` or `browser` and the format is `iffe`. But I haven't think it through, if it's not urgent required, I'm gonna leave it for a while.
