### ISSUE TITLE
[Bug]: build panics on certain conditions 

### ISSUE THREAD

**Issue by HanabishiRecca** [rolldown/rolldown#2616]
### Reproduction link or steps

1. Install `@arcgis/core` npm package:
```sh
$ npm i '@arcgis/core'
```
2. Create `index.js`:
```js
import Graphic from "@arcgis/core/Graphic";
```
3. Build it with rolldown:
```sh
$ rolldown 'index.js' --dir 'dist'
```

### What is expected?

The project should build.

### What is actually happening?

Rolldown panics.

```
thread 'tokio-runtime-worker' panicked at core/src/slice/sort/shared/smallsort.rs:860:5:
user-provided comparison function does not correctly implement a total order
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
node:internal/process/promises:394
    triggerUncaughtException(err, true /* fromPromise */);
    ^

[Error: user-provided comparison function does not correctly implement a total order] {
  code: 'GenericFailure'
}

Node.js v23.1.0
```

### System Info

```
  Binaries:
    Node: 23.1.0 - /usr/bin/node
    npm: 10.9.0 - /usr/bin/npm
  npmPackages:
    rolldown: latest => 0.14.0 
```

### Any additional comments?

Reproducibility is not 100%. It's more like 50/50.

**Comment by ThatOneCalculator** [comment]
This is actually happening to me consistently right now with https://github.com/rolldown/vite (latest commit)

```
✓ 3162 modules transformed.
thread 'tokio-runtime-worker' panicked at core/src/slice/sort/shared/smallsort.rs:865:5:
user-provided comparison function does not correctly implement a total order
```

**Comment by IWANABETHATGUY** [comment]
> This is actually happening to me consistently right now with https://github.com/rolldown/vite (latest commit)
> 
> ```
> ✓ 3162 modules transformed.
> thread 'tokio-runtime-worker' panicked at core/src/slice/sort/shared/smallsort.rs:865:5:
> user-provided comparison function does not correctly implement a total order
> ```

Can you provide us a reproduced demo?

**Comment by ThatOneCalculator** [comment]
I can't make a minimal reproduction -- it seemingly has to do with a specific package or piece of code, but the errors printed are not helpful.

**Comment by ThatOneCalculator** [comment]
As mentioned in https://github.com/rolldown/rolldown/issues/3244#issuecomment-2563382078 , using the correct Vue Vite Plugin build fixes this issue.

**Comment by IWANABETHATGUY** [comment]
> As mentioned in [#3244 (comment)](https://github.com/rolldown/rolldown/issues/3244#issuecomment-2563382078) , using the correct Vue Vite Plugin build fixes this issue.
