### ISSUE TITLE
[Feature Request]: Expose `cssFileNames` and `cssChunkFileNames` options in js side

### ISSUE THREAD

**Issue by thesmartwon** [rolldown/rolldown#2618]
### What problem does this feature solve?

Cache busting

### What does the proposed API look like?

I think `assetFileNames` should be respected.

Related #2364

**Comment by hyf0** [comment]
`[hash]` is supported in `cssFilenNmes`. This issue's content is quite confusing, please describe it in detail.

**Comment by thesmartwon** [comment]
> `[hash]` is supported in `cssFilenNmes`

I don't see the string `cssFileNames` anywhere in this project. Passing it to `output` does nothing.

> This issue's content is quite confusing, please describe it in detail.

When bundling, instead of `dist/app.css` I'd like `dist/app-ABCDEFG.css` where `ABCDEFG` is the hash of the file contents. I can already control this for `entryFileNames` and `assetFileNames`. I'd like for CSS to respect `assetFileNames` or for a new `cssFileNames` option.

**Comment by hyf0** [comment]
Get it. I just looked into the code. Looks like we haven't expose the `cssFileNames` and `cssChunkFilenNames` in `rolldown` package.
