### ISSUE TITLE
[Feature Request]: keep `require` function name as-is

### ISSUE THREAD

**Issue by sapphi-red** [rolldown/rolldown#2684]
### What problem does this feature solve?

[`artichokie`](https://github.com/sapphi-red/artichokie), a library to run code in a worker, uses `Function::toString` on the main thread side and eval that string on the worker side.

When I use it like below:
```js
const worker = new Worker(() => {
    const path = require('node:path')
    return async (relative) => path.resolve(relative)
})

const result = await worker.run('./foo')
console.log(result) // /absolute/path/to/foo
```
and bundle that code by Rolldown. The output (sometimes?) becomes:
```js
const worker = new Worker(() => {
    const path = __require('node:path')
    return async (relative) => path.resolve(relative)
})

const result = await worker.run('./foo')
console.log(result) // /absolute/path/to/foo
```
(the `require` is renamed to `__require`.)

This code no longer runs because `__require` is not defined on the worker side (Because artichokie stringifies the function and put that on the worker side).

I know this is quite a hacky usecase, so I expect this issue to be closed as won't fix, but thought it would be nice to be supported.

Slightly related: if rolldown renames functions, it might need some feature like [`keepNames` in esbuild](https://esbuild.github.io/api/#keep-names).

### What does the proposed API look like?

No API changes. Just make rolldown to keep `require` as-is.

**Comment by IWANABETHATGUY** [comment]
what is the `format` of the output?

**Comment by IWANABETHATGUY** [comment]
https://hyrious.me/esbuild-repl/?version=0.23.0&b=e%00entry.js%00require%28%27node%3Apath%27%29&b=%00test.json%00%7B%0A%22test-test%22%3A+%22feaimefaw%22%2C%0A%22test%22%3A+%22test%22%0A%7D&o=%7B%0A++treeShaking%3A+true%2C%0A++external%3A+%5B%22c%22%2C+%22a%22%2C+%22b%22%5D%2C%0A%22bundle%22%3A+true%2C%0Aformat%3A+%22esm%22%2C%0Aplatform%3A+%22node%22%2C%0Aminify%3A+false%0A%7D, Here is an example if the `format` is not cjs and the `specifier` is a external module, then esbuild will try to rewrite `require` to `__require` and inject the related runtime

**Comment by sapphi-red** [comment]
Format is ESM.

**Comment by IWANABETHATGUY** [comment]
https://github.com/rolldown/rolldown/blob/21ee99b5b172c6ef42d3ca3e458353e1a5a59d03/crates/rolldown/src/runtime/runtime-without-comments.js#L58-L66 here is how `__require` looks like, if `require` is exists in `globalThis`, `__require` should works same as `require`.
Can you provide the reproduce steps ?

**Comment by sapphi-red** [comment]
Here's the reproduction: https://stackblitz.com/edit/github-xv4yss-dubrwq?file=rolldown.config.mjs,src%2Fentry.cjs
`node src/entry.cjs` works but `node dist/entry.cjs` fails.

**Comment by IWANABETHATGUY** [comment]
I just found we have the same output as esbuild, except when you specify `platform: node` esbuild will auto set `output.format` as `cjs` if you don't explicitly set `output.format`.

**Comment by IWANABETHATGUY** [comment]
after auto polyfill `require()` in `format: esm + node platform` do we still need this feature?

**Comment by sapphi-red** [comment]
I think yes. This is the reproduction with the new version: https://stackblitz.com/edit/github-xv4yss-75buft?file=rolldown.config.mjs
(I also fixed the `entryFileNames` option. It should have been `entry.js` and not `entry.cjs`.)

**Comment by hyf0** [comment]
I tried latest rolldown and it seems solved. https://stackblitz.com/edit/github-xv4yss-yqdkzynx?file=package.json,dist%2Fentry.js

---

ignore this. I misunderstand the problem

**Comment by sapphi-red** [comment]
@IWANABETHATGUY Is the new `output.polyfillRequire` option expected to be used like below? (Just confirming)
```js
{
  output: {
    polyfillRequire: false,
    banner:
      "import { createRequire as ___createRequire } from 'module'; const require = ___createRequire(import.meta.url);",
  },
}
```
https://stackblitz.com/edit/github-xv4yss-9324azps?file=rolldown.config.mjs,src%2Fentry.cjs

**Comment by IWANABETHATGUY** [comment]
When you disabled `polyfillRequire` in `platform: node` and `format: esm`, rolldown will not rewrite `require`, so yes, you need to 
 polyfill the require.
