### ISSUE TITLE
[Bug]: `RenderedModule.renderedLength` support

### ISSUE THREAD

**Issue by sapphi-red** [rolldown/rolldown#2686]
### Reproduction link or steps

1. Open https://stackblitz.com/edit/github-xv4yss-ggycbu?file=rolldown.config.mjs
2. `npm i` runs automatically
3. `npm run build` runs automatically
4. `chunk modules [ undefined, undefined ]` is output in the terminal
5. run `npm run build:up` to use rollup
6. `chunk modules [ 46, 19 ]` is output in the terminal

### What is expected?

`chunk modules [ number, number ]` is output (`RenderedModule.renderedLength` is supported)

### What is actually happening?

`chunk modules [ undefined, undefined ]` is output (`RenderedModule.renderedLength` is not supported)

### System Info

```Shell
Stackblitz

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    rolldown: https://pkg.pr.new/rolldown@f94549f => 0.14.0
```

### Any additional comments?

Found while trying to bundle Vite with Rolldown.
This property is necessary to make `rollup-plugin-license` to work ([relevant code](https://github.com/mjeanroy/rollup-plugin-license/blob/66333ea04aa0e204f43f976439fe4fae50dd8cdb/src/index.js#L58-L60)).

**Comment by hyf0** [comment]
Some notes:

- These numbers should be calculated based on utf-16.
