### ISSUE TITLE
implement `import.meta.resolve` 

### ISSUE THREAD

**Issue by IWANABETHATGUY** [rolldown/rolldown#2712]
TODO:
- import.meta.resolve
- [proposal-asset-references](https://github.com/tc39/proposal-asset-references)

_Originally posted by @magic-akari in https://github.com/rolldown/rolldown/issues/2710#issuecomment-2472279105_

**Comment by hyf0** [comment]
More contexts:

- https://github.com/evanw/esbuild/issues/2866

**Comment by hyf0** [comment]
After some discussions, rolldown isn't gonna do anything related to `import.meta.resolve` in compile time and it would be kept it as it is.

The behavior of `import.meta.resolve` is affected by the host runtime, so it's not proper for rolldown to do any assumption.
