### ISSUE TITLE
[Bug]: should use bare identifier for external module that is matched by `external` option

### ISSUE THREAD

**Issue by conmaster2112** [rolldown/rolldown#2750]
### Reproduction link or steps

1. Install Rolldown v0.14.0
```
npm i rolldown@nightly -D
```

2. Create Config File `rolldown.config.js`
```js
import { defineConfig } from 'rolldown';

export default defineConfig({
  input: 'index.ts',
  external: [
    /node_module/g //Match based on raw path, intend to mark all node packages as external
  ],
  output: {
    file: "index.js"
  }
});
```
3. Add src file `index.ts`
```ts
import rolldown from "rolldown";
console.log(rolldown);
```
4. Run Rolldown
```
npx rolldown -c
```

### What is expected?

Bundled out put file should exclude external packages and keep its imports same as before, unless you have more complex resolve settings.

Expected result
```js
import rolldown from "rolldown";
console.log(rolldown);
```

### What is actually happening?

Rolldown would change the import path based on matching results from external regex from config, with corrupted path format.

My case:
```js
import rolldown from "D:\Resources\Programming\JavaScript\bundler-test\node_modules\rolldown\dist\esm\index.mjs";

//#region src/index.ts
console.log(rolldown);

//#endregion
```

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 5.83 GB / 15.64 GB
  Binaries:
    Node: 22.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.2.4 - ~\AppData\Roaming\npm\npm.CMD
    pnpm: 9.12.3 - ~\AppData\Local\pnpm\pnpm.EXE
    bun: 1.1.8 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (129.0.2792.79)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    rolldown: ^0.14.0-snapshot-6d170b4-20241115003513 => 0.14.0-snapshot-6d170b4-20241115003513
```

### Any additional comments?

Shouldn't be option to create includes regex? For files to bundle only, lets say i want to bundle only files from `./src/` diractory

**Comment by hyf0** [comment]
Looks like a bug. Thanks for reporting.

**Comment by hyf0** [comment]
Interesting. So the steps is
1. Rolldown resolve `rolldown` to `D:\Resources\Programming\JavaScript\bundler-test\node_modules\rolldown\dist\esm\index.mjs`
2. Rolldown apply `external` option on `D:\Resources\Programming\JavaScript\bundler-test\node_modules\rolldown\dist\esm\index.mjs`
3. Rolldown found it external and return `D:\Resources\Programming\JavaScript\bundler-test\node_modules\rolldown\dist\esm\index.mjs` as the external path

But what you want is returning `rolldown` as the external path?

**Comment by conmaster2112** [comment]
> Interesting. So the steps is
> 
> 1. Rolldown resolve `rolldown` to `D:\Resources\Programming\JavaScript\bundler-test\node_modules\rolldown\dist\esm\index.mjs`
> 2. Rolldown apply `external` option on `D:\Resources\Programming\JavaScript\bundler-test\node_modules\rolldown\dist\esm\index.mjs`
> 3. Rolldown found it external and return `D:\Resources\Programming\JavaScript\bundler-test\node_modules\rolldown\dist\esm\index.mjs` as the external path
> 
> But what you want is returning `rolldown` as the external path?

Its, pseudo concept it could be any package, i just want to exclude node modules from the bundled code, its great to use rolldown example, bc its already installed by the tool it self

**Comment by hyf0** [comment]
The current behavior is expected, because that's how it works and rollup has the same behavior. You could check it out here: https://stackblitz.com/edit/stackblitz-starters-wt4xfw?file=output%2Fmain.js.

`@rollup/plugin-node-resolve` as plugin does a extra check to ensure return `rolldown` instead of the absolute path. But it's a plugin behavior. We need to consider moving this to the rolldown core doesn't break other things.

**Comment by conmaster2112** [comment]
And what about includes feature? So i could specify what files from directory to include for bundling? What do you think about it?

Also do you think you can link me some projects that rely on absolute paths here?

**Comment by hyf0** [comment]
> And what about includes feature? So i could specify what files from directory to include for bundling?

No official plan for this feature. But you should able to do it via plugin system I guess.

**Comment by hi-ogawa** [comment]
I think this is working intended and it can be closed.

>  i just want to exclude node modules from the bundled code

 For this specific need (and I assume library build in general), what's commonly done is to specify a few `external` manually or reuse package.json `dependencies`, something like:

https://github.com/rolldown/rolldown/blob/ab7b6b4dedcb2cbeaadb404a234d44efbc8cc100/packages/rolldown/build.ts#L20-L28
