### ISSUE TITLE
[Bug]: gets stuck when calling `this.load` with same id in parallel

### ISSUE THREAD

**Issue by sapphi-red** [rolldown/rolldown#2751]
### Reproduction link or steps

1. Open https://stackblitz.com/edit/github-xv4yss-qaagcu?file=rolldown.config.mjs,package.json
2. `npm run build` runs automatically
3. Rolldown command does not end

Note this happens not only on Stackblitz but also on Windows as well.

### What is expected?

The build finishes.

### What is actually happening?

The build does not finish.

### System Info

```Shell
Stackblitz

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    rolldown: https://pkg.pr.new/rolldown@cce5cde => 0.14.0
```

### Any additional comments?

I found this when I tried to enable some disabled tests in rolldown-vite.

**Comment by sapphi-red** [comment]
My guess is that there's a logic that does something like:
```js
let processing = 0
let processPromises = {}

const load = () => {
  load++
  processPromises[id] ??= actualLoad()
  return processPromises[id]
}

const actualLoad = async () => {
  // do actual load

  delete processPromises[id]
  load--
}
```

**Comment by underfin** [comment]
@sapphi-red You case has one problem loading `foo.js` at transform `foo.js`, it will caused dead lock. The rollup will give a error like

```
[!] Error: Unexpected early exit. This happens when Promises returned by plugins cannot resolve. Unfinished hook action(s) on exit:
(loader) transform "/home/projects/github-xv4yss-qaagcu/src/entry.js"
(loader) transform "/home/projects/github-xv4yss-qaagcu/src/foo.js"
```

I will give a more specific error for it.

**Comment by sapphi-red** [comment]
Ah, true. I didn't intend that one.
Just in case, this is the diff needed to reproduce my bug:
```diff
-        if (id.startsWith('/resolved:')) return;
+        if (!id.endsWith('entry.js')) return;
```

**Comment by underfin** [comment]
> @sapphi-red You case has one problem loading `foo.js` at transform `foo.js`, it will caused dead lock. The rollup will give a error like
> 
> ```
> [!] Error: Unexpected early exit. This happens when Promises returned by plugins cannot resolve. Unfinished hook action(s) on exit:
> (loader) transform "/home/projects/github-xv4yss-qaagcu/src/entry.js"
> (loader) transform "/home/projects/github-xv4yss-qaagcu/src/foo.js"
> ```
> 
> I will give a more specific error for it.

Need to resolve.
