### ISSUE TITLE
[Bug]: assigning to `moduleSideEffects` returned from `this.load` has no effect

### ISSUE THREAD

**Issue by sapphi-red** [rolldown/rolldown#2752]
### Reproduction link or steps

1. Open https://stackblitz.com/edit/github-xv4yss-a7mdan?file=rolldown.config.mjs
2. `npm run build` runs automatically
3. Output includes `console.log("no sideeffects");`
4. Run `npm run build:up` to use rollup
5. Output does not include `console.log("no sideeffects");`

### What is expected?

Output to not include `console.log("no sideeffects");`

### What is actually happening?

Output includes `console.log("no sideeffects");`

### System Info

```Shell
Stackblitz

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    rolldown: https://pkg.pr.new/rolldown@cce5cde => 0.14.0
```

### Any additional comments?

I guess this is hard to fix.

**Comment by underfin** [comment]
@sapphi-red here should be using like 

```.js
  const moduleInfo = await this.load({
    id: path.join(__dirname, 'foo.js'),
    moduleSideEffects: false,
  })
```
