### ISSUE TITLE
[Feature Request]: Enable `inlineDynamicImports` automatically if format is `iffe` or `umd`

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#2792]
### What problem does this feature solve?

Improve UX.

### What does the proposed API look like?

This issue includes two main tasks:
- Set `inlineDynamicImports: true` if format is `iffe` or `umd`  https://github.com/rolldown/rolldown/blob/8ef1b106a4796c54a04d018e317a29c41cb75009/crates/rolldown/src/utils/normalize_options.rs#L133
- If `inlineDynamicImports` is set to `false` by user, a warning should be emitted and we still set `inlineDynamicImports` to be `true`.

**Comment by shulaoda** [comment]
I find it a bit difficult to trigger a warning. Although I triggered it within `Bundler::new` using `block_on`, it seems to cause some kind of deadlock-like issue.
