### ISSUE TITLE
How export rolldown resolver?

### ISSUE THREAD

**Issue by underfin** [rolldown/rolldown#282]
### Description 

The rollup external node packages by default, it need `@rollup/plugin-resolve` to do it. The rolldown maybe have some ways to do it, it need discuss at now.

1. enable node packages by default,  add `resolve` option to control the resolver behavior.
2. follow rollup and add `resolve` option to enable native plugin `plugin-resolve`.

Hope get some advices, thanks.

**Comment by yyx990803** [comment]
I think we should resolve `node_modules` by default as that is a far more ergonomic default for most users.

But also need an option / flag to turn it off and give users full control over resolution.
