### ISSUE TITLE
[Bug]: watch does not trigger build when a file change happened while building

### ISSUE THREAD

**Issue by sapphi-red** [rolldown/rolldown#2830]
### Reproduction link or steps

1. Made `foo.mjs` with the content below
1. Run it with `node foo.mjs`
1. See `dist/bar.js`

```js
// foo.mjs

fs.writeFileSync('./bar.mjs', '')

import fs from 'node:fs'
import { watch } from 'rolldown'

const w = await watch({
  input: './bar.mjs',
  plugins: [
    {
      name: 'run',
      async renderChunk() {
        console.log('renderchunk')
        await new Promise((resolve) => setTimeout(resolve, 1000))
      },
    },
  ],
})

w.on('event', (event) => {
  console.log('event', event)
})

await new Promise((resolve) => setTimeout(resolve, 100))

fs.writeFileSync('./bar.mjs', 'console.log("bar")')
console.log('wrote')
```

### What is expected?

`dist/bar.js` is contains `console.log("bar")`

### What is actually happening?

`dist/bar.js` is empty

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 10.98 GB / 31.92 GB
  Binaries:
    Node: 22.11.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.9.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.12.3 - C:\Program Files\nodejs\pnpm.CMD
    bun: 1.1.29 - ~\AppData\Local\Microsoft\WinGet\Links\bun.EXE
  Browsers:
    Edge: Chromium (130.0.2849.56)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    rolldown: https://pkg.pr.new/rolldown@01cedb9 => 0.14.0
```

### Any additional comments?

Found while trying to enable watch related tests on rolldown-vite

**Comment by underfin** [comment]
@sapphi-red Could you add `println!("watch event {:?}", event);` at https://github.com/rolldown/rolldown/blob/main/crates/rolldown/src/watcher/watcher.rs#L246. Then use local build to see the event, not sure how the event is emitted at windows, i remember it should be `EventKind::Modify(ModifyKind::Any)`.

**Comment by sapphi-red** [comment]
No event happened. If I change the file after the bundle is finished, the event happens and it was `EventKind::Modify(ModifyKind::Any)`.

**Comment by sapphi-red** [comment]
Maybe this happens because rollup starts watching the files when each file is transformed, but rolldown starts watching all the files after the complete bundle is finished.

**Comment by sapphi-red** [comment]
I think this can be deprioritized as I noticed that this is not required for the tests to pass and is an edge case.

**Comment by underfin** [comment]
> Maybe this happens because rollup starts watching the files when each file is transformed, but rolldown starts watching all the files after the complete bundle is finished.

Yeah. You are right, ref https://github.com/rollup/rollup/blob/master/src/watch/watch.ts#L209.
