### ISSUE TITLE
[Bug]: crashes when bundling code that contains `import` inside a block to IIFE format

### ISSUE THREAD

**Issue by sapphi-red** [rolldown/rolldown#2833]
### Reproduction link or steps

1. Open https://stackblitz.com/edit/github-xv4yss-hbqsc1?file=rolldown.config.mjs,src%2Fentry.js
2. `npm run build` runs automatically
3. Rolldown crashes

### What is expected?

No crash happens

### What is actually happening?

Rolldown crashes with the following message:
```
thread '<unnamed>' panicked at crates/rolldown/src/module_finalizers/scope_hoisting/impl_visit_mut.rs:568:43:
no entry found for key
```

### System Info

```Shell
Stackblitz

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    rolldown: https://pkg.pr.new/rolldown@01cedb9 => 0.14.0
```

### Any additional comments?

Found while trying to upgrade rolldown in rolldown-vite.

**Comment by shulaoda** [comment]
I did some quick research, and enabling `inlineDynamicImports` results in an error with the `import('..')` syntax, regardless of the `output.format` setting. This is because we did not record `import('..')` in `module.imports`.

https://github.com/rolldown/rolldown/blob/ded9a4f17aebf3ba37b108f6394901865639b14b/crates/rolldown/src/module_finalizers/scope_hoisting/impl_visit_mut.rs#L563-L568

**Comment by hyf0** [comment]
> I did some quick research, and enabling `inlineDynamicImports` results in an error with the `import('..')` syntax, regardless of the `output.format` setting. This is because we did not record `import('..')` in `module.imports`.
> 
> [rolldown/crates/rolldown/src/module_finalizers/scope_hoisting/impl_visit_mut.rs](https://github.com/rolldown/rolldown/blob/ded9a4f17aebf3ba37b108f6394901865639b14b/crates/rolldown/src/module_finalizers/scope_hoisting/impl_visit_mut.rs#L563-L568)
> 
> Lines 563 to 568 in [ded9a4f](/rolldown/rolldown/commit/ded9a4f17aebf3ba37b108f6394901865639b14b)
> 
>  fn try_rewrite_inline_dynamic_import_expr( 
>    &mut self, 
>    import_expr: &mut ImportExpression<'ast>, 
>  ) -> Option<Expression<'ast>> { 
>    if self.ctx.options.inline_dynamic_imports { 
>      let rec_id = self.ctx.module.imports[&import_expr.span];

Should check if `self.ctx.module.imports[&import_expr.span]` exist instead of getting it directly.

**Comment by shulaoda** [comment]
> Should check if `self.ctx.module.imports[&import_expr.span]` exist instead of getting it directly.

You're right. This issue only occurs when `import(path)` is used with a variable `path`.
