### ISSUE TITLE
[Bug]: incompatible `watch` API

### ISSUE THREAD

**Issue by sxzz** [rolldown/rolldown#2842]
### Reproduction link or steps

N/A

### What is expected?

https://github.com/rolldown/rolldown/blob/1ae6760fa540f8c608143849c4bf56ae806ef348/packages/rolldown/src/rolldown.ts#L14

https://github.com/rolldown/rolldown/blob/1ae6760fa540f8c608143849c4bf56ae806ef348/packages/rolldown/src/options/watch-option.ts#L4-L6

Both `input` and `output` should be arrayable to align with [Rollup](https://rollupjs.org/javascript-api/#watchoptions).

### What is actually happening?

Not support arrayable input/output config.

### System Info

```Shell
N/A
```

**Comment by underfin** [comment]
@sxzz The `input` is not arrayable at rollup. The `output` is not arrayable at rolldown, because the rolldown intends to support one `output` configure, it similar to `RolldownOption`.

**Comment by sxzz** [comment]
See https://github.com/rollup/rollup/blob/7c0b1f8810013b5a351a976df30a6a5da4fa164b/src/rollup/types.d.ts#L1031 for input options

If Rolldown doesn't support arrays for input or output, how can it outputs two module formats with one watcher?

**Comment by underfin** [comment]
> See https://github.com/rollup/rollup/blob/7c0b1f8810013b5a351a976df30a6a5da4fa164b/src/rollup/types.d.ts#L1031 for input options
> 
> If Rolldown doesn't support arrays for input or output, how can it outputs two module formats with one watcher?

Oh. I get it.

**Comment by underfin** [comment]
closed by https://github.com/rolldown/rolldown/pull/3037
