### ISSUE TITLE
[Bug]: the module has sideEffects is removed

### ISSUE THREAD

**Issue by underfin** [rolldown/rolldown#2864]
### Reproduction link or steps

https://stackblitz.com/edit/github-qovohk?file=rolldown.config.mjs,src%2Fentry.js,src%2Ffoo.js,src%2Fsideeffect.js,src%2Fcommon.js,dist%2Fentry.js

### What is expected?

The `globalThis.aa = true` should not treeshakend.

### What is actually happening?

The `globalThis.aa = true` is treeshakend.

### System Info

```Shell
-
```

**Comment by shulaoda** [comment]
I investigated `esbuild`, `Rollup`, and `Parcel`, and they all behave as expected above.

**Comment by IWANABETHATGUY** [comment]
closed in favor of #3190
