### ISSUE TITLE
[Bug]: the type of `NormalizedOutputOptions.format` is not compatible with rollup

### ISSUE THREAD

**Issue by sapphi-red** [rolldown/rolldown#2867]
### Reproduction link or steps

The type in rolldown is `format?: ModuleFormat`.
https://github.com/rolldown/rolldown/blob/f6ac721d00627060db3e147b8a9a6c065e097976/packages/rolldown/src/options/normalized-output-options.ts#L5
https://github.com/rolldown/rolldown/blob/f6ac721d00627060db3e147b8a9a6c065e097976/packages/rolldown/src/rollup.d.ts#L805

The type in rollup is `format: InternalModuleFormat`
https://github.com/rollup/rollup/blob/dd623b56e340e51ebb09d5d1a3a9323f5f50fb3a/src/rollup/types.d.ts#L811

The types of `NormalizedOutputOptions` is used in `renderChunk` hook.

### What is expected?

The type is compatible.

### What is actually happening?

The type is not compatible.

### System Info

```Shell
N/A
```

### Any additional comments?

related https://github.com/rolldown/rolldown/pull/2848

**Comment by hyf0** [comment]
Should be solved after https://github.com/rolldown/rolldown/issues/1041.
