### ISSUE TITLE
[Bug]: builtin plugin name is `number` instead of `string`

### ISSUE THREAD

**Issue by hi-ogawa** [rolldown/rolldown#2879]
### Reproduction link or steps

reproduction: https://stackblitz.com/edit/github-8wylpe?file=rolldown.config.mjs

```ts
import * as rolldownExperimental from 'rolldown/experimental';
console.log(rolldownExperimental.transformPlugin());
// => TransformPlugin { name: 6, options: undefined }
```

### What is expected?

`string`

### What is actually happening?

`number`

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    rolldown: latest => 0.14.0
```

### Any additional comments?

When using native plugin on Vite, I was using `plugins.filter(plugin => plugin.name.startsWith("..."))` to do some filtering, but found that `plugin.name` is a number for native plugin. Probing `plugins` array like this is Vite specific trick, but it would be probably nice if number encoding is not visible to Js users and presented as string based on some convention (`builtin:...` or `rolldown:builtin:...`?).

**Comment by hyf0** [comment]
Yeah. This is not expected.Though we use `instanceof BuiltinPlugin` to check if a plugin is builtin, it should at least have meaningful plugin name like `builtin:xxx`
