### ISSUE TITLE
Check if `unplugin-isolated-decl` is work after https://github.com/rolldown/rolldown/issues/1041

### ISSUE THREAD

**Issue by IWANABETHATGUY** [rolldown/rolldown#2885]
> @hyf0 
> 
> This change could be considered a major update that breaks https://github.com/unplugin/unplugin-isolated-decl
> 
> 1. This plugin didn't treat Rolldown specially but regarded it as Rollup.
> 2. It relies on the default value of `NormalizedOutputOptions.entryFileNames`, which is `[name].js` in Rollup, but now it's undefined.
> 3. `NormalizedInputOptions.input` is `string[] | Record<string, string>` in Rollup and can be a `string` in Rolldown.
> 
> If this is by design, I hope the Rolldown team will reconsider. 

 _Originally posted by @sxzz in [#2835](https://github.com/rolldown/rolldown/issues/2835#issuecomment-2495551100)_

**Comment by hyf0** [comment]
I'll add a compatibility test.  Not sure where to put it. Anyway, I'll add one in `rolldown/tests`. Let's make it work first.

**Comment by sxzz** [comment]
After commit https://github.com/unplugin/unplugin-isolated-decl/commit/ab6fe9001e6aa3490c3075e98c5100b93f427f6b, unplugin-isolated-decl is supported the latest Rolldown.

**Comment by hyf0** [comment]
@sxzz Cool. I just fixed it too. I checked `0.8.0` works well with rolldown's fixes [1](https://github.com/rolldown/rolldown/pull/2894), [2](https://github.com/rolldown/rolldown/pull/2899).
