### ISSUE TITLE
Pass normalized options from rust to js

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#2906]
# If you are interested in some tasks, please first claim them in the comments, then raise a PR.

This is a follow up of https://github.com/rolldown/rolldown/issues/1041.

So far we are passing the normalize options(done in rust side) from rust to js. I have already build the basic infra for this requirement and consider this as good chance to involve contributors.

Task are

## ~~Pass normalized options itself from rust to js for hooks~~ Solved

There are some plugin hooks that require to access normalized options and I just pass faked to them as an workaround to pass type-check.

For guidance, you could see how I did this to `generateBundle` hook in https://github.com/rolldown/rolldown/pull/2902.

- ~~`renderChunk` hook~~

https://github.com/rolldown/rolldown/blob/788d7fc54b5beb0adb9003056e214139d1a4a2d8/packages/rolldown/src/plugin/bindingify-output-hooks.ts#L73-L74

- ~~`writeBundle` hook~~

https://github.com/rolldown/rolldown/blob/788d7fc54b5beb0adb9003056e214139d1a4a2d8/packages/rolldown/src/plugin/bindingify-output-hooks.ts#L213-L214

## Pass normalized fields from rust to js

For guidance, you could see how I did this in https://github.com/rolldown/rolldown/pull/2900.

```js
export interface NormalizedOutputOptions {
	assetFileNames: string | ((chunkInfo: PreRenderedAsset) => string);
	banner: AddonFunction;
	chunkFileNames: string | ((chunkInfo: PreRenderedChunk) => string);
	dir: string | undefined; // solved
	entryFileNames: string | ((chunkInfo: PreRenderedChunk) => string);
	esModule: boolean | 'if-default-prop';
	exports: 'default' | 'named' | 'none' | 'auto'
	externalLiveBindings: boolean;
	file: string | undefined;
	footer: AddonFunction;
	format: InternalModuleFormat; // Supported by rolldown already
	inlineDynamicImports: boolean; // solved
	name: string | undefined;
	outro: AddonFunction;
	sourcemap: boolean | 'inline' | 'hidden'; // solved
	sourcemapBaseUrl: string | undefined;
	sourcemapExcludeSources: boolean;
	sourcemapFile: string | undefined;
	sourcemapFileNames: string | ((chunkInfo: PreRenderedChunk) => string) | undefined;
}
```

This is current supported options

https://github.com/rolldown/rolldown/blob/87f7277c36256a81ee170c5483fb2a352b669e5b/packages/rolldown/src/options/normalized-output-options.ts#L7-L10

For input options, I don't feel there are fields need to support so I didn't list them here.

**Comment by sapphi-red** [comment]
For `dir` and `inline_dynamic_imports` and `sourcemap` properties, I'll do them as those types are used by Vite.

**Comment by sapphi-red** [comment]
I'll do the `renderChunk` hook, it was also needed.

**Comment by shulaoda** [comment]
I'll finish `writeBundle` hook. 

I'm curious, if each plugin's hook passes `options` from `rust` to `js`, wouldn't this result in creating a new options object each time? Compared to js originally sharing a single options object, wouldn't this lead to higher memory usage when there are more plugins?

**Comment by hyf0** [comment]
@shulaoda 

> wouldn't this result in creating a new options object each time?

Yeah. This could be improved by storing only one options object. However, having correct behaviors is the first thing to do.

**Comment by ikkz** [comment]
I will complete the "Pass normalized fields from Rust to JS."

And it seems that some tests might also need to be added on the JS side?

**Comment by ikkz** [comment]
And do I only need to handle the fields listed in the issue body, or should I handle as many fields as possible in [NormalizedBundlerOptions](https://github.com/rolldown/rolldown/blob/main/crates/rolldown_common/src/inner_bundler_options/types/normalized_bundler_options.rs#L30)?

**Comment by hyf0** [comment]
> And do I only need to handle the fields listed in the issue body, or should I handle as many fields as possible in [NormalizedBundlerOptions](https://github.com/rolldown/rolldown/blob/main/crates/rolldown_common/src/inner_bundler_options/types/normalized_bundler_options.rs#L30)?

Yeah. It's all welcome. Just make sure to claim them with comments, so others know what you are working on.

**Comment by ikkz** [comment]
ok, I will finish these properties: `cwd, platform, name, css_entry_filenames, css_chunk_filenames, chunk_filenames, asset_filenames, file, exports, es_module, banner, footer, intro, outro, external_live_bindings`

**Comment by shulaoda** [comment]
I will complete the remaining properties of `NormalizedBundlerOptions` that were not listed above and align them with `rollup`.
