### ISSUE TITLE
[Bug]: moduleInfo.assertions gives "Cannot read properties of null" error

### ISSUE THREAD

**Issue by drwpow** [rolldown/rolldown#2950]
### Reproduction link or steps

Rolldown breaks when using [rollup-plugin-import-css](https://www.npmjs.com/package/rollup-plugin-import-css). Minimal repro here: https://github.com/drwpow/rolldown-moduleinfo-assertions.

### What is expected?

Builds

### What is actually happening?

```
[UNHANDLEABLE_ERROR] Error: Something wrong inside the rolldown, please report this at https://github.com/rolldown/rolldown/issues.
GenericFailure, TypeError: Cannot read properties of null (reading 'assertions')

[UNHANDLEABLE_ERROR] Error: Something wrong inside the rolldown, please report this at https://github.com/rolldown/rolldown/issues.
GenericFailure, TypeError: Cannot read properties of null (reading 'assertions')

node:internal/process/promises:394
    triggerUncaughtException(err, true /* fromPromise */);
    ^

[Error: Build failed] { code: 'GenericFailure' }

Node.js v22.11.0
```

### System Info

```Shell
System:
    OS: macOS 15.1.1
    CPU: (8) arm64 Apple M2
    Memory: 86.27 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.11.0 - ~/.local/state/fnm_multishells/3279_1732684030822/bin/node
    npm: 10.9.0 - ~/.local/state/fnm_multishells/3279_1732684030822/bin/npm
    pnpm: 9.14.2 - ~/Library/pnpm/pnpm
  Browsers:
    Safari: 18.1.1
  npmPackages:
    rolldown: ^0.14.0 => 0.14.0
```

### Any additional comments?

Thanks for such an exciting project 🙂

**Comment by hyf0** [comment]
It's not supported so far. I guess we could provide a fake property as workaround.

**Comment by drwpow** [comment]
Feel free to close if it’s already tracked as part of #819, or if this is an intentional breaking change! I just couldn’t tell if this was known.

**Comment by hi-ogawa** [comment]
Interestingly, build passes with nightly `0.14.0-snapshot-f1bd92f-20241126015006`. Since rolldown has builtin css support, it looks like you don't need `rollup-plugin-import-css` for simple side effect import usage like your `import './styles.css'`.

```js
$ pnpm build
<DIR>/index.css     asset │ size: 0.21 kB                                                          
<DIR>/index.js.map  asset │ size: 0.31 kB                                                          
<DIR>/index.js      chunk │ size: 0.18 kB                                                          
```

To disable builtin css support in favor of `rollup-plugin-import-css`, you probably need to overwrite `moduleTypes`:

```js
export default {
  // ...
  moduleTypes: {
    css: 'js'
  }
}
```

```js
$ pnpm build
<DIR>/all-components.css  asset │ size: 0.21 kB                                                    
<DIR>/index.js.map        asset │ size: 0.31 kB                                                    
<DIR>/index.js            chunk │ size: 0.18 kB                                                    
 ```

**Comment by drwpow** [comment]
> Since rolldown has builtin css support, it looks like you don't need `rollup-plugin-import-css`

🤩 That’s great news!

Still wanted to raise it just in case this is an API you all wanted to carry forward, or not (e.g. raise an error).

When I run my React + CSS project without `rollup-plugin-import-css`, I get another error (below). But I’ll make another minimal repro to find what that issue is:

```
thread 'tokio-runtime-worker' panicked at core/src/slice/sort/shared/smallsort.rs:860:5:
user-provided comparison function does not correctly implement a total order
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
node:internal/process/promises:394
    triggerUncaughtException(err, true /* fromPromise */);
    ^

[Error: user-provided comparison function does not correctly implement a total order] {
  code: 'GenericFailure'
}
```

**Comment by IWANABETHATGUY** [comment]
Can you try nightly? I can't reproduce the panic with your steps.

**Comment by drwpow** [comment]
> Can you try nightly? I can't reproduce the panic with your steps.

Yes! Nightly works for me. I was actually trying to create a minimal repro with React + CSS + `@latest` and couldn’t. That error is from a monorepo ([draft PR](https://github.com/terrazzoapp/terrazzo/pull/362)) with lots of other things happening on `@latest`, but the nightly works on the monorepo, so this might be fixed!
