### ISSUE TITLE
[Bug]: `Convert json sourcemap error: BadSourceReference(1)` error happens

### ISSUE THREAD

**Issue by sapphi-red** [rolldown/rolldown#2969]
### Reproduction link or steps

1. Open https://stackblitz.com/edit/github-xv4yss-k6oupm?file=rolldown.config.mjs
2. `npm run build` runs automatically
3. rolldown errors

### What is expected?

No error happens.

### What is actually happening?

The following error happens:
```
Error: [UNHANDLEABLE_ERROR] Error: Something wrong inside the rolldown, please report this at https://github.com/rolldown/rolldown/issues.
Convert json sourcemap error: BadSourceReference(1)
```

### System Info

```Shell
Stackblitz

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    rolldown: 0.14.0-snapshot-5e571e4-20241128015029 => 0.14.0-snapshot-5e571e4-20241128015029
```

### Any additional comments?

Found while trying to update rolldown in rolldown-vite

**Comment by shulaoda** [comment]
This should be an issue with `oxc_sourcemap`

**Comment by shulaoda** [comment]
I believe the issue has been fixed, and I have tested it on both the `js` and `rust` sides with the latest code. 

Perhaps we should trigger the `Publish to pkg.pr.new` pipeline to get the latest version and test again.

**Comment by shulaoda** [comment]
The issue has indeed been fixed using the version from three days ago: https://pkg.pr.new/rolldown@446dca9.

**Comment by underfin** [comment]
> The issue has indeed been fixed using the version from three days ago: https://pkg.pr.new/rolldown@446dca9.

 ``` .js
{
      name: 'vite:css-post',
      transform(code, id) {
        if (id.endsWith('imported-with-import.css')) {
          return {
            code: 'export {}',
            map: { mappings: '' },
          };
        }
      },
    },
```

Yeah. The edge case is fixed, but breaking the sourcemap if the transform hook returned sourcemap contains multiple sources. Let me fix it.
