### ISSUE TITLE
[Bug]: class name is error after deconfilct

### ISSUE THREAD

**Issue by underfin** [rolldown/rolldown#2985]
### Reproduction link or steps

[reproduction](https://hyrious.me/esbuild-repl/?version=0.24.0&b=e%00entry.js%00import+Bar+from+%27.%2Ffile%27%3B%0A%0Aconst+wrapper+%3D+%28%29+%3D%3E+%7B%0A%09class+Foo+extends+Bar+%7B%0A%09%09static+assertName%28%29+%7B%0A%09%09%09assert.strictEqual%28this.name%2C+%27Foo%27%29%3B%0A%09%09%09assert.strictEqual%28super.name%2C+%27Foo%27%29%3B%0A%09%09%7D%0A%09%7D%0A%0A%09return+Foo%3B%0A%7D%3B%0A%0Awrapper%28%29.assertName%28%29%3B&b=%00file.js%00export+default+class+Foo+%7B%7D&o=%7B%0A++bundle%3A+true%2C%0A++outdir%3A+%27dist%27%2C%0A++external%3A+%5B%27external%27%5D%2C%0A++format%3A+%27esm%27%2C%0A++keepNames%3A+false%0A%7D)

You could see the class name is incorrect, the rolldown output is same as esbuild.

### What is expected?

Esbuild using `keepNames` to make sure the class name is correct, but the rollup is default to make the output is correct. ref https://esbuild.github.io/api/#keep-names.

[Expected result](https://hyrious.me/esbuild-repl/?version=0.24.0&b=e%00entry.js%00import+Bar+from+%27.%2Ffile%27%3B%0A%0Aconst+wrapper+%3D+%28%29+%3D%3E+%7B%0A%09class+Foo+extends+Bar+%7B%0A%09%09static+assertName%28%29+%7B%0A%09%09%09assert.strictEqual%28this.name%2C+%27Foo%27%29%3B%0A%09%09%09assert.strictEqual%28super.name%2C+%27Foo%27%29%3B%0A%09%09%7D%0A%09%7D%0A%0A%09return+Foo%3B%0A%7D%3B%0A%0Awrapper%28%29.assertName%28%29%3B&b=%00file.js%00export+default+class+Foo+%7B%7D&o=%7B%0A++bundle%3A+true%2C%0A++outdir%3A+%27dist%27%2C%0A++external%3A+%5B%27external%27%5D%2C%0A++format%3A+%27esm%27%2C%0A++keepNames%3A+true%0A%7D)

### What is actually happening?

the class name is incorrect

### System Info

```Shell
-
```

**Comment by hyf0** [comment]
Related:

- https://github.com/evanw/esbuild/issues/2149
- https://github.com/rollup/rollup/pull/4674
