### ISSUE TITLE
Merge `render` and `finalize` passes into one pass

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#30]
This might lead to remove `SourceMutation` abstraction. We could mutate `MagicSting` directly, rather than using `SourceMutation`.

**Comment by Boshen** [comment]
It would be appreciated if more contexts are added, more specifically the reason behind the phase merge.

**Comment by hyf0** [comment]
> It would be appreciated if more contexts are added, more specifically the reason behind the phase merge.

Currently, we create `SourceMutations` in `finalize` pass and apply `SourceMutation`s on `MagicString` to get the rendered result. Just as the description said we could mutate `MagicString` in `finalize` pass directly and then use it  to get the rendered result.
