### ISSUE TITLE
[Bug]: `augmentChunkHash` doesn't affect parent chunk's hash

### ISSUE THREAD

**Issue by hi-ogawa** [rolldown/rolldown#3049]
### Reproduction link or steps

reproduction: https://stackblitz.com/edit/github-czi3qh?file=README.md

In the reproduction, there are three chunks `entry -> dep1 -> dep2` and `augmentChunkHash` is used to change `dep2` chunk's hash for each build.

### What is expected?

On rollup, it affect parent chunk's hash.

```sh
$ npm run build-rollup
[debug] [ 'entry-JLv7mwm2.js', 'dep1-BjiIigbx.js', 'dep2-FFxFXinQ.js' ]

$ npm run build-rollup
[debug] [ 'entry-DfZTTeuI.js', 'dep1-dlGUTxta.js', 'dep2-nUWkYB-M.js' ]
```

### What is actually happening?

On rolldown, it affects only `dep2` chunk.

```sh
$ npm run build
[debug] [ 'entry-CBcHEEV8.js', 'dep1-CN1ADQTv.js', 'dep2-CeH93yrm.js' ]

$ npm run build
[debug] [ 'entry-CBcHEEV8.js', 'dep1-CN1ADQTv.js', 'dep2-Bo3o0C0E.js' ]
```

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    rolldown: 0.15.0-snapshot-993c4a1-20241205003858 => 0.15.0-snapshot-993c4a1-20241205003858
```

### Any additional comments?

I'm investigating test failures on rolldown vite https://github.com/vitejs/vite/blob/8773916797f8c0f53f3d7eef0542f1c8ffbb9121/packages/vite/src/node/__tests__/build.spec.ts#L63. I'm not sure if this test was working as intended with rolldown, but since v0.15, it became a clear (but flaky) failure.

Comparing with the tests on original Vite, I found the difference of hash and the behavior of `augmentChunkHash` in general.

**Comment by hyf0** [comment]
I guess we should put this

https://github.com/rolldown/rolldown/blob/108331456c9d276bf1608674f01c0d2c9d3a0091/crates/rolldown/src/utils/chunk/finalize_chunks.rs#L82-L84

to 

https://github.com/rolldown/rolldown/blob/108331456c9d276bf1608674f01c0d2c9d3a0091/crates/rolldown/src/utils/chunk/finalize_chunks.rs#L56-L58
