### ISSUE TITLE
[Feature Request]: Support rolldown.transform function

### ISSUE THREAD

**Issue by zhangyuang** [rolldown/rolldown#3063]
### What problem does this feature solve?

Like `esbuild.transform(fileContent: String)`, I hope rolldown can support it.

### What does the proposed API look like?

Refer to esbuild type declaration `export declare function transform<T extends TransformOptions>(input: string | Uint8Array, options?: SameShape<TransformOptions, T>): Promise<TransformResult<T>>
`
If it's allowed, I can provide a pull request to make some contributions to the rolldown.

**Comment by hyf0** [comment]
We have discuss this before and don't have a solid conclusion. For the workaround, you could https://www.npmjs.com/package/oxc-transform directly.

**Comment by hyf0** [comment]
And we actually expose it under the `rolldown/experimental`. You could use if you want. However, it's considered as experimental so far.

**Comment by zhangyuang** [comment]
ok i will try with that



发自我的iPhone


------------------ Original ------------------
From: Yunfei He ***@***.***&gt;
Date: Fri,Dec 6,2024 6:21 PM
To: rolldown/rolldown ***@***.***&gt;
Cc: yuuang ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [rolldown/rolldown] [Feature Request]: Support rolldown.transformfunction (Issue #3063)





 
And we actually expose it under the rolldown/experimental. You could use if you want. However, it's considered as experimental so far.

**Comment by hyf0** [comment]
We would keep `transform` under `experimental` until oxc-transform itself reaches stable status.
