### ISSUE TITLE
First class support for bundling typescript 

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#309]

**Comment by hyf0** [comment]
On hold: need to wait for the oxc transformer. Should support `@rollup-plugin/typescript` as a workaround.

**Comment by trivikr** [comment]
> need to wait for the oxc transformer

Milestone 1 is being tracked at https://github.com/oxc-project/oxc/issues/2859

**Comment by hyf0** [comment]
Done by #1364.
