### ISSUE TITLE
[Feature Request]: improve JSON parse error

### ISSUE THREAD

**Issue by sapphi-red** [rolldown/rolldown#3102]
### What problem does this feature solve?

Reproduction: https://stackblitz.com/edit/github-xv4yss-wdhfvuhj?file=rolldown.config.mjs,src%2Fentry.json

The error position is different by 1 character. Also the output has additional `(` and `)`. This is a bit confusing.
```
Error: Build failed with 1 error:
Error: [PARSE_ERROR] Error: Unexpected token
   ╭─[src/entry.json:1:3]
   │
 1 │ ({)
   │   ┬  
   │   ╰── 
───╯
```

### What does the proposed API look like?

The error should be
```
Error: Build failed with 1 error:
Error: [PARSE_ERROR] Error: Unexpected end of file
   ╭─[src/entry.json:1:2]
   │
 1 │ {
   │ ┬  
   │ ╰── 
───╯
```
The message can be "The closing brace was not found for this opening brace".

**Comment by hyf0** [comment]
Not sure this could be easily done. The error message is came from `serde_json`. And the error is pure syntax error, it's hard give a accurate meaningful message by just looking up the syntax error.

**Comment by hyf0** [comment]
Found this https://github.com/dtolnay/path-to-error

**Comment by IWANABETHATGUY** [comment]
ah, I know that, it came from lazy json export
