### ISSUE TITLE
Refactor: remove all derived `Deserialize` in `rolldown_binding` crate

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#3109]
Yeah. It could be removed. It's basically for `#[serde(rename_all = "camelCase")]`. Seems napi-rs supports this by default.

_Originally posted by @hyf0 in https://github.com/rolldown/rolldown/pull/3103#discussion_r1877541921_

- `struct`s in `rolldown_binding` doesn't need to have a derived `Deserialize` because we won't create them by deserializing anything.
- `#[serde(rename_all = "camelCase")]` is supported by napi-rs itself
- This should reduce binary sizes.
- If we need to rename the property name, we could just simply write
```rust
struct Foo {
  whatever_fooBar: ...,
}
```
`rolldown_binding` won't be consumed by other rust crate.

**Comment by shulaoda** [comment]
There may be some situations that should be kept:
```rust
#[napi_derive::napi(object)]
#[derive(Deserialize, Debug)]
pub struct BindingSourcemap {
  #[serde(skip_deserializing, default = "default_sourcemap")]
  pub inner: Either<String, BindingJsonSourcemap>,
}
```

**Comment by hyf0** [comment]
> There may be some situations that should be kept:
> 
> #[napi_derive::napi(object)]
> #[derive(Deserialize, Debug)]
> pub struct BindingSourcemap {
>   #[serde(skip_deserializing, default = "default_sourcemap")]
>   pub inner: Either<String, BindingJsonSourcemap>,
> }

Why? What will happen if we remove `Deserialize` and `#[serde(skip_deserializing, default = "default_sourcemap")]`?

**Comment by shulaoda** [comment]
> Why? What will happen if we remove `Deserialize` and `#[serde(skip_deserializing, default = "default_sourcemap")]`?

I thought `default="default_stourcemap"` was necessary, but now I understand that we can implement it through trait `Default`.
