### ISSUE TITLE
[Feature Request]: System OS Packages

### ISSUE THREAD

**Issue by trymeouteh** [rolldown/rolldown#3127]
### What problem does this feature solve?

More options to install Rolldown and not need to install NodeJS to simply install Rolldown.

### What does the proposed API look like?

Release Rolldown the following ways for each OS.

- Windows
   - Winget
   - Scoop
- MacOS
   - Homebrew
- Linux
   - Debian/Ubuntu Repo
   - Arch Repo
   - Nix

https://github.com/rolldown/rolldown/discussions/1020

**Comment by Boshen** [comment]
We currently don't have the bandwidth to develop and maintain all these release channels, close as now planned for now.

> and not need to install NodeJS

Node.js is required for Rolldown, distribute Node.js + Rolldown together requires even more effort.
