### ISSUE TITLE
[Bug]: Export statement combining type and value exports is ignored

### ISSUE THREAD

**Issue by nestarz** [rolldown/rolldown#3133]
### Reproduction link or steps

When combining type exports and value exports in a single export statement, the exports are ignored and cause "MISSING_EXPORT" errors when importing.

```typescript
// Working example (separate export statements)
export { ToastViewport }
export { type ToastActionElement }

// Not working (combined export statement)
export { type ToastProps, ToastViewport }

// Import statement that fails
import { ToastViewport } from "./dep1.tsx";
```

### What is expected?

The combined export statement should work correctly, allowing both type and value exports in a single export statement. This is valid TypeScript syntax and works with other bundlers. The ToastViewport value should be properly exported and available for import.

### What is actually happening?

The export is ignored, and when trying to import `ToastViewport`, the following error is thrown:
```
Error: [MISSING_EXPORT] Error: "ToastViewport" is not exported by "tests/dep1.tsx".
    ╭─[tests/jsr/mod.ts:45:10]
    │
 45 │ import { ToastViewport } from "./dep1.tsx";
```

### System Info

```Shell
System:
    OS: macOS 15.0.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 72.84 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.12.0 - ~/.version-fox/temp/1733439600-74842/nodejs/bin/node
    npm: 10.9.0 - ~/.version-fox/temp/1733439600-74842/nodejs/bin/npm
    pnpm: 9.12.3 - ~/.version-fox/temp/1733439600-74842/nodejs/bin/pnpm
    Watchman: 2024.10.21.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 131.0.6778.139
    Safari: 18.0.1
  npmPackages:
    rolldown: workspace:* => 0.15.0
```

**Comment by underfin** [comment]
It is expected behavior, because the `export { type ToastProps, ToastViewport }` is removed at compile ts to js. You also should using `import type { ToastViewport } from "./dep1.tsx";`

**Comment by nestarz** [comment]
Note that `ToastViewport` is not a type, so it's not expected to be removed.

**Comment by hyf0** [comment]
Thanks for repoting.

It's bug a of oxc https://github.com/oxc-project/oxc/pull/7812. I'm fixing it.

**Comment by hyf0** [comment]
Solved in https://github.com/rolldown/rolldown/pull/3150.

So the newest nightly version should work correctly now.
