### ISSUE TITLE
[Bug]: duplicated default import

### ISSUE THREAD

**Issue by nstepien** [rolldown/rolldown#3199]
### Reproduction link or steps

Repo branch: https://github.com/adazzle/react-data-grid/pull/3578
- `git clone https://github.com/adazzle/react-data-grid.git`
- `git checkout rolldown`
- `npm i`
- `npm run build`
- open `lib/bundle.js`
- notice that that the default export of `clsx` is imported multiple times with different identifiers
  ```js
  import clsx, { default as clsx$1, default as clsx$2, default as clsx$3, default as clsx$4, default as clsx$5, default as clsx$6, default as clsx$7 } from "clsx";
  ```

### What is expected?

I'd expect the following import to not result in multiple imports.
```js
import clsx from "clsx";
```

### What is actually happening?

The `clsx` default export is imported under multiple identifiers.

### System Info

```Shell
System:
    OS: Windows 11 10.0.26100
    CPU: (64) x64 AMD Ryzen Threadripper 3970X 32-Core Processor
    Memory: 11.11 GB / 31.88 GB
  Binaries:
    Node: 23.5.0 - C:\Program Files\nodejs\node.EXE
    npm: 11.0.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (131.0.2903.99)
    Internet Explorer: 11.0.26100.1882
  npmPackages:
    rolldown: ^0.15.1 => 0.15.1
```

### Any additional comments?

The CJS output (`lib/bundle.cjs`) does not have this issue.
Rollup does not have this issue either.

**Comment by hi-ogawa** [comment]
I made a minimal-ish repro https://stackblitz.com/edit/github-ugpzvon2?file=src%2Fentry.js

Esbuild also doesn't dedupe same external imports (though in a different way) [esbuild try](https://esbuild.github.io/try/#YgAwLjI0LjIAewogIGZvcm1hdDogImVzbSIsCiAgZXh0ZXJuYWw6IFsiZXh0ZXJuYWwiXSwKICBidW5kbGU6IHRydWUsCn0AZQBlbnRyeS5qcwBpbXBvcnQgZXh0ZXJuYWwgZnJvbSAnZXh0ZXJuYWwnOwppbXBvcnQgZGVwIGZyb20gJy4vZGVwLmpzJzsKCmNvbnNvbGUubG9nKHsgZXh0ZXJuYWwsIGRlcCB9KTsAAGRlcC5qcwBpbXBvcnQgZXh0ZXJuYWwgZnJvbSAnZXh0ZXJuYWwnOwpleHBvcnQgZGVmYXVsdCAnZGVwJzsKCmNvbnNvbGUubG9nKHsgZXh0ZXJuYWwgfSk7) and there's an issue about it https://github.com/evanw/esbuild/issues/475

**Comment by nstepien** [comment]
Other external imports don't exhibit this behavior in my build, that's odd. 🤔 
```js
import { createContext, forwardRef, memo, useCallback, useContext, useEffect, useId, useImperativeHandle, useLayoutEffect, useMemo, useRef, useState } from "react";
import { flushSync } from "react-dom";
import clsx, { default as clsx$1, default as clsx$2, default as clsx$3, default as clsx$4, default as clsx$5, default as clsx$6, default as clsx$7 } from "clsx";
import { Fragment, jsx, jsxs } from "react/jsx-runtime";
```
Maybe it's only an issue with default imports?

**Comment by hi-ogawa** [comment]
Indeed, this seems to only happen for default import. I updated the repro above now output looks like this:

```js
import externalDefault, { externalNamed, default as externalDefault$1 } from "external";

//#region src/dep.js
var dep_default = "dep";
console.log({
	externalDefault: externalDefault$1,
	externalNamed
});

//#endregion
//#region src/entry.js
console.log({
	externalDefault,
	externalNamed,
	dep: dep_default
});

//#endregion
```

**Comment by hyf0** [comment]
Seems `default` doesn't get merged on purpose @IWANABETHATGUY cc

https://github.com/rolldown/rolldown/blob/80d522f92f50a5fa112dd2c93ebdc61135db7bfe/crates/rolldown/src/stages/link_stage/bind_imports_and_exports.rs#L392-L400
