### ISSUE TITLE
[Bug]: `--watch` only works for up to 5 projects

### ISSUE THREAD

**Issue by manuel3108** [rolldown/rolldown#3214]
### Reproduction link or steps

1. Clone [manuel3108/rolldown-watcher-repro](https://github.com/manuel3108/rolldown-watcher-repro)
2. install dependencies with `pnpm i`
3. run rolldown in `watch` mode with `pnpm dev`
4. Everything works as expected, so kill the server
5. Navigate to `rolldown.config.js` and comment in the sixth project: https://github.com/manuel3108/rolldown-watcher-repro/blob/de371e7ec25913a89eee6abd52a24ed8f55164f8/rolldown.config.js#L25
6. run rolldown in `watch` mode with `pnpm dev`

### What is expected?

It shouldn't matter how many projects are specified, watch made should always work.

### What is actually happening?

Initial build is not happening. Rebuild not triggered by modifying any files.

### System Info

```Shell
System:
    OS: Windows 11 10.0.26100
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 4.27 GB / 15.93 GB
  Binaries:
    Node: 22.11.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.9.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.14.4 - ~\AppData\Local\pnpm\pnpm.CMD
    bun: 1.1.22 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (131.0.2903.99)
    Internet Explorer: 11.0.26100.1882
  npmPackages:
    rolldown: ^0.15.1 => 0.15.1
```

### Any additional comments?

Identified in https://github.com/sveltejs/cli/pull/371

**Comment by underfin** [comment]
It could be fixed at https://github.com/rolldown/rolldown/pull/3217

**Comment by manuel3108** [comment]
Can confirm this is now fixed.
