### ISSUE TITLE
[Feature]: export `target` to js side

### ISSUE THREAD

**Issue by underfin** [rolldown/rolldown#3252]
The rust side already add `target` related logic but not export to js side.

The rust side need to do.
- Add `target` to `BindingInputOptions` at https://github.com/rolldown/rolldown/blob/main/crates/rolldown_binding/src/options/binding_input_options/mod.rs#L87
- Normalised it to `BundlerOptions#target` https://github.com/rolldown/rolldown/blob/main/crates/rolldown_binding/src/utils/normalize_binding_options.rs#L243

The js side need to do
- Add `target` to `InputOptions`, https://github.com/rolldown/rolldown/blob/main/packages/rolldown/src/options/input-options.ts#L162
- binding it to rust side at https://github.com/rolldown/rolldown/blob/main/packages/rolldown/src/utils/bindingify-input-options.ts#L76
- Add a test at https://github.com/rolldown/rolldown/tree/main/packages/rolldown/tests/fixtures

related https://github.com/rolldown/rolldown/issues/3243

**Comment by hyf0** [comment]
`es5` is not gonna supported. So `target`'s value shouldn't contains `es5`.

**Comment by nilptr** [comment]
May I give this a try?

BTW, should `target` be added to `BindingOutputOptions` instead of `BindingInputOptions`? Since it seems more relevant to the output.

**Comment by shulaoda** [comment]
> May I give this a try?

Sorry, I didn't see this comment.

**Comment by shulaoda** [comment]
> BTW, should `target` be added to `BindingOutputOptions` instead of `BindingInputOptions`? Since it seems more relevant to the output.

It seems reasonable
