### ISSUE TITLE
[Bug]:  When `output.exports` is set to `named`, the definition of `default` in formats except `ESM` differs from `rollup`

### ISSUE THREAD

**Issue by shulaoda** [rolldown/rolldown#3272]
### Reproduction link or steps

It was discovered in issue #3269, related to #3235.

With `output.exports -> named, output.format -> umd`:

```js
// main.js
export { default as newA, a } from './lib.js';
export { default, b } from './lib2.js';

// lib.js
export const a = 1;
export default class A {}

// lib2.js
export const b = '1';
export default class B {}
```

More details, see the repo: [rolldown](https://stackblitz.com/edit/github-xv4yss-vvoavsyg?file=rolldown.config.mjs,dist%2Fumd.js,src%2Flib2.js,src%2Fentry.js,src%2Flib.js) and [rollup](https://rollupjs.org/repl/?version=4.28.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMCU3QiUyMGRlZmF1bHQlMjBhcyUyMG5ld0ElMkMlMjBhJTIwJTdEJTIwZnJvbSUyMCcuJTJGbGliLmpzJyUzQiU1Q25leHBvcnQlMjAlN0IlMjBkZWZhdWx0JTJDJTIwYiUyMCU3RCUyMGZyb20lMjAnLiUyRmxpYjIuanMnJTNCJTVDbiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTJDJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlN0QlMkMlN0IlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwY29uc3QlMjBhJTIwJTNEJTIwMSUzQiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwY2xhc3MlMjBBJTIwJTdCJTdEJTVDbiUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSUyQyUyMm5hbWUlMjIlM0ElMjJsaWIuanMlMjIlN0QlMkMlN0IlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwY29uc3QlMjBiJTIwJTNEJTIwJzEnJTNCJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBjbGFzcyUyMEIlMjAlN0IlN0QlNUNuJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTJDJTIybmFtZSUyMiUzQSUyMmxpYjIuanMlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyb3V0cHV0JTIyJTNBJTdCJTIyZXhwb3J0cyUyMiUzQSUyMm5hbWVkJTIyJTJDJTIyZm9ybWF0JTIyJTNBJTIyYW1kJTIyJTdEJTdEJTdE)

### What is expected?

```js
...

const a = 1;
class A {}

const b = '1';
class B {}

exports.a = a;
exports.b = b;
exports.default = B;
exports.newA = A;

Object.defineProperty(exports, '__esModule', { value: true });

...
```

### What is actually happening?

```js
...

Object.defineProperty(exports, '__esModule', { value: true });

//#region src/lib.js
const a = 1;
var A = class {};

//#endregion
//#region src/lib2.js
const b = "1";
var B = class {};

//#endregion
exports.a = a
exports.b = b
Object.defineProperty(exports, 'default', {
  enumerable: true,
  get: function () {
    return B;
  }
});
Object.defineProperty(exports, 'newA', {
  enumerable: true,
  get: function () {
    return A;
  }
});

...
```

### Any additional comments?

If this is expected behavior, feel free to close the issue.

**Comment by shulaoda** [comment]
There shouldn't be much difference between `Object.defineProperty(exports, ...)` and `exports.? =`. I'm not sure if we need to be concerned about this.

**Comment by hyf0** [comment]
@underfin cc
