### ISSUE TITLE
[Bug]: output array results in multiple build runs

### ISSUE THREAD

**Issue by nstepien** [rolldown/rolldown#3274]
### Reproduction link or steps

https://stackblitz.com/edit/github-vwaxybzu?file=src%2Ftest.js,rolldown.config.mjs

1. set up an `output` array with 2+ build outputs
2. run the build
3. check how many times the `console.log()` in the plugin's `transform` is called

### What is expected?

Code should only be transformed once: `console.log` should only be called once in the example.

### What is actually happening?

Code is transformed once per output: `console.log` is called once per output in the example.

### System Info

```Shell
System:
    OS: Windows 11 10.0.26100
    CPU: (64) x64 AMD Ryzen Threadripper 3970X 32-Core Processor
    Memory: 10.66 GB / 31.88 GB
  Binaries:
    Node: 23.5.0 - C:\Program Files\nodejs\node.EXE
    npm: 11.0.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (131.0.2903.99)
    Internet Explorer: 11.0.26100.1882
  npmPackages:
    rolldown: ^1.0.0-beta.1 => 1.0.0-beta.1
```

### Any additional comments?

Rollup does not have this issue: there are no additional `transform` runs for example. There is only 1 full build.

Rolldown seems to be doing 1 full build per `output` item, which slows it down.

This is a follow-up to https://github.com/rolldown/rolldown/issues/3200

**Comment by hyf0** [comment]
This is a expected behavior due to how rolldown works internally and we gonna keep this behavior for a long time.

**Comment by IWANABETHATGUY** [comment]
supply more context for those who are curious why we chose this way, TLDR:
1. Multi-format is mostly used by lib user, which is relatively small.
2. Modifying multi-copy of ast/source in one go require some none trivial workload, we don't have enough bandwidth to do that for now(So you may expect we support this in the future).
3. According to the [benchmark](https://github.com/rolldown/benchmarks) , we could build about 10 ~ 20 times(depending on the user's device) when rollup compiles once, so even using this way, there will not be too much difference in bundling time.
