### ISSUE TITLE
the rolldown how to implement `platfrom`?

### ISSUE THREAD

**Issue by underfin** [rolldown/rolldown#333]
The platform is used distinguish node and browser, see https://esbuild.github.io/api/#platform. the rolldown how to do it? 
- Follow esbuild add aplaform option, add internal options for it
- Follow rollup to let user config option, eg external node builtin modules [rollup-plugin-node-externals](https://github.com/Septh/rollup-plugin-node-externals)

**Comment by hyf0** [comment]
Closed by #751.
