### ISSUE TITLE
Need a new strategy for dealing with conflicted identifiers

### ISSUE THREAD

**Issue by underfin** [rolldown/rolldown#389]
https://github.com/rolldown/rolldown/blob/b8555ac034ebe97bb0d7f5bbb46a8a1bd7cf1d7d/crates/rolldown/src/utils/renamer.rs#L36-L56

The current algorithm counts from 0 and may end up with a huge number of allocations and hashes for `candidate_name`.

The challenge is to come up with the most efficient strategy for finding the new name.

One possible solution is to follow esbuild - the assigned new name is a new name on the scope

The original discussion is https://github.com/rolldown-rs/rolldown/issues/365.

**Comment by underfin** [comment]
> 1. the assigned new name is a new name at scope. Esbuild used it.

We should use it, because it will reduce soucemap token `names` size, and it will reduce the overhead of name hash calculate and vlq mapping.

related https://github.com/oxc-project/oxc/issues/2753.

**Comment by hyf0** [comment]
I understand esbuild could assign new name in one shot. But I'm not sure I understand this. Could you give an example to show why now we will generate more types for `names` filed of sourcemap.

And for the generated sourcemap, how much we are bigger than esbuild.

**Comment by hyf0** [comment]
https://github.com/rolldown/rolldown/blob/b8555ac034ebe97bb0d7f5bbb46a8a1bd7cf1d7d/crates/rolldown/src/utils/renamer.rs#L45-L48

The new strategy should find a conflict-less name once rather check many times.

**Comment by IWANABETHATGUY** [comment]
what about use name `${original_name}-${symbol_ref.owner}-${symbol_id}` for the first time, and increasing count,  until we find a the target. e.g.
```
// main.js
const a = 1000;
// lib.js
// SymbolRef(1, 1) (1, 1) is unique for the whole modules
const a  = 10000; // rename to a1$1, for most cases it is enough, but if there is a variable called `a1$1`
                               // we try `a1$11` , `a1$12` and so on.


```

In most cases, we could find it in `O(1)`,

**Comment by IWANABETHATGUY** [comment]
Method two: 
Instead of storing used canonical_names in `HashSet` we could store them in a `HashMap`, here is the algorithm. 

``` js
// main.js
const a = 1000; // visit the top level, insert it into the map, now **the map** : `{a => []}`
// lib.js
const a  = 10000; // find conflict, try `a1` , gotcha!. **the map**:   `{a => [1], a1 => []}`

// a.js
const a = 100000; // find conflict, try `a1`, `a2`, gotcha, **the map**: `a => [1, 2], a1 => [], a2 => []}`
```

Pro: 
  1. we don't need to allocate the new string, just use the set of the key to find if the new candidate postfix has been used before.

Cons: 
  1. Still need a lot of look up if there are many same top-level declarations

**Comment by IWANABETHATGUY** [comment]
I prefer the first one as there is almost no chance of conflict with `name + symbol.ower + symbolId`
