### ISSUE TITLE
`yarn build --no-wasm` could not detect changes of `rolldown_binding`'s dependecies

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#432]
To make sure the [`just test-node`](https://github.com/rolldown-rs/rolldown/pull/431/files#diff-deb9bb56fb122db0b605aa5b63f95a4665c905b18dd670e1fa6c877576a94ff1R49) always running node tests with latest code, `yarn build --no-wasm` need to build `rolldown_node_binding` freshly when there are changes of `rolldown_binding`'s dependecies.

@milesj I'm not sure how to fix this behavior, maybe watch all files of `crates/**/*.rs`?

**Comment by milesj** [comment]
Let me dig into it.

**Comment by hyf0** [comment]
I just try #434 locally, the issue is not solved.

Let's say you changed `crates/rolldown_rstr/src/to_str.rs`. `yarn build --no-wasm` won't detect the change and trigger the fresh build, no matter if changed files are in staged.

**Comment by milesj** [comment]
@hyf0 Ah I was only checking `rolldown_binding`. You can probably glob the whole crates folder then here: https://github.com/rolldown-rs/rolldown/blob/main/scripts/build-node-binding.mjs#L182

**Comment by hyf0** [comment]
> @hyf0 Ah I was only checking `rolldown_binding`. You can probably glob the whole crates folder then here: https://github.com/rolldown-rs/rolldown/blob/main/scripts/build-node-binding.mjs#L182

Cool. I would give a try. `caching` is very useful for running ci locally, it save a lot time just for not building non-changed packages.
