### ISSUE TITLE
Changelog strategy

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#437]
https://github.com/rolldown-rs/rolldown/pull/435 is a start to setup making changelog, but there are something left to be considered.

Currently there are two packages that rolldown repo maintains. They are `@rolldown/node` and `rolldown/wasm`. And we will treat them as a unite thing.

So the new changelog strategy is
- `rolldown` and futured `@rolldown/wasm` will have a synced version
- Having a root changelog that represents `rolldown`
- For github releases, just create a link to the `rolldown` changelog

**Comment by milesj** [comment]
Now that we are using changesets, is there anything else that needs to be done here?

**Comment by hyf0** [comment]
> Now that we are using changesets, is there anything else that needs to be done here?

I guess not. The only left thing to do is using the version of `rolldown` in changelog, which is done in #659.

---

I also remove the changeset part. It turns out if we using single synced version strategy, A [simple script](https://github.com/rolldown/rolldown/blob/f9a52e0d5bbb3957239190fe2df640494367beaf/scripts/bump-version.js) will do the job.
