### ISSUE TITLE
Node binding typing relies on rollup types

### ISSUE THREAD

**Issue by yyx990803** [rolldown/rolldown#439]
But `rollup` isn't installed as a dependency, so we lose type inference in most places.

Since we don't really want `rollup` as a dependency (only its types), we either need a way to bundle rollup types or have to copy the relevant types over. (The latter probably necessary as that also allows us to provide more accurate types in cases where there are properties / APIs that we do not yet support)

**Comment by hyf0** [comment]
+1. Luckly we could just use the rollup's bundled `.d.ts` file.
