### ISSUE TITLE
Improve `SideEffectDetector` for template literal

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#511]
Add following test code to `crates/rolldown/src/ast_scanner/side_effect_detector.rs`.

```rust
#[test]
  fn test_template_literal() {
    assert!(!get_statements_side_effect("`hello`"));
    assert!(!get_statements_side_effect("const foo = ''; `hello${foo}`"));
    // accessing global variable may have side effect
    assert!(get_statements_side_effect("`hello${foo}`"));
    assert!(get_statements_side_effect("const foo = {}; `hello${foo.bar}`"));
    assert!(get_statements_side_effect("tag`hello`"));
  }
}
```

and make them passed.

**Comment by Demivan** [comment]
I will work on this

**Comment by Demivan** [comment]
@hyf0 are there existing side-effect tests somewhere? (esbuild, rollup) Or should I write new ones?

**Comment by hyf0** [comment]
> @hyf0 are there existing side-effect tests somewhere? (esbuild, rollup) Or should I write new ones?

Nope. But there a lot of room to be improved for `SideEffectDetector`. If you are interested in it, you could check it out yourselve. Feel free to DM me in discord or github.
