### ISSUE TITLE
Migrate from Yarn / Lerna to pnpm

### ISSUE THREAD

**Issue by yyx990803** [rolldown/rolldown#543]
Lerna was used for legacy reasons but is actually no longer necessary.

Yarn was also used for legacy reasons - old versions of pnpm had issues in Docker, but should no longer be an issue according to @Brooooooklyn. We should investigate whether moving to pnpm would improve CI time.

**Comment by hyf0** [comment]
It's better do this after I finish merging the `@rolldown/node-binding` and `rolldown` together. I will cue you in this issue @underfin after finishing.

**Comment by Brooooooklyn** [comment]
As a reference, oxc-resolver is already using pnpm and it seems to have no problem: https://github.com/oxc-project/oxc-resolver/blob/main/.github/workflows/release_napi.yml

**Comment by milesj** [comment]
It pnpm's publish/release flow anywhere near as good as lerna's? That's pretty much why everyone still uses lerna.

**Comment by trivikr** [comment]
Most package managers have similar features, and the choice should mostly depend on what most contributors are comfortable with.

Personally, I use a yarn modern and changesets in my projects, and have been happy with.
Since rolldown is aimed at consumption in vite which uses pnpm, would that be the best option?

**Comment by hyf0** [comment]
> It's better do this after I finish merging the `@rolldown/node-binding` and `rolldown` together. I will cue you in this issue @underfin after finishing.

@underfin Done in #545. I update the napi-rs cli to `^3.0.0-alpha.43`. See documents at https://github.com/napi-rs/napi-rs/tree/main/cli/docs.

Commands related to releasing should be no problems, but you might want to checkout out them again.

**Comment by jonkoops** [comment]
Let me know if some assistance is required with this, I've ported a couple of projects from Yarn to PNPM, I'd be willing to take this on if that helps.

> It pnpm's publish/release flow anywhere near as good as lerna's? That's pretty much why everyone still uses lerna.

Should be pretty decent, are there any specific Lerna features you need that are not in PNPM?

**Comment by milesj** [comment]
I'm looking into this.

**Comment by hyf0** [comment]
The migration is finished in #567. But there are some other problems left:

- [x] Make release flow work with using pnpm
- [ ] Install `tree-sitter-go` with pnpm cause errors in my m2pro mac

**Comment by ghiscoding** [comment]
Side note, you can also use [Lerna-Lite](https://github.com/lerna-lite/lerna-lite) with pnpm and `workspace:` protocol (that is actually what is being used within the project). Lerna-Lite is much smaller and every commands are optional packages. A list of large projects that switched to Lerna-Lite are Jest and Volar. Really excited about rolldown! Cheers
