### ISSUE TITLE
Cargo deny

### ISSUE THREAD

**Issue by Boshen** [rolldown/rolldown#61]
See https://github.com/web-infra-dev/oxc/blob/main/deny.toml and https://github.com/web-infra-dev/oxc/blob/3605f7c0fc2421496a869c2b8fb470340903a21f/.github/workflows/ci.yml#L85

**Comment by IWANABETHATGUY** [comment]
can I take this ?

**Comment by hyf0** [comment]
👌no problem

IWANABETHATGUY ***@***.***>于2023年10月30日 周一12:14写道：
