### ISSUE TITLE
Wasm Build

### ISSUE THREAD

**Issue by Boshen** [rolldown/rolldown#63]
Let's check for wasm build early so we don't get caught up with technical debt when we start shipping wasm.

See https://github.com/web-infra-dev/oxc/blob/3605f7c0fc2421496a869c2b8fb470340903a21f/.github/workflows/ci.yml#L57

**Comment by Boshen** [comment]
Shall we add this to the CI workflow?

**Comment by hyf0** [comment]
> Shall we add this to the CI workflow?

I think we should. Will https://github.com/rolldown-rs/rolldown/issues/71 does the job?
