### ISSUE TITLE
Expose path aliases extracted from `tsconfig.json` and `package.json`

### ISSUE THREAD

**Issue by brillout** [rolldown/rolldown#637]
Extracting the path alias information defined by `tsconfig.json#compilerOptions.paths` and `package.json#imports` isn't trivial. Most notably if the user has multiple `tsconfig.json` files.

It could make sense if the path alias information, which Rolldown needs to extracts from `tsconfig.json` and `package.json` anyways, is publicly exposed for tools built on top of Rolldown such as Vite.

If Vite uses that information, then Vite users won't have to define path aliases redundantly in `vite.config.js` anymore. Making [vite-tsconfig-paths](https://github.com/aleclarson/vite-tsconfig-paths) obsolete.

**Comment by hyf0** [comment]
Thanks for bring this up. So far we could tell is that rolldown provided the ability of aliasing, but for

> Extracting the path alias information defined by tsconfig.json#compilerOptions.paths and package.json#imports isn't trivial. Most notably if the user has multiple tsconfig.json files.

we need to evaluate if this should be done by a bundler itself or an upper level tools.

**Comment by brillout** [comment]
FYI esbuild does it (but I don't how complete it is). I see, I guess an alternative would be Rolldown accepting a path alias parameter (albeit less correct since it'd be global and couldn't account for multiple `tsconfig.json`), or a hook like `onResolve()` (although I'm not sure how a JS-land `onResolve()` would slow down everything) :thinking:
