### ISSUE TITLE
Deprecate `@rolldown/node` and `@rolldown/node-binding` on npm

### ISSUE THREAD

**Issue by trivikr** [rolldown/rolldown#657]
### Is your feature request related to a problem? Please describe.

The modules `@rolldown/node` and `@rolldown/node-binding` were deprecated when team acquired `rolldown` on npm https://github.com/rolldown/rolldown/issues/545#issue-2178213174

However, some consumers are still using them https://github.com/rolldown/rolldown/issues/622#issue-2198317065

### Describe the solution you'd like

Deprecate `@rolldown/node` and `@rolldown/node-binding` on npm so that users are aware of the updated module.

Example:
```console
$ npm deprecate @rolldown/node "The package '@rolldown/node' is deprecated. Please use 'rolldown' instead."
```

Docs for npm deprecate: https://docs.npmjs.com/cli/v10/commands/npm-deprecate

### Describe alternatives you've considered
N/A

**Comment by yyx990803** [comment]
Done.

**Comment by trivikr** [comment]
The package [@rolldown/node-binding](https://www.npmjs.com/package/@rolldown/node-binding) is not deprecated.

It can be done by running:
```console
$ npm deprecate @rolldown/node-binding "The package '@rolldown/node-binding' is deprecated. Please use 'rolldown' instead."
```

cc @yyx990803

**Comment by trivikr** [comment]
> The package [@rolldown/node-binding](https://www.npmjs.com/package/@rolldown/node-binding) is not deprecated.

Created a new issue https://github.com/rolldown/rolldown/issues/720
