### ISSUE TITLE
Deprecate `@rolldown/node-binding` on npm

### ISSUE THREAD

**Issue by trivikr** [rolldown/rolldown#720]
### Is your feature request related to a problem? Please describe.

The module `@rolldown/node-binding` were deprecated when team acquired `rolldown` on npm https://github.com/rolldown/rolldown/issues/545#issue-2178213174

However, it's not deprecated on npm.

### Describe the solution you'd like

Deprecate `@rolldown/node-binding` on npm so that users are aware of the updated module.

Example:
```console
$ npm deprecate @rolldown/node-binding "The package '@rolldown/node-binding' is deprecated. Please use 'rolldown' instead."
```

Docs for npm deprecate: https://docs.npmjs.com/cli/v10/commands/npm-deprecate

### Describe alternatives you've considered
N/A

### Additional Context

In previous issue reported in https://github.com/rolldown/rolldown/issues/657, but only `@rolldown/node` was deprecated.

**Comment by hyf0** [comment]
Thanks for reporting this. I don't think users would rely on `@rolldown/node-binding` directly. So it's probably enough for just deprecating `@rolldown/node`.
