### ISSUE TITLE
support mix esm and cjs module

### ISSUE THREAD

**Issue by underfin** [rolldown/rolldown#74]
If esm module mixed cjs require syntax, it can worked becuase treat it  as esm.

- Using mix esm import and cjs require
- Using mix esm export and cjs require

So here only has cjs exports syntax will be as cjs module.

If cjs module mixed esm syntax
- Using cjs export and mix esm import , it will give an warning and treat it as cjs.
https://esbuild.github.io/try/#YgAwLjE5LjMALS1idW5kbGUgLS1zcGxpdHRpbmcgLS1vdXRkaXI9ZGlzdCAtLWZvcm1hdD1lc20AZQBlbnRyeS5tanMAaW1wb3J0ICcuL2EnCm1vZHVsZS5leHBvcnRzID0gMQAAYS5qcwBpbXBvcnQgJy4vYicKbW9kdWxlLmV4cG9ydHMgPSAxAABiLmpzAG1vZHVsZS5leHBvcnRzID0gMQ
- Using cjs export and mix esm export,It will give an warning and treat it as esm(cjs export is ignored).
https://esbuild.github.io/try/#YgAwLjE5LjMALS1idW5kbGUgLS1zcGxpdHRpbmcgLS1vdXRkaXI9ZGlzdCAtLWZvcm1hdD1lc20AZQBlbnRyeS5qcwBpbXBvcnQgJy4vYScKbW9kdWxlLmV4cG9ydHMgPSAxAABhLmpzAGV4cG9ydCBjb25zdCBhID0gMQptb2R1bGUuZXhwb3J0cyA9IDEAAGIuanMAbW9kdWxlLmV4cG9ydHMgPSAx

- [ ] warning for syntax error
- [x] implement mix commnjs and esm.

**Comment by hyf0** [comment]
We have supported enough features related to this. Consider this issue solved and open a new one for new features.
