### ISSUE TITLE
Rolldown should supporting plugin order and have a fully investigation on it.

### ISSUE THREAD

**Issue by moushicheng** [rolldown/rolldown#770]
## what is plugin order?
[rollup doc](https://rollupjs.org/plugin-development/#build-hooks)
> order: "pre" | "post" | null
> If there are several plugins implementing this hook, either run this plugin first ("pre"), last ("post"), or in the user-specified > position (no value or null).
```js
export default function resolveFirst() {
	return {
		name: 'resolve-first',
		resolveId: {
			order: 'pre',
			handler(source) {
				if (source === 'external') {
					return { id: source, external: true };
				}
				return null;
			}
		}
	};
}
```
If several plugins use "pre" or "post", Rollup runs them in the user-specified order. This option can be used for all plugin hooks. For parallel hooks, it changes the order in which the synchronous part of the hook is run.

## current situation
rolldown cant support order, And we still need to discuss some implementation details  to avoid rollup's technical debt.

for Example:
1. On which end(js or rs) should this feature be implemented ?
2. ...
3. ...

I am currently investigating rollup's plugin feature
## if you be familiar with rollup plugin or you have any ideas, welcome discussion here

**Comment by underfin** [comment]
close it by https://github.com/rolldown/rolldown/pull/1929
