### ISSUE TITLE
Auto generated esbuild tests.

### ISSUE THREAD

**Issue by IWANABETHATGUY** [rolldown/rolldown#78]
1. A tool automatically converts esbuild tests to snapshot test

**Comment by hyf0** [comment]
This will be a huge improving on DX if this issue solved. 🫡

**Comment by Boshen** [comment]
Are we able to extract code via ast-grep? Or any codemod from `go`.

**Comment by IWANABETHATGUY** [comment]
> Are we able to extract code via ast-grep? Or any codemod from `go`.

nice suggestion, I will have a look.
