### ISSUE TITLE
Migrate esbuild's tests of `packagejson`

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#783]
We want to migrate esbuild's tests defined in https://github.com/evanw/esbuild/blob/main/internal/bundler_tests/bundler_packagejson_test.go to this repo.

## Guidance

Take the first test [`TestPackageJsonMain`](https://github.com/evanw/esbuild/blob/44e746965d783646f97daf3d0617ff816727e7fb/internal/bundler_tests/bundler_packagejson_test.go#L13-L37) as an example.

1. All you do is creating corresponding files like I did in https://github.com/rolldown/rolldown/pull/782.

2. After create the test files, try pass the test. __However, it doesn't matter if the test is failed. If the test is failed, just rename the test folder from `main` to `.main`. And it would be skipped automatically__

3. Remove the test name you just added in this test list https://github.com/rolldown/rolldown/pull/781/files

3. Commit the change with message like `test(esbuild/packagejson): add ....`. Remember run `just roll` to see if everything is ok.

4. Open a PR.

**Comment by zhusjfaker** [comment]
maybe i can handle this

**Comment by zhusjfaker** [comment]
should i try to use memory file like esbuild test case or like your mr make disk file in rolldown test dir and migrate all of case in your txt list @hyf0

**Comment by hyf0** [comment]
@zhusjfaker Use disk files. This would allow us to reuse the ability that `cargo test` provided and need to write a complicated test suite ourselves. Thank you in advanced.

**Comment by zhusjfaker** [comment]
@hyf0  I've added a PR that's not quite finished yet，until it finished, i will comment here and call for you
