### ISSUE TITLE
Generate `_test.schema.json` automatically

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#785]
See https://rolldown.rs/contrib-guide/testing first.

Currently we have a json shcema file `_test.schema.json` in  https://github.com/rolldown/rolldown/blob/main/crates/rolldown_testing/_test.scheme.json.

It's generated by run `cargo run --bin gen_test_config_schema` manually. The executable code is defined in https://github.com/rolldown-rs/rolldown/blob/ee3739d65dfed173dbc582270f7cc89017dc285a/crates/rolldown_testing/bin/gen_test_config_schema.rs. 

So what we want here is that if someone edited the [`BundlerOptions`](https://github.com/rolldown/rolldown/blob/main/crates/rolldown_common/src/inner_bundler_options/mod.rs#L16-L40) or `TestConfig`, we hope that `_test.schema.json` could be updated automatically while running `cargo test`

I tried to achieve this with cargo's `build.rs` feature, but got pull out for other things.

**Comment by kainzc** [comment]
Hey @hyf0

Gonna try and figure this out.

**Comment by hyf0** [comment]
> Hey @hyf0
> 
> Gonna try and figure this out.

Thank you in advanced.

**Comment by kainzc** [comment]
@hyf0 ,

I had an implementation question. I have the build.rs developed and working, but am encountering a small issue. The script relies on the gen_test_config_schema binary to generate _test.schema.json automatically based on changes to BundlerOptions or TestConfig. The challenge arises during a clean build or when the binary hasn't been compiled prior to running the build.rs script, leading to a scenario where the script cannot find the binary to execute it.

While subsequent builds (after the binary is compiled) don't face this issue, the initial failure on a clean build could potentially confuse new contributors or disrupt automated build processes. I've considered a few approaches to resolve this, such as integrating the binary's logic directly into the build script or creating an automated pre-build step, but I wanted to consult with you on the best path forward.

**Comment by hyf0** [comment]
I was thinking moving the code of `gen_test_config_schema.rs` to `build.rs` rather than executing  `gen_test_config_schema.rs` in `build.rs`.

**Comment by kainzc** [comment]
Encountered a hurdle integrating gen_test_config_schema.rs functionality into build.rs directly, as recommended. The main challenge is accessing and utilizing the TestConfig struct from rolldown_testing within build.rs for schema generation. Directly defining or reusing TestConfig in build.rs poses difficulties due to scope and dependency management.

What would be the best method to access TestConfig for schema generation within build.rs, adhering to the suggestion of integrating gen_test_config_schema.rs directly?

**Comment by hyf0** [comment]
Yeah I met this too. Tried to solve it but got pull out for other things. However, I was going to extract `TestConfig` to a new crate called `rolldown_testing_config`. With it, you should be able to access the `TestConfig` in `build.rs` of `rolldown_testing`.

**Comment by kainzc** [comment]
Sounds good will do it this way.

**Comment by kainzc** [comment]
Hey @hyf0 , Im trying to push code but am getting a permission denied error. Is there a list I need to be added to before I can push? Thanks

**Comment by hyf0** [comment]
@kainzc  https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project

**Comment by hyf0** [comment]
Closed by #891.
