### ISSUE TITLE
Passing `BindingResolveOptions#alias` from js to rust with maintaining order

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#790]
https://github.com/rolldown/rolldown/blob/c304a0dcde43234654626f8695cd745f37de4d33/crates/rolldown_binding/src/options/binding_input_options/binding_resolve_options.rs#L8-L11

### Use `Option<Vec<(String, Vec<String>)>>>`

The problem is that NAPI-RS so far doesn't support tuples

### Define a temporary struct like

```rust
pub struct AliasItem {
  pub name: String,
  pub paths: Vec<String>,
}
```

and write `Option<Vec<AliasItem>>>`.

---

I personally prefer using tuples on this case. However this requires [discussing with NAPI-RS if this feature is really needed](https://github.com/napi-rs/napi-rs/issues/1372).

**Comment by PengBoUESTC** [comment]
@hyf0 I will try to work for this

**Comment by hyf0** [comment]
> @hyf0 I will try to work for this

Thanks. I just had words with @Brooooooklyn. He's also welcome for anyone to implement https://github.com/napi-rs/napi-rs/issues/1372. So I will encourage you do the hard way first. However, it's also ok to use the temporary struct solution. Free to go.

**Comment by PengBoUESTC** [comment]
> > @hyf0 I will try to work for this
> 
> Thanks. I just had words with @Brooooooklyn. He's also welcome for anyone to implement [napi-rs/napi-rs#1372](https://github.com/napi-rs/napi-rs/issues/1372). So I will encourage you do the hard way first. However, it's also ok to use the temporary struct solution. Free to go.

I use `struct ` to solve this problem,  I will subscribe this issue [napi-rs/napi-rs#1372](https://github.com/napi-rs/napi-rs/issues/1372), and try to deal with this later (it's too hard for me now +_+).
