### ISSUE TITLE
Implement `renderStart` hook.

### ISSUE THREAD

**Issue by underfin** [rolldown/rolldown#821]
The `renderStart` hook is run at before generate chunks, [here](https://github.com/rolldown/rolldown/blob/main/crates/rolldown/src/bundler.rs#L132) ia s good place to call it.

For plugin implement, you can follow `generate_bundle` hook, add it to [here](https://github.com/rolldown/rolldown/blob/main/crates/rolldown_plugin/src/plugin_driver/output_hooks.rs#L6).

The typing is `(outputOptions: OutputOptions, inputOptions: InputOptions) => void`, you should use js side normalized options.

Also, if you add a test at [here](https://github.com/rolldown/rolldown/tree/main/packages/rolldown/tests/fixtures/plugin) would be nice.

**Comment by PengBoUESTC** [comment]
I will try
