### ISSUE TITLE
Emit warnings for circular dependencies

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#831]
https://github.com/rolldown/rolldown/pull/830 detected circular dependencies but didn't emit warnings.

### Where to emit the warnings

You could emit the warnings in the place where I left a comment `// TODO: emit warning`.

### How to emit warnings

You could reference how https://github.com/rolldown/rolldown/pull/398 did it.

**Comment by PengBoUESTC** [comment]
I will try

**Comment by hyf0** [comment]
> I will try

Thank you in advanced.
