### ISSUE TITLE
Reliable way for benchmark rolldown in rust on CI

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#869]
The old way https://github.com/rolldown/rolldown/blob/6f01071b31f5255ce0a0427a3a67c4757f96504d/.github/workflows/bench.yaml is more reliable than current one, we should bring back it and combine it with https://github.com/benchmark-action/github-action-benchmark.

**Comment by hyf0** [comment]
Failed in https://github.com/rolldown/rolldown/actions/runs/8716470140/job/23910046846?pr=897

**Comment by underfin** [comment]
fixed
