### ISSUE TITLE
Render charts of benchmark data

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#870]
github-action-benchmark already support it in https://github.com/benchmark-action/github-action-benchmark?tab=readme-ov-file#screenshots. What we need to is to add an extra step to push the generated html to the repo we want to store. https://github.com/rolldown/benchmark-results-storage/blob/main/benchmark-node-output.json

**Comment by underfin** [comment]
Close it because the benchmark data has some noise because the GitHub action using machines is different.
