### ISSUE TITLE
The `resolveDynamicImport` hook implemention

### ISSUE THREAD

**Issue by underfin** [rolldown/rolldown#883]
Because the `resolveId` hook includes all kinds of `static import/dynamic import/require`, maybe has another kind at the future. 
I want to only run `resolveDynamicImport` hook at js side, to make the rust API clear.
If you have some advice, please let me know.

**Comment by hyf0** [comment]
There are a lot of usages here

- https://github.com/search?q=resolveDynamicImport+language%3ATypeScript&type=code&l=TypeScript

- https://github.com/search?q=resolveDynamicImport+language%3AJavaScript+&type=code

I'm thinking we follow this pattern for compatibility. For static import and require we call `resolveId`. For dynamic import, we call `resolveDynamicImport` hook.


---

I'm also wondering for an ID which is both static and dynamic imported, how rollup behaves. Does it call `resolveId` and `resolveDynamicDependecy` both? Or it's a UB.

---edited

Just found how rollup handle this

https://github.com/rollup/rollup/blob/49b57c2b30d55178a7316f23cc9ccc457e1a2ee7/src/ModuleLoader.ts#L733-L747

It will emit a warning if there are differences.

With such behaviors, for dynamic import,
1. we could first call `resolveDynamicDependecy`
2. if it returns resolved id, we just use the result.
3. if it returns nothing, we fallback to `resolveId` and call it.

This way we could be compatible with the rollup behaviors without breaking too much things.

**Comment by underfin** [comment]
> I'm thinking we follow this pattern for compatibility. For static import and require we call resolveId. For dynamic import, we call resolveDynamicImport hook.

I think maybe it is better for the compatibility only happen at rollup compat(js side). The rollup is designed for esm syntax, so it's API is not suitable for rolldown. 

To implement this we need to run `resolveDynamicImport` when `resolveId` kind is `dynamic-import`, here something is not great because we need to implement a small `PluginDriver` at js side to call `resolveDynamicImport` hook.

**Comment by hyf0** [comment]
> 1. we could first call `resolveDynamicDependecy` for `dynamic-import`.
> 2. if it returns resolved id, we just use the result.
> 3. if it returns nothing, we fallback to `resolveId` and call it.

I'm more prefer this way. Whether we implement `resolveDynamicDependecy` in rust or node are both fine to me.
