### ISSUE TITLE
Migrate all esbuild's tests

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#938]
- ~bundler_css_test~
- [x] #989
- [x] bundler_default_test
- [x] bundler_glob_test
- [x] bundler_importstar_test
- [x] bundler_importstar_ts_test
- [x] bundler_loader_test
- [x] bundler_lower_test
- [x] bundler_packagejson_test #783 
- [x] bundler_splitting_test
- ~bundler_test~
- [x] bundler_ts_test

---

We need to try to run all the tests, and keep a diff of passed and failed in a snapshot. We need to make sure nothing hangs or crashes.

**Comment by hyf0** [comment]
`bundler_css_test` is not needed so far.

Tests related to typescript could be migrated but not passed due to we don't have builtn typescript transpile support. Others should be fine.

**Comment by chiehw** [comment]
I'm confused about two place: 
1. why do some test folders start with dot?
2. why do some test folders not have artifacts.snap file?

For example: 
https://github.com/rolldown/rolldown/pull/984/files
![image](https://github.com/rolldown/rolldown/assets/99897242/f21066c9-3ebc-4932-a6cb-fd6f6e0fd855)

**Comment by hyf0** [comment]
@chiehw  https://rustdoc.swc.rs/testing_macros/attr.fixture.html#ignoring-a-test

**Comment by chiehw** [comment]
ok, thanks. Why ignore these tests? a little curious. It seems that some test can be passed.

**Comment by hyf0** [comment]
> ok, thanks. Why ignore these tests? a little curious. It seems that some test can be passed.

Mainly due to there aren't passed. If you find passed tests that are ignored, it's welcome to open a PR to enable them.

**Comment by zhusjfaker** [comment]
https://github.com/evanw/esbuild/blob/main/internal/bundler_tests/bundler_loader_test.go

i will work it @hyf0  @IWANABETHATGUY

**Comment by hyf0** [comment]
> https://github.com/evanw/esbuild/blob/main/internal/bundler_tests/bundler_loader_test.go
> 
> i will work it @hyf0 @IWANABETHATGUY

Thanks. The loader feature is complete yet. But you could start migrating these cases.

**Comment by IWANABETHATGUY** [comment]
> https://github.com/evanw/esbuild/blob/main/internal/bundler_tests/bundler_loader_test.go
> 
> i will work it @hyf0 @IWANABETHATGUY

You could use https://github.com/rolldown/rolldown/blob/main/scripts/misc/gen-esbuild-test.mjs, to auto-generated related tests.

**Comment by zhusjfaker** [comment]
> > https://github.com/evanw/esbuild/blob/main/internal/bundler_tests/bundler_loader_test.go
> > i will work it @hyf0 @IWANABETHATGUY
> 
> You could use https://github.com/rolldown/rolldown/blob/main/scripts/misc/gen-esbuild-test.mjs, to auto-generated related tests.

thank you master

**Comment by zhusjfaker** [comment]
> > https://github.com/evanw/esbuild/blob/main/internal/bundler_tests/bundler_loader_test.go
> > i will work it @hyf0 @IWANABETHATGUY
> 
> You could use https://github.com/rolldown/rolldown/blob/main/scripts/misc/gen-esbuild-test.mjs, to auto-generated related tests.

nice scrtipt

**Comment by zhusjfaker** [comment]
> > https://github.com/evanw/esbuild/blob/main/internal/bundler_tests/bundler_loader_test.go
> > i will work it @hyf0 @IWANABETHATGUY
> 
> You could use https://github.com/rolldown/rolldown/blob/main/scripts/misc/gen-esbuild-test.mjs, to auto-generated related tests.

nice script 666
