### ISSUE TITLE
Validate `_config.json` using `_config.schema.json`

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#939]
See https://rolldown.rs/contrib-guide/testing#how-test-cases-are-defined first.

So we have #785 now. Next we want is to validate the `_config.json` using `_config.schema.json` to avoid invalid input.

Validate the input, before parsing it. Panic if it's invalid.

https://github.com/rolldown/rolldown/blob/7b64957632f0942ff69dac7899f74f8d29141b6d/crates/rolldown_testing_config/src/lib.rs#L35-L38

**Comment by katungi** [comment]
Hey @hyf0 , Can I give this a shot?

**Comment by hyf0** [comment]
> shot?

Sure. Thanks.

**Comment by hyf0** [comment]
@katungi Hi. Are you still working on this?

**Comment by katungi** [comment]
Hey @hyf0 yes I am. Will be done by tomorrow.

**Comment by chiehw** [comment]
> Validate the input, before parsing it. Panic if it's invalid.

Does this mean checking `_config.json` in build.rs? @hyf0

**Comment by IWANABETHATGUY** [comment]
Closed in favor of #1042
